### ISSUE TITLE
No download after EPUB is packed

### ISSUE THREAD

**Issue by Humanoid-Human** [dteviot/WebToEpub#1005]
After clicking "Pack EPUB", the progress bar fills up as normal. Using Firefox's inspect network tool thingy (Ctrl + Shift + E) it shows that the tool is getting information from all of the selected chapters. But once it finishes there is no "Save As" screen. If the option "Don't popup 'SaveAs' dialog when save Epub" is checked, then it downloads properly. 
This error occurs with RoyalRoad and Wordpress. I haven't checked any other sites yet.
Web browser is Firefox. OS is Ubuntu 22.04. 

**To Reproduce** (I don't know if this is an issue on my end or not, so I don't know if it can be reproduced on other machines)
1. Go to a RoyalRoad story page
2. Click on WebToEpub extension
3. Click "Pack Epub"
4. No "Save As" dialog.

**Comment by gamebeaker** [comment]
@Humanoid-Human i was not able to reproduce this error i used [https://www.royalroad.com/fiction/70724/ginseng-and-yew](https://www.royalroad.com/fiction/70724/ginseng-and-yew). Which firefox version did you use and what are your other extensions? (Try turning off all other extensions and try again.)

**Comment by Humanoid-Human** [comment]
Using Firefox 113.0.2. Turned off all extensions (other than WebToEpub, obviously) and the problem still occurs.

**Comment by dteviot** [comment]
@Humanoid-Human 
I've had reports of similar problems in the past.  It's usually due to one of two things.
1. Conflict with another extension.
2. Conflict with one of the browser's settings.  (Sorry, can't remember which one, and quick (ha) search of issues didn't bring it up.)

My suggestion, install a developer version of Firefox (you can have both Developer and Normal instances installed at same time) and try running WebToEpub in the dev version.  That's probably the easiest way.

FWIW, the reason WebToEpub has problems with saving file is because there's no proper API for saving files.  So, need to do a hack to make it work, and the hack can have issues.

**Comment by Humanoid-Human** [comment]
ok so i fixed the problem
it turned out that none of the save as dialogs or the 'upload a file' dialogs were working at all
i fixed it with `sudo apt install xdg-desktop-portal xdg-desktop-portal-gtk` and now it works without the "Don't popup" option enabled

**Comment by dteviot** [comment]
@Humanoid-Human 
Thanks for letting me know.
