### ISSUE TITLE
[Enhancement] LNMTL Parse by Volume

### ISSUE THREAD

**Issue by KiraYamatoSD** [dteviot/WebToEpub#105]
Is it possible to add the feature to parse the content from LNMTL that is sorted by volume?
For example, separating the novels by volume instead inserting everything to one huge file. That way, a single epub file will not be cluttered.

**Comment by dteviot** [comment]
@KiraYamatoSD
> separating the novels by volume instead inserting everything to one huge file.

I'm not entirely sure what you're asking for.  Are you asking that instead of generating a single epub, you want multiple epub files generated, each epub holding one volume?
If this is what you want, you can use calibre to split an epub into multiple files.  See: 
http://www.howtogeek.com/168444/how-to-easily-merge-and-split-ebooks/ or http://dearauthor.com/ebooks/using-epub-split-create-individual-books-collection-box-sets/

If this isn't what you require or is not a satisfactory solution, please let me know.

**Comment by dteviot** [comment]
Closing, No response from original requester means I don't know what's wanted.
