### ISSUE TITLE
Please add site https://novelsemperor.com/

### ISSUE THREAD

**Issue by abetestnow** [dteviot/WebToEpub#1087]
Can you please update the parser for https://novelsemperor.com/?
They change the website and the extension can no longer grab any data.
Thank you,
Abe

**Comment by Jackdemon1999** [comment]
"I tried to download it, but the download appears, and no chapter is displayed. It used to work before, but since they had a website remodel, it stopped working."
"I tried to follow the procedure mentioned on the website https://novelsemperor.com/ #1059, but I didn't succeed. Do you think there might be any solution or method I can use to make it work?"

**Comment by abetestnow** [comment]
I can't think of anyway to get it work without updating the parser for the website.

**Comment by abetestnow** [comment]
Just tried it out and it worked perfectly.  Thank you for updating the extension.
Abe

**Comment by dteviot** [comment]
@Jackdemon1999 @abetestnow 
Updated version (0.0.0.156) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 3 to 21 days.
