### ISSUE TITLE
Track Default Parser settings on a Site Basis

### ISSUE THREAD

**Issue by xd1986k** [dteviot/WebToEpub#109]
Hello. 
Would it be possible to add a profile system for unsupported sites so we can save the specific class/id needed to extract text to avoid repetitiveness? 

i.e.  When the default parser is used, have it remember the "Element with Chapter Content" settings that were used for each site and reload those settings when you try additional pages on the site.

**Comment by dteviot** [comment]
@xd1986k 
How does this differ from https://github.com/dteviot/WebToEpub/issues/110?

**Comment by dteviot** [comment]
@xd1986k
This sounds like a reasonable suggestion and I'll see what can be done.
Note, my preferred solution in a case like this would be to create a new parser for the site(s).  Then everyone gains the benefit.  And I've put a lot of effort into building the extension so that creating new parsers is easy for anyone with a basic knowledge of HTML and Javascript.

**Comment by dteviot** [comment]
@xd1986k 
Version 0.0.0.33 has been updated with requested functionality.
The "Find Content" settings are saved on a per "host name" basis for each site.  (Note, the save of settings occurs when the "Pack EPUB" button is pressed.)
Your version should update within 24 hours.
Please re-open this issue if there are problems.
