### ISSUE TITLE
Select parser for each page on a page by page basis

### ISSUE THREAD

**Issue by Cupbox** [dteviot/WebToEpub#110]
Would it be possible to process url's on a per site basis.
As in we have 
**Dark Translations**
div class=entry-content
**NovelsReborn**
div class=chapter-body

So if we have an index like so
novelreborn.com/blah/1
darktranslations.com/blah/4
It will process darktranslations and novelsreborn with the specific div class selected for them in a profile.

**Comment by dteviot** [comment]
@xd1986k
I think what you're asking me is that when the default parser is used, you want it to remember the "Element with Chapter Content" settings that were used for each site and reload those settings when you try additional pages on the site.

i.e. When you get the message "No parser found for this URL. Default parser will be used. You need to specify how to obtain content for each chapter.")  If you change the "Element with Chapter Content" settings, then those settings are remembered for that site's hostname.  The next time the Default parser sees that hostname, it loads those settings as the initial values.

Can you please confirm this is what you're asking for?

Incidentally, why did you pick Dark Translations as an example? It is a Wordpress based site and seems to be handled correctly.e.g. If I try: https://darktranslations.wordpress.com/mad-god-en/volume-1/,
the wordpress parser is selected and as far as I can tell, correctly parsed.
Is there some problem with darktranslations that I haven't noticed?

**Comment by xd1986k** [comment]
@dteviot 
Yes that is what I was requesting in #109 . I'm sorry for being unclear.
As for this issue I meant that when we encounter a TOC containing items from two sites like so
![upload2](https://cloud.githubusercontent.com/assets/13769570/24334435/92ea09e6-1283-11e7-978b-7d411099fd7a.png)
As seen in the picture the parser fails upon encountering a URL which can't be parsed with the parser selected for the specific base URL(RoyalRoad in this case). 
Would it be possible for the extension to switch to the Wuxia World parser when it encounters a WW URL in the above instead of failing.  

As for Dark Translations, it's working fine. I just chose a site randomly.

**Comment by dteviot** [comment]
@xd1986k 
First off, thank you for your revised description of the problem, it's much easier to understand now.

> Would it be possible for the extension to switch to the Wuxia World parser when it encounters a WW URL in the above instead of failing.

This behaviour has already been requested.  See: https://github.com/dteviot/WebToEpub/issues/99#issuecomment-269366086
Unfortunately, due to the architecture of the extension, this change requires a lot of work and is unlikely to be done for several months at least.  Until it is done, might I suggest downloading the two sets of chapters into two epubs, and then merging the epubs with Calibre?  https://www.epubor.com/how-to-merge-multiple-epub-ebooks.html

**Comment by xd1986k** [comment]
Yeah, that's what I'm doing currently. Thank you for the suggestion.

**Comment by dteviot** [comment]
@xd1986k, @buthub
I've committed a Proof of Concept implementation of this to the experimental tab branch, if you'd like to install from source and try it out to let me know how it works for you.

**Comment by xd1986k** [comment]
I've tried it out on a few url's and it works perfectly. Thanks!

**Comment by dteviot** [comment]
Sample URLs I've tested.
- [x] https://isekailunatic.wordpress.com/tsuki-ga-michibiku-isekai-douchuu/
