### ISSUE TITLE
Is it Possible to make this work on NovelUpdates

### ISSUE THREAD

**Issue by AndreaHasani** [dteviot/WebToEpub#112]
Can you make it so this can gather all the chapters from NovelUpdates Index . NovelUpdates only adds a "?pg=5" to its url for the so it should be possible to make the extension smart enough to read the chapters from all the pages.

**Comment by dteviot** [comment]
@AndreaHasani
Unfortunately, It's not going to be possible to do this very well until https://github.com/dteviot/WebToEpub/issues/110 is done.
The problem is, the current design of WebToEpub means it uses the page with the chapter of contents to select the parser needed to extract the chapter contents.  However, NovelUpdates points to a large number of different sites, with different layouts. (So, needing different parsers.)  But WebToEpub can't tell which parser is needed as:
1. The site with the chapters is NovelUpdates.
2. The chapter URLs given by NovelUpdates don't point to the chapters either, they're links to NovelUpdates, with HTTP 302 redirects.

So, at this point in time, best I can do is have NovelUpdate parser guess on how to get the content for each chapter, but it's going to be very hit-and-miss which stories work and which don't.


Also, what happened on the very first story I tried.

Pick a novel.  http://www.novelupdates.com/series/help-gooogle-sensei/

Examine the hyperlink for "v3 prologue" chapter.  It contains two links.
```html
<td width="20%">
	<a title="v3 prologue" class="chp-release rand5251s" href="http://www.novelupdates.com/extnu/385535/" rel="nofollow">v3 prologue</a>
        <a title="v3 prologue" class="chp-release rand3421s" href="http://www.novelupdates.com/extnu/385536/" rel="nofollow">v3 prologue</a>
</td>
```

The first link returns an empty page.
The second link gives a HTTP 302 redirect to https://kntranslation.wordpress.com/2016/12/18/quick-release-prologue-is-short-after-all/
Which doesn't have the text, instead, it has a link to https://kntranslation.wordpress.com/help-gooogle-sensei-v3-pro, which ultimately has the chapter text.

**Comment by dteviot** [comment]
@AndreaHasani
NovelUpdates has informed me that they do **not** want WebToEpub to gather chatpers from their site.(see: http://forum.novelupdates.com/threads/rest-api-to-get-novel-details.36157/)
So, I'm not going to implement this.
