### ISSUE TITLE
Add site https://www.readawrite.com

### ISSUE THREAD

**Issue by bichitoxxx** [dteviot/WebToEpub#1132]
**Describe the bug**
It manages to take the complete table of chapters of the page but not the content of them, it does not take the text, only images and banner. This is the first time something like this has happened to me, I don't know if it's due to the language or if it's a problem with the page.
https://www.readawrite.com/a/8eb3926a025bb86899f452f3dd675f04?r=user_page

- Browser
Microsoft Edge
Versión 119.0.2151.97 (Compilación oficial) (64 bits)

![Screenshot_1](https://github.com/dteviot/WebToEpub/assets/29169926/e39fd7c7-0ac0-41c1-b011-33c865bf28ed)
![Screenshot_2](https://github.com/dteviot/WebToEpub/assets/29169926/a1b699fd-4177-4efb-824e-02d9d97c1fc8)
![screenshoteasy](https://github.com/dteviot/WebToEpub/assets/29169926/ab874e87-a0a1-4fb1-bd83-9f2c5d856042)

**Comment by dteviot** [comment]
@bichitoxxx 

Has it ever worked?

**Comment by bichitoxxx** [comment]
I don't think I had tried it on this page on other similar pages if, and In that one it worked, it also took links, ads and things that appeared on the page but also the text. It's the first time I don't save the text, I'm just not on the rest of the page.  I'm not really sure I used it here. Excuse me.

**Comment by dteviot** [comment]
@bichitoxxx 

> page but not the content of them, it does not take the text, only images and banner.

That's because the content isn't directly in the HTML.  Instead, the &lt;div id="articleContents"&gt; is populated after the page loads.  Unfortunately, as the text is Thai (which I can't read) and this site is doing other things to make my life difficult, I can't figure out where and the text is being loaded form.  At least, not without spending more time on it than I'm willing.

You might like to see if https://github.com/martial-god/Benny-Scraper can help you.  It works somewhat differently to WebToEpub, It loads pages into a browser and then pulls the text.  So bypasses this sort of problem.

**Comment by bichitoxxx** [comment]
First, thank you for the incredible work you always do, it is admirable, and it is understandable that you cannot and do not have time for everything.
Thank you also for the recommendation, although I don't understand anything about this type of thing and I have looked at the page that you recommend but I don't know where to start and I don't even know how to use it, my ability is limited to using browser addons and little. further.
  Thank you always, maybe one day someone can come up with something that we can use.
