### ISSUE TITLE
RoyalRoad issue when downloading

### ISSUE THREAD

**Issue by Bavirebe** [dteviot/WebToEpub#1140]
**Describe the bug**
When attempting to pack the epub I get this pop up error message:

WARNING: Site 'c10.patreonusercontent.com' has sent an Access Denied (403) error.  You may need to logon or satisy a CAPTCHA before WebToEpub can continue.

Clicking ok loads a new error page (moz-extension://faebf0a1-320c-4caa-9076-c6da9eb74f16/popup.html?id=136):

Error: Fetch of image 'https://c10.patreonusercontent.com/4/patreon-media/p/post/62649413/50570cecd5834176af5d5f0a386b090d/e30%3D/1.png?token-time=1646265600&token-hash=85DZQ8WQE0-5gaIAU_1oOfXogJuutJCKfjdT88O9HSg%3D' for page 'https://www.royalroad.com/fiction/36804/the-devils-foundry/chapter/846945/chapter-10-ladys-port' failed with network error 403. This is an intermittent error. If you retry in a few minutes, it may succeed. promptUserForRetry@moz-extension://faebf0a1-320c-4caa-9076-c6da9eb74f16/js/HttpClient.js:55:19
onResponseError@moz-extension://faebf0a1-320c-4caa-9076-c6da9eb74f16/js/HttpClient.js:48:25
checkResponseAndGetData@moz-extension://faebf0a1-320c-4caa-9076-c6da9eb74f16/js/HttpClient.js:188:45
wrapFetchImpl/<@moz-extension://faebf0a1-320c-4caa-9076-c6da9eb74f16/js/HttpClient.js:182:31

**To Reproduce**
1. Go to 'https://www.royalroad.com/fiction/36804/the-devils-foundry'
2. Click on 'extension'
3. Begin epub pack, it will error out 10 chapters into book 2

**Expected behavior**

**Desktop (please complete the following information):**
 - OS: Windows
 - Browser: both Chrome and Firefox
 - Both latest updates

**Additional context**
Could be a permissions thing? I'm logged in as a user of RoyalRoad.

**Comment by dteviot** [comment]
@Bavirebe 
The problem is the page https://www.royalroad.com/fiction/36804/the-devils-foundry/chapter/846945/chapter-10-ladys-port has an invalid image.  You can see this for yourself if you go to the page. 
![image](https://github.com/dteviot/WebToEpub/assets/5157081/95909574-dbeb-4144-a014-011df89e0c30)
The given location of this image is invalid.
Default behaviour of WebToEpub is to stop when it is unable to load a page/image.  However, you can tell WebToEpub to carry on by going to "Advanced Options" and checking the "Skip chapters that return HTTP 404 error" box.
![image](https://github.com/dteviot/WebToEpub/assets/5157081/363a11ef-6638-40b5-9b60-9f98a2be7b22)

Note,
1. You'll also have to press the "Skip" option when the error appears.
2. It looks like Chapter 11 has same problem
3. You might like to send a message to the author, asking them to fix the link to the image.

**Comment by Bavirebe** [comment]
Aha! I tried the skip chapters with the 404 error checkbox, but I still got the errors. I ended up unselecting all the image boxes and it worked. Thank you!

**Comment by dteviot** [comment]
@Bavirebe 
I got the error messages, but if you click the "Skip" option when the error appears, then WebToEpub carries on.  At least, it did for me when I tried the above chapter.

**Comment by dteviot** [comment]
Going to call this solved.  Let me know if you don't agree.
