### ISSUE TITLE
Error on line 1 at column 1106: error parsing attribute name

### ISSUE THREAD

**Issue by swanknight** [dteviot/WebToEpub#1150]
**Describe the bug**
Trying to download anything from freewebnovel.com results in these errors (randomly, multiple chapters).
The result, when opening the EPUB, these chapters are incomplete.

**Novel**
https://freewebnovel.com/global-dungeon-my-support-is-too-strong.html

**Error**
> Warning, unable to convert chapter 'Chapter 754 - 754: Bad News' from 'https://freewebnovel.com/global-dungeon-my-support-is-too-strong/chapter-754.html' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. 
> Conversion error message was: (This page contains the following errors:error on line 1 at column 1106: error parsing attribute name
> Below is a rendering of the page up to the first error.)
> 

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser: Edge 120
 - Version 0.0.0.156 (WebToEpub)

**Comment by dteviot** [comment]
@swanknight 
Looking at https://freewebnovel.com/global-dungeon-my-support-is-too-strong/chapter-754.html, the problem is there's a malformed HTML tag.  Specifically:

&lt;font &lt; div&gt; The Great Peacock King continued, “My young friend Lu, do you want to hear my speculation about the Bronze Temple?” &lt;/font&gt;


Refer to https://github.com/dteviot/WebToEpub/issues/1123, for why this is a problem that WebToEpub is unable to fix.
You'll need to manually fix the chapter(s) in the epub with something like Calibre.
