### ISSUE TITLE
[Baka-Tsuki parser] Grab image description

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#117]
Some images in Baka-Tsuki may have description in the image page.
Such as: https://www.baka-tsuki.org/project/index.php?title=File:ImoIre_0242.png

Suggestions:
Run a check to see if there's any extra text in the image page. In the example above, the text seems to be in a `div` with the `id` `mw-imagepage-content`.
If the image page doesn't have any extra text, this div is empty (doesn't contain any elements). 
For example: https://www.baka-tsuki.org/project/index.php?title=File:Mondaiji-tachi_ga_isekai_kara_kuru_soudesu_yo_v11_Index.jpg

**Comment by dteviot** [comment]
Unfortunately, it's not that simple.
Looking at first example , the &lt;div&gt; element contains a "Translators Notes and References" section.

How to solve this problem is also complicated by the fact that I only have one example of this file with extra text.
I looked at a number of Baka-Tsuki images, but was unable to find any other instances of this.
This makes it difficult to know if a solution that works for this page would be sufficiently general to work with other instances.

**Comment by toshiya44** [comment]
> How to solve this problem is also complicated by the fact that I only have one example of this file with extra text.

True. I fear that I might've missed any images that contains text in the file page, as I had never even considered it until this particular image came to my attention. I'll keep an eye out for now.

**Comment by dteviot** [comment]
@toshiya44 
Has been 2 months with no update.
Closing for time being.
Can be re-opened when more examples are available.
