### ISSUE TITLE
Please update https://noveltop1.org/ it's not working anymore.

### ISSUE THREAD

**Issue by itsonagain** [dteviot/WebToEpub#1230]
Please update the site https://noveltop1.org/ I used to use it very often but its not working anymore. 
I keep getting this error: "WARNING: Site 'thenovelbin.org' has sent an Access Denied (403) error.  You may need to logon or satisfy a CAPTCHA before WebToEpub can continue."

Thanks!

**Comment by dteviot** [comment]
@itsonagain 

It's exactly what the message is telling you.  The site is rejecting WebToEpub because it thinks you're not a person.  You need to open one of the chapters in the browser (or perhaps several pages) until the CloudFlare "are you a human?" page triggers.  (The technical name for this is a CAPCHA.) Once that happens, you can use WebToEpub.  Note, you might like to set the Advanced Options to only 1 chapter every few seconds, or the site will probably get suspicious of you.

Also, seems like this site is just another alias for NovelBin or perhaps https://thenovelbin.org, as that's where the content seems to be held.
Anyway, I've updated WebToEpub so that it's aware of the alias.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://noveltop1.org/bok/alchemy-emperor-of-the-divine-dao#tab-chapters-title, chapter 1 and 2

For my notes: 28 minutes work

**Comment by dteviot** [comment]
@itsonagain 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
