### ISSUE TITLE
Fannovels.com parser not detected

### ISSUE THREAD

**Issue by Adrianjack** [dteviot/WebToEpub#1233]
**Describe the bug**
Fannovels.com is using default parser when it is mentioned in Readwnparser.

**To Reproduce**
1. Go to https://www.fannovels.com/
2. Use WebToEpub
3. Parser not detected 

**Expected behavior**
I checked Readwnparser and found fannovels.com in there. So it should work, right? It didn't.

**Screenshots**
![Screenshot_20240302_105227_Kiwi Browser](https://github.com/dteviot/WebToEpub/assets/139681740/0183a3b7-f70f-42ba-8250-72bb114b77d6)

**Smartphone (please complete the following information):**
 - Device: [Samsung A73]
 - OS: [Android 14]
 - Browser [kiwi browser]
 - Version [?]

**Additional context**

**Comment by ImLJS** [comment]
Fannovels.com is added in experimental version of webtoepub. You need to install that to work!

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers.

**Comment by dteviot** [comment]
@Adrianjack 

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.

Note, this might not help you, as newer versions of Firefox for mobile have limited extension support.
