### ISSUE TITLE
[Bug] Error parsing (wuxiaworld) chapters with collpased titles

### ISSUE THREAD

**Issue by Randshot** [dteviot/WebToEpub#125]
The parser throws an error when parsing (wuxiaworld) chapters with collapsed titles (possibly collapsed content in general).
One such chapter can be found here: [Chapter](http://www.wuxiaworld.com/issth-index/issth-book-4-chapter-417)

Error text:
```
Warning, unable to convert chapter 'Next Chapter' from 'http://www.wuxiaworld.com/issth-index/issth-book-4-chapter-417' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre.
```

**Comment by dteviot** [comment]
@Randshot 

Strictly speaking, the problem in the link you give isn't the collapsed titles.  The problem is the collapsed title has quotes (") in it which results in a malformed title attribute.  Shown below.
```HTML
<span class="collapseomatic colomat-hover" id="id129" tabindex="" title="Chapter 417 (Click to show " spoiler"="" title)"="">Chapter 417 (Click to show "spoiler" title)</span>
```
This isn't valid HTML, but most browsers will handle it.  However, XHTML (used by EPUB 2) is less tolerant.
The ideal way to fix this would be to update WebToEpub emit EPUB 3, as that uses HTML 5 instead of XHTML. However, I'm not going to get around to doing that for a while.
Fix for immediate problem is to strip the collapseomatic information as it's not wanted in the epub anyway.  
Note to self: steps for doing this are:
- Remove style from any element with a class starting with "collapseomatic_content"
- Remove any collapseomatic triggers.  (Has a class of "collapseomatic" and an id that starts with "id")

**Comment by dteviot** [comment]
@Randshot
Removal of collapseomatic elements has been added to version 0.0.0.38 which has been sent to Chrome store.  You version should automatically update within 24 hours.

**Comment by Randshot** [comment]
@dteviot Thanks for quick fix!

**Comment by dteviot** [comment]
Need to emit EPUB 3
