### ISSUE TITLE
There's an issue with this site in not grabbing the whole chapter --> https://shanghaifantasy.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1254]
Hello!

I've created a few epubs from this site before and usually had no issue, but when trying to create an epub with this specific novel -- **https://shanghaifantasy.com/novel/criminal-investigation-notes/** -- I saw that a specific range of chapters had faltered with Webtoepub by encountering an issue which had only grabbed the **first sentence** of the chapter. The single sentence that was generated into the near-empty xhtml file was also not ensconced in paragraph tags, but simply placed as **bare text** as well.

![image](https://github.com/dteviot/WebToEpub/assets/161710539/b75976f0-e8b3-41b4-967d-b6768a2bc66b)

This issue specifically affected Chapters 18 - 43. It's unclear why this error occurred since all other chapters, outside of this range, grabbed the full content. Given the source layout, using the default parser was a bit difficult.

Thank you for all the help, it's much appreciated.

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

The problem is the site format changes for those chapters.  If you look at, say chapter 17, the text is all within a &lt;div&gt; element with a class that includes "contenta".  And nearly all the text is inside &lt;p&gt; tags.  (The first sentence is NOT in a &lt;p&gt; tag.)
For chapter 18, there's only one sentence within the "contenta" &lt;div&gt;, the rest of the text is in the following &lt;div&gt; elements.
And for other chapters it's even worse.  e.g. Chapter 23 the paragraphs don't share the same parent element as the "contenta"

As a quick hack, I've got WebToEpub to use the first "div.flex" element if it looks like there's only a sentence there.  Unfortunately, this results in quite a bit of HTML that can't be converted into XHTML being collected.  Cleaning that out was a pain.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://shanghaifantasy.com/novel/criminal-investigation-notes/, chapters 18, 23, 43

For my notes: 84 minutes work

**Comment by plsbenice-immadeofjelly** [comment]
Thank you so much, it fixed this issue! xx

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Updated version (0.0.0.158) has been submitted to Firefox store and is avaiable now
Due to technical issues (i.e. I pressed the wrong button) udated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
