### ISSUE TITLE
Is it possible to grab the endnotes at the bottom of the chapter for this source --> https://travistranslations.com/

### ISSUE THREAD

**Issue by plsbenice-immadeofjelly** [dteviot/WebToEpub#1259]
Hello! I was creating an epub from this source and noticed that an element at the bottom of the chapter (like an author's note) isn't part of the generated content because it's outside the current detected range.

So, if I may ask, would it be possible to also grab these translator notes at the bottom of the chapter as well, without affecting the overall clean format by only including this specific data, but not pulling in any other unnecessary html elements?

**Example Table of Contents:** https://travistranslations.com/novel/20024/after-transmigrating-i-made-the-antagonist-cry/#toc

**Example Chapter with an Endnote:** https://travistranslations.com/novel/20024/after-transmigrating-i-made-the-antagonist-cry/chapter-2/

Please view the below image for the location of the "author note" that appears at the bottom of some chapters:

![image](https://github.com/dteviot/WebToEpub/assets/161710539/a640aff0-9a7a-439c-afd0-7cbcf5a0950e)

I tried using the Default Parser to no avail since I couldn't exactly grab the specific range without inadvertently pulling in other irrelevant source data.

But through the parser, I found that these "author notes" are ensconced in a `<div>` tag:

```
<hr class="mt-4 border-t-2" />
			<div class="flex flex-col py-1 pb-2">
				<strong class="mb-2 text-xl">boilpoil's notes:</strong>
```

Thank you for all your help! xx

**Comment by dteviot** [comment]
@plsbenice-immadeofjelly 

Try this. 
It's annoying, because there's no tag that says "this is the note".  So, just have to guess and hope.
It's not great for spoilers (text might be invisible).  And I don't know if it will work for the notes for other stories.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://travistranslations.com/novel/20024/after-transmigrating-i-made-the-antagonist-cry/, chapters 1 to 5

For my notes: 36 minutes work

**Comment by plsbenice-immadeofjelly** [comment]
Thank you very much!!!! I tried it with other novels that had these notes and it worked as well! Thanks again!! xx
