### ISSUE TITLE
[Bug] Can't parse hellping.org

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#126]
I noticed I can't parse hellping.org, or even grab something from it using manually made links.
I don't think it's a "protection" on the content, just  the site changed something (new them for once).

Can this be fixed? I was trying to fetch Bokushino and the super long title one.

The error log:

Could not find content element for web page 'https://hellping.org/bokushinu-v1/bokushinu-v1-prologue/'. Error: Could not find content element for web page 'https://hellping.org/bokushinu-v1/bokushinu-v1-prologue/'.
    at chrome-extension://pdjgnlommckobgkiialndbmakmkebdjp/js/Parser.js:267:27
    at <anonymous>

**Comment by dteviot** [comment]
@typhoon71 
> Can this be fixed? 

Yes, they've changed the layout, so the code in the parser that looks for bits is no longer looking in the right places.

The file you want is HellpingParser.js
The function getChapterUrls(dom) looks for the URLs for the chapters.  
```javascript
    getChapterUrls(dom) {
        let menu = util.getElement(dom, "ul", e => e.id === "nav");
        return Promise.resolve(util.hyperlinksToChapterList(menu));
    }
```
Currently it's looking for all the hyperlinks in a &lt;ul&gt; element with an id of "nav".
If you look at one of the pages e.g. https://hellping.org/may-your-soul-rest-in-magdala/  You can see that the list of chapters (the menu bar at top of page) is in the &lt;nav&gt; element with an id of "main-navigation".  So change function to

```javascript
    getChapterUrls(dom) {
        let menu = util.getElement(dom, "nav", e => e.id === "main-navigation");
        return Promise.resolve(util.hyperlinksToChapterList(menu));
    }
```

Likewise, it's looking for the chapters content with findContent(dom), which is now in  &lt;div&gt; element of class "post-content".    So that function becomes

```javascript
    findContent(dom) {
        return util.getElement(dom, "div", e => e.className === "post-content");
    }
```

Then there's findChapterTitle(dom) which collects the title of each chapter (as that's not in the "content" element. ) The element we want is the &lt;h1gt; element of class "page-title".    So this function becomes

```javascript
    findContent(dom) {
        return util.getElement(dom, "h1", e => (e.className === "page-title"));
    }
```

Congratulations.  You now know enough to write your own parsers (at least for the simple sites.)

**Comment by dteviot** [comment]
@typhoon71
D'oh.
Just noticed. Hellping parser is also used for NanoDesu site.  So making these changes will break NanoDesu.  Need to copy the old Hellping parser for Nanodesu.

**Comment by dteviot** [comment]
@typhoon71 
Should now be fixed in ExperimentalTabMode branch.

**Comment by typhoon71** [comment]
Thanks, it works now.
Tested with Bokushino, Magdala, and Long title just to harass ppl.
