### ISSUE TITLE
Please add site https://www.wuxiabox.com/

### ISSUE THREAD

**Issue by Mielanjelo** [dteviot/WebToEpub#1263]
Please add https://www.wuxiabox.com/ formerly known as wuxiabee.org, thank you

**Comment by dteviot** [comment]
@Mielanjelo 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.wuxiabox.com/novel/infinite-film-and-television-trumpet-mania.html

For my notes: 44 minutes work

**Comment by dteviot** [comment]
@Mielanjelo 

@ImLJS  Note, now WebToEpub looks at page formatting, rather than URL to recognize this site.  Hopefully won't have to update WebToEpub to fix for a while.

Updated version (0.0.0.158) has been submitted to Firefox store and is available now
Due to technical issues (i.e. I pressed the wrong button) updated version can't be submitted to Chrome store for an indefinite period.
Chrome might be available in 6 to 42 days.
