### ISSUE TITLE
Site https://www.asianovel.net/ fails to grab chapters

### ISSUE THREAD

**Issue by querrieoh** [dteviot/WebToEpub#1279]
**Describe the bug**
When using extension on site https://www.asianovel.net/ , no chapters show up.

**To Reproduce**
1. Go to 'https://www.asianovel.net/story/2882/'
2. Click on 'WebToEpub Extension'
3. Scroll down to 'Chapter List'
4. See error (No Chapters)

**Expected behavior**
See chapters 1 to 148 listed

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/67846733/38ffb280-fefd-4acb-8a13-baf989aca940)

**Desktop (please complete the following information):**
 - OS: [Windows]
 - Browser [Brave]
 - Version [Brave
 Version 1.64.122 Chromium: 123.0.6312.122 (Official Build) (64-bit)](https://brave.com/latest/)]

**Smartphone (please complete the following information):**
 - Did not try on smartphone

**Additional context**
Chapters DO show up when using default parser and manually setting it up

**Comment by dteviot** [comment]
@querrieoh 

Site has changed layout since parser was last written. Updated parser.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.asianovel.net/story/2882/, chapter 1
* https://www.asianovel.net/story/1907/ chapter 2  (story has 303 chapters)

For my notes: 20 minutes work

**Comment by querrieoh** [comment]
@dteviot I get the chapter list now, thank you!

**Comment by dteviot** [comment]
@querrieoh 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
