### ISSUE TITLE
Website no longer able to download epub: https://syosetu.com/ 

### ISSUE THREAD

**Issue by yunc1008** [dteviot/WebToEpub#1283]
**Describe the bug**
Main website is https://syosetu.com/, which has been working until recently. I tested with a few novels and none of them download any longer. Using Chrome, Windows 10. WebtoEpub 0.0.0.158 extension.

The specific page tested is: https://ncode.syosetu.com/n6316bn/

TypeError:   Cannot read properties of null (reading 'nextSibling')--
at SyosetuParser.cleanInformationNode   (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/SyosetuParser.js:79:25)
at SyosetuParser.populateInfoDiv   (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:356:18)
at SyosetuParser.makeInformationEpubItem   (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:342:14)
at SyosetuParser.webPagesToEpubItems   (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:314:33)
at SyosetuParser.epubItemSupplier   (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:302:30)
at packEpub   (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:187:37)
at   chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/main.js:154:20

**To Reproduce**
1. Go to https://ncode.syosetu.com/n6316bn/
2. Click on WebToEpub extension
3. The chapters will generate, but will not be automatically checked in the checkbox. Click select all and pack epub.
4. After loading all chapters, will return error listed above "Cannot read properties of null".

**Expected behavior**
Expected behavior is after loading all chapters it will trigger successful download.

**Screenshots**
![image](https://github.com/dteviot/WebToEpub/assets/167159024/9e844d4e-305c-4d3b-8296-e80c04204e02)
![image](https://github.com/dteviot/WebToEpub/assets/167159024/3c890d95-3a70-4a9f-b419-68013e5335fe)

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser Chrome
 - Version 0.0.0.158

**Comment by dteviot** [comment]
@yunc1008 

Looks like this was fixed in commit https://github.com/dteviot/WebToEpub/commit/43f123be20df0bb61bafb4bc809a4aa60b9fc0d5. This code is currently in the test version, but has not yet been updated to Chrome or Firefox stores.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with: 
* https://ncode.syosetu.com/n6316bn/

For my notes: 17 minutes work

**Comment by yunc1008** [comment]
Confirmed it now works. Thank you very much, really appreciate your work!

**Comment by dteviot** [comment]
@yunc1008 

Updated version (0.0.0.159) is now available from Firefox and Chrome stores.
