### ISSUE TITLE
Please add site https://mtlarchive.com/

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#1310]
pls add https://mtlarchive.com/

**Comment by 1k-7** [comment]
Could you please add the site

**Comment by 1k-7** [comment]
@dteviot can you please

**Comment by dteviot** [comment]
@Finks82 @1k-7 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://mtlarchive.com/novel/invincible-god-of-killing-system, chapters 1 to 4  (story with 690 chapters)
* https://mtlarchive.com/novel/i-starting-from-celestial-dragons-infinite-summons, chapter 1,  (story with 190 chapters, i.e. 2. ToC pages)
* https://mtlarchive.com/novel/navigation-start-with-celestial-dragons-and-take-down-hancock, chapter 1.  (Story with 65 chaters.  i.e. 1 ToC page)

Note, did not try to fetch above chapter 100, that required a subscription.

For my notes: 171 minutes work
Some time lost dealing with bug with Clouldflare cookies when site doesn't have cookies.
But mostly due to difficulty in REST calls to get Chapters.
Having to search array of objects for novel ID was ugly.

**Comment by dteviot** [comment]
@Finks82 @1k-7 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
