### ISSUE TITLE
Mtlarchive.com parser

### ISSUE THREAD

**Issue by TheFirstProgenitor** [dteviot/WebToEpub#1312]
Can you please create a parser for mtlarchive.com

**Comment by Kiradien** [comment]
Looks like this page is also under cf and has the same 403 issues creating a parser as Fanfiction.net currently has. 
![image](https://github.com/dteviot/WebToEpub/assets/68683574/eb8d0c60-3006-4596-811a-5554737cb15c)

Generic parameters look like they would have worked fine if w2e could open the page.

**Comment by dteviot** [comment]
@Kiradien 

Actually, looking at the site, it would need a custom parser.  The content for the chapters is not in the HTML pages, instead it's JSON that is obtained by a REST call.  (So I don't know why they're bothering with CF.)

**Comment by dteviot** [comment]
Also, duplicate https://github.com/dteviot/WebToEpub/issues/1310

**Comment by dteviot** [comment]
@TheFirstProgenitor @Kiradien 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://mtlarchive.com/novel/invincible-god-of-killing-system, chapters 1 to 4  (story with 690 chapters)
* https://mtlarchive.com/novel/i-starting-from-celestial-dragons-infinite-summons, chapter 1,  (story with 190 chapters, i.e. 2. ToC pages)
* https://mtlarchive.com/novel/navigation-start-with-celestial-dragons-and-take-down-hancock, chapter 1.  (Story with 65 chaters.  i.e. 1 ToC page)

Note, did not try to fetch above chapter 100, that required a subscription.

For my notes: 171 minutes work
Some time lost dealing with bug with Clouldflare cookies when site doesn't have cookies.
But mostly due to difficulty in REST calls to get Chapters.
Having to search array of objects for novel ID was ugly.

**Comment by 1k-7** [comment]
![Screenshot_20240525_104409_Firefox Nightly](https://github.com/dteviot/WebToEpub/assets/169595478/4369883f-0b98-4fce-a2db-c0b507bc2941)

**Comment by 1k-7** [comment]
Already logged in

**Comment by 1k-7** [comment]
@dteviot it doesn't work?

**Comment by dteviot** [comment]
@1k-7 
You're using firefox?  You might need to open a chapter normally to trigger the Cloudflare "are you a human" page.
I just tested desktop version.  Got chatpers 1 to 3.  (Which is all I tried for)

**Comment by dteviot** [comment]
Did have to make a fix for https://mtlarchive.com/novel/i-can-copy-talent-novel.  Novel ID was in position 23 of the array.  Updated test versions on Google Drive.

**Comment by 1k-7** [comment]
> @1k-7 You're using firefox? You might need to open a chapter normally to trigger the Cloudflare "are you a human" page. I just tested desktop version. Got chatpers 1 to 3. (Which is all I tried for)

It works...

**Comment by dteviot** [comment]
@TheFirstProgenitor 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
