### ISSUE TITLE
Chinese characters showing up as Specials Unicode Block

### ISSUE THREAD

**Issue by SinD3825** [dteviot/WebToEpub#1317]
**Describe the bug**
I tried to download a novel from jjwxc.net and when using the default parser, what showed up for me in the test window was a combo of mostly specials unicode block and a bunch of different languages (armenian, korean, arabic, random fractions, etc.)

**To Reproduce**
1. Go to <https://www.jjwxc.net/onebook.php?novelid=5126430>
2. Click on WebtoEpub extension, start default parser
3. URL of first chapter: <https://www.jjwxc.net/onebook.php?novelid=5126430&chapterid=1>
4. CSS selector for element holding content to put into EPUB: div.novelbody
5. Click "Test"

**Expected behavior**
I wasn't expecting the specials unicode block and gibberish to show up. I tried to download this novel again on another Chinese website <https://www.52shuku.vip/jiakong/pm/h4tA.html> and it worked, but this website splits up the chapters and is missing some extras/edits, so I was hoping that there was a way I could get it to work on JJWXC.

**Screenshots**
Trying to use default parser on jjwxc.net
<img width="1076" alt="Screen Shot 2024-05-15 at 5 18 54 PM" src="https://github.com/dteviot/WebToEpub/assets/43595499/e38d06b9-cf62-411d-9c94-7fdb04b65cb7">

**Desktop (please complete the following information):**
 - OS: macOS
 - Browser: chrome
 - Version 0.0.0.159

Thanks so much for all that you do! Really appreciate your hard work :)

**Comment by dteviot** [comment]
@SinD3825 

The problem is this site www.jjwxc.net, is not say what encoding it's using for the content.  Therefore, WebToEpub is assuming the content is UTF-8, which doesn't work because the site is (probably) encoded with gb18030.  Handling this requires writing a custom parser.

That said, it looks like writing a parser would not be hugely difficult.  (It does not appear to be using JSON for chapter content, and it looks like all chapters of a story might appear on a single Table of Contents page.  (If you can confirm this, or provide link to story where Table of Contents spans multiple pages, that would be helpful.)

Alternately, I COULD extend the default parser to allow you to tell WebToEpub the encoding, but I suspect that would be beyond most people to handle.

If you'd like me to write a parser for the site, please create a new issue (with answers to my questions) and I'll add it to my task queue.

**Comment by SinD3825** [comment]
I just submitted a new issue, thank you so much!
