### ISSUE TITLE
Patreon worked yesterday but no today

### ISSUE THREAD

**Issue by Shadow15888** [dteviot/WebToEpub#1323]
**Describe the bug**
I Used webtoepub on patreon yesterday worked just fine today will not work

**To Reproduce**
1. I logged in to patreon
2. went to collections for author
3. went into extension and clicked pack 
4. got error message multiple times

**Expected behavior**
usually just just starts working

**Screenshots**
![Screenshot_20240521_231132_Kiwi Browser](https://github.com/dteviot/WebToEpub/assets/170488911/d5bd8d05-3058-4d28-976c-7aefce793747)

**Desktop (please complete the following information):**

**Smartphone (please complete the following information):**
 - Device: samsung fold 5
 - OS: [android
 - Browser kiwi but also firefox
 - Version 14

**Additional context**

**Comment by dteviot** [comment]
@Leifman35 @Shadow15888 
Please provide URL that fails

**Comment by Leifman35** [comment]
> @Leifman35 @Shadow15888 Please provide URL that fails

Well, what i am doing with web2epub is going to a specific creator i subscribe to that posts a story (or chapters) per se, say for example https://www.patreon.com/cerim/posts (can be done on every other channel you are subscribed to or otherwise)
which results in this for example:
https://i.imgur.com/gRzWFSh.png
then after usually when i would click to generate the epub, it doesn't technically 'start' and i get this:
https://i.imgur.com/WCxQ9Iz.png
followed by seeing that it didn't  technically download any of the pages etc' as it would usually do (usually there would be green checkmarks/it will grab everything etc'):
https://i.imgur.com/kGLsvyg.png

**Comment by dteviot** [comment]
@Leifman35 
Thanks.  This is want I wanted.  
There's a couple of non-protected items for that author.  I'll look into it and see what's happened.  But not tonight. I need some sleep.

**Comment by Leifman35** [comment]
> @Leifman35 Thanks. This is want I wanted. There's a couple of non-protected items for that author. I'll look into it and see what's happened. But not tonight. I need some sleep.

Thank you. much appreciated whenever you can get to it. and have a good rest!

**Comment by PolarisFx** [comment]
I'm still running 0.157 from the GDrive on mobile from the last time patreon got borked and it's having no issues with Patreon. I just got notified of the latest issue, and demands that I get on here and do something about it. But I'm having no issues.

**Comment by grenskul** [comment]
Having the same issue on 1.159 but 1.157 works

**Comment by dteviot** [comment]
FYI.  Older versions can be found https://github.com/dteviot/WebToEpub/releases?page=1, open the "Assets" part of each release.

**Comment by Leifman35** [comment]
Yeah downgraded 1 version and cna confirm it works (i believe on 1.158 too) and ill admit, i haven't even thought of downgrading the version... figured it was a new patreon sorta change rather than something changing with a new version? oh well.
I do have to comment tho, that before it broke the new 'changes' to the web2epub grabbing stuff from Patreon (removing the date the post was made and numbers in the bottom if there are comments etc) was something i absolutely LOVED.
Now with the downgrade those changes are gone and it's back to having the date that post was made and the numbers in the bottom. i manually edit them out but i hope that when the newest version is fixed, these new changes i loved so much are back :) and thanks for the tip to downgrade! it's a life saver meanwhile while the latest isn't fixed yet

**Comment by dteviot** [comment]
@grenskul @PolarisFx @Leifman35 

Well, that sucked.
Patreon changed layout again.  Multiple issues to fix.

1. JSON schema changed.
2. Handle post with image. https://www.patreon.com/posts/book-3-cover-103253763
3. Filter out bad links in Table of Contents

Also bug in WebToEpub.  Code to handle Cloudflare cookies throws exception if site has no cookies.  (What sort of site has no cookies?!)

Note, not sure how long this will continue working for.  Patreon has been making a lot of changes recently.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.patreon.com/cerim (had post with image)
* https://www.patreon.com/ddwebb

For my notes: 117 minutes work

**Comment by pounat** [comment]
Thank you @dteviot ! Can also confirm the test version on Chrome worked for me today!

**Comment by dteviot** [comment]
@PolarisFx @pounat @grenskul @Leifman35 @Shadow15888 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
