### ISSUE TITLE
[Bug] Check Filename before running

### ISSUE THREAD

**Issue by Selene29** [dteviot/WebToEpub#134]
The field for the filename lets you enter whatever one wants,
therefore it also allows the following illegal chars " \ / : * ? " < > | ".

When running the app it will work without error but it can't write the file.

Solution:
When clicking "Pack Epub" first check the filename for these chars and then
either throw an error message or remove or replace them.

**Comment by dteviot** [comment]
Notes.
Not as easy as it looks.  
Firstly, it interacts with 
* https://github.com/dteviot/WebToEpub/issues/136
* https://github.com/dteviot/WebToEpub/issues/133

Also, what's a legal filename depends on the host OS.  https://kb.acronis.com/content/39790
Would be simpler to have the a SaveAs dialog appear, except when it opens, it changes the focus.  So when running in popup mode (as opposed to Tab), that makes Chrome and Firefox unload the extension before the save occurs.
The obvious solution to that is remove popup mode.

**Comment by dteviot** [comment]
Turns out, Chrome won't show SaveAs dialog if filename illegal.
So, have to pre-check filename.
On reflection, as Windows is most restrictive case, just check if name is illegal for Windows and give error if it is.
Could check for other OSes, and check for each case. But that just adds additional complexity for minimal gain.
So, lowest common denominator it is.

**Comment by toshiya44** [comment]
Windows's restrictions covers most other OS's restriction as well so that's fine 👍
