### ISSUE TITLE
webnovel.com (Qidian) all fanfic chapters missing title

### ISSUE THREAD

**Issue by seba11998** [dteviot/WebToEpub#1342]
**Describe the bug**
It seems like something changed in webnovel's code because now no chapter has a title and its full of `<div>` and `<i>`.

**To Reproduce**
1. Go to: [Book example](https://www.webnovel.com/book/creating-manga-of-one-piece-in-pirates-world-become-my-ultimate-goal!_21965064805459105)
2. Download book

**Screenshots**
Before:

![Screenshot 2024-06-10 013524](https://github.com/dteviot/WebToEpub/assets/14128134/779807c9-1c1f-4606-916b-d1838bf02075)

After:

![Screenshot 2024-06-10 013623](https://github.com/dteviot/WebToEpub/assets/14128134/204619cf-f960-4092-8d17-5f7d97d80713)

**Comment by Kiradien** [comment]
Yeah, this bug has been going on for a few days along with a few intermittent bugs. They changed the page style when viewing and the chapter title is no longer within the div.page h1 it was originally in. 

I've got a fix sitting in a branch somewhere, I'll cherry-pick the part you need and add a pull request. Webnovel's been a bit weird since these changes went in, sometimes throwing random errors like HTTP 445, so I have a bunch of fixes that may or may not come up in the future.

**Comment by dteviot** [comment]
@seba11998 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://www.webnovel.com/book/king-of-gods_9017100806001205, chapter 1

For my notes: 31 minutes work

**Comment by seba11998** [comment]
Thank you, it works. The xhtml still has a bunch of extra `<i>` and `<div>` but the main problem is solved. Thank you so much

**Comment by dteviot** [comment]
@seba11998 @Kiradien 

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.
