### ISSUE TITLE
Save Window does not popup in Firefox (but it does in Chrome)

### ISSUE THREAD

**Issue by buthub** [dteviot/WebToEpub#137]
Hi, again.  Thanks for continuing work on this awesome addon, dteviot!

Just thought I'd mention a small bug I've come across on Firefox.  

.epub files created by WTE does not seem to create a Save As popup window to let me choose where to save/name the file.  Yes, the "Always ask you where to save files" option is on in FF.  It's been happening for quite a few weeks now.  And yes, epub files I download elsewhere will make the Save As window.  

I'm on Firefox 54.0.1 (cause I didn't want to lose certain features).  I don't know if it matters, but I also have [Tab Mix Plus](https://addons.mozilla.org/en-US/firefox/addon/tab-mix-plus/) and [Tab Groups](https://addons.mozilla.org/en-US/firefox/addon/tab-groups-panorama/) installed.

Thanks.  Just wondering if I'm the only one having this problem?

**Comment by dteviot** [comment]
@buthub 
I'm not sure what you mean by
> And yes, epub files I download elsewhere

OK, long story. Short form.
Chrome and Firefox don't have same logic for writing file to disk.  Was same, but changes to Firefox broke it, so it needed different logic.  That was build 38.  Side effect of this change was, if running in popup (instead of tab) mode, when the Save As dialog appeared, WTE looses focus and Firefox closes the extension.  (Which crashes the file save as the data ceases to exist before it's saved.)  So, I had to disable the SaveAs dialog for Firefox.
Probably what I should do is remove the Popup mode, and re-enable the SaveAs dialog.  Do you use Tab or Popup mode?

**Comment by dteviot** [comment]
Until very recently, I was not able to debug the extension on Chrome when running in Tab mode due to https://bugs.chromium.org/p/chromium/issues/detail?id=768169.
It took me 5 hours of searching the web on the weekend to find the workaround.
