### ISSUE TITLE
Cleaning up old/ broken URLs

### ISSUE THREAD

**Issue by gamebeaker** [dteviot/WebToEpub#1414]
There are a lot of parser for non existing/ broken sites.

I created a google dox with 3 columns.
https://docs.google.com/spreadsheets/d/1vdV8PfRGXRWeUTgE603LO_x7rS6QWyDRBe8T0eHyL4M/edit?gid=0#gid=0

URL in Parserfactory: is https://www. + base URL from parserFactory
URL redirects to: If the URL just redirects where to?
Test Book URL (not validated): A Book on the site (not validated could be boogus links patreon for example is just patreon.com)

If a site got blocked from ublock origin i consider it dead.
most sites with https error (no https) were redirections to ublocked sites.
If a site has a cloudflare error i wrote in Test Book URL zzzzzzzzzcloudflare error so that if it is sorted in this column they aren't considerd dead.

Stats:
430 URLs from parserFactory
130 from 430 are dead

The question now is if we should delete these old parser/urls or not.

**Comment by dteviot** [comment]
@gamebeaker 

1. I fixed the two helscans references.  (Now helhiem, and required layout adjustments.)  
2. I'm going to say, keep the old links/parsers.  Reasoning.
(a) If site is redirecting, old content may have references to the old hostname in links.  WebToEpub has problems if it has no parser for a hostname.
(b) It's an easy to find record that we DID support the site at some stage.  (Helps with some requests.)
(c) Sometimes I copy/paste code out of old parsers, because it has a solution to some layout problem.
(d) Do we really gain anything from removing them?

That said, feel free to add a comment by the ones that are dead/redirected with a date stamp.  We can clean them later if it's a problem.

**Comment by gamebeaker** [comment]
Closing this issue. You are right it is good reference.

**Comment by gamebeaker** [comment]
83 parser.js files "could" be deleted.
