### ISSUE TITLE
Issue on booktoki350

### ISSUE THREAD

**Issue by Bigdcikman** [dteviot/WebToEpub#1433]
**Describe the bug**
When trying to epub a series this popup, I already answer the captcha and login on the website

[WARNING: Site 'booktoki350.com' has sent an Access Denied (403) error. You may need to logon to site, or browse site normally until you get a Cloudflare "Are you a human" page or satisfy some other CAPTCHA before WebToEpub can continue.]

**To Reproduce**
1. Go to https://booktoki350.com/novel/15678262?page=2
2. Click on webtoepub
3. Click on pack epub
4. See the popup

**Expected behavior**
To pack the series with no errors.

**Screenshots**
![Uploading Screenshot_2024-08-21-21-08-18-722_com.kiwibrowser.browser-edit.jpg…]()

![Uploading Screenshot_2024-08-21-21-08-18-722_com.kiwibrowser.browser-edit.jpg…]()

**Smartphone (please complete the following information):**
 - Device: [xiaomi 5]
 - OS: [xiaomi hyper os]
 - Browser [kiwi browser]
 - Version [124.0]

**Additional context**

**Comment by Bigdcikman** [comment]
![Uploading Screenshot_2024-08-21-21-08-18-722_com.kiwibrowser.browser-edit.jpg…]()

**Comment by Kiradien** [comment]
Ah, yes, that is a throttling issue. Easy fix locally, but you'll have to wait until your unbanned.

1) In WebToEpub, click "Advanced Options"
2) Scroll down to the setting that says "Manual Throttle|Delay per chapter" and set to 3 seconds.
3) Open up any chapter that hasn't previously been opened, and make sure the chapter loads.
4) Generate Epub

I'll be pushing up a fix for this shortly; Setting 1.5 seconds as the default. The site looks like it technically allows for 1-second page loads, but I was banned at chapter 94 during testing due to manual browsing.

**Comment by dteviot** [comment]
@Bigdcikman 
Test versions for Firefox and Chrome have been uploaded to https://github.com/dteviot/WebToEpub/releases/tag/developer-build. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers.

**Comment by dteviot** [comment]
@Bigdcikman

Updated version (0.0.0.160) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in a few hours to 21 days.

**Comment by Bigdcikman** [comment]
Huzzah!
