### ISSUE TITLE
do not work with China website

### ISSUE THREAD

**Issue by yingxincui** [dteviot/WebToEpub#146]
such as https://sspai.com/column/110

**Comment by dteviot** [comment]
@yingxincui
Can you please be more specific?
I don't know Chinese, so it's hard for me to tell what the problem is.

**Comment by yingxincui** [comment]
I mean It's hard to get the real concent of the web. This app is not so clever in extract the article.

for example ,this web https://sspai.com/post/41044   
The concent comes from <div class="content wangEditor-txt" ref="content"> how can I extract it ?

**Comment by dteviot** [comment]
@yingxincui
You'll probably need to write a new parser to handle it.
However, now that you've figured out where the content is, it's not hard.
How to do it.
1. Load WebToEpub from source. https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#how-to-install-from-source
2.  Instructions on how to write a new parser.  http://www.codeproject.com/Articles/1060680/Web-to-EPUB-Extension-for-Chrome  (Note those instructions are a bit out of date.  You can save yourself some work by using the file js/parsers/Template.js  as a starting point for your parser.  Then just implement the functions 
* parserFactory.register()
* getChapterUrls(dom)
* findContent(dom)

Note, as you already know where the content is, findContent() is 
```javascript
findContent(dom) {
    return dom.querySelector("div.wangEditor-txt");
}
```

If you've read those instructions and need additional help, please let me know.

**Comment by dteviot** [comment]
@yingxincui
OK, on investigation, a new parser is not needed.
Assuming you just want the contents of say https://sspai.com/post/41044 converted into an epub, then steps are.
1. In web browser, go to https://sspai.com/post/41044
2. Click on the WebToEpub icon.  When "No parser found for this URL" message appears, click OK.
3. On the "Element with Chapter Content" row, set first drop down to "&lt;div&gt;", second drop down to "Class is", and last drop down to "content wangEditor-txt"  (ignore the quotes)
4. Click "Unselect All" button, then "Edit Chapter URLs"
5. On window add text 
```HTML
<a href="https://sspai.com/post/41044">ChapterOne</a>
```
6. Click "Apply Changes" button
7. Click "Pack Epub"

This will result in a EPUB.  (Although you'll get an error message that the XHTML is not valid for that page)
The reason is some &lt;o:p&gt; elements on page  They're valid HTML 5, but not valid XHTML.
You can fix the EPUB by using Calibre to manually remove the offending element.

**Comment by dteviot** [comment]
@yingxincui I have added a very simple parser for the sspai.com site to the experimental tab branch.  If you would install from source https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#how-to-install-from-source and let me know what issues it has, that would be appreciated.

**Comment by yingxincui** [comment]
I do as the instruction below


I just can not load it . and I do not know what is wrong.

**Comment by dteviot** [comment]
@yingxincui 
> I just can not load it . and I do not know what is wrong.

Do you mean you can't load WebToEpub from source, or you can't load pages from the sspai.com site?
Either way, I need more information to help you.
Please describe.
1. Each step you performed.
2. What happened when you did the step.
3. What you expected to happen (if different from what happened.)

**Comment by dteviot** [comment]
@yingxincui
I parser for this site has been added to the latest release (0.0.0.43) for Chrome.  Please let me know if there are any issues.
