### ISSUE TITLE
request for option to part xhtml in smaller parts.

### ISSUE THREAD

**Issue by annahana** [dteviot/WebToEpub#148]
request for option too part xhtml in smaller parts for Reader that can just handel up 260 KB of html like
Microsoft edge becomes slowly after that.

**Comment by dteviot** [comment]
@annahana
I'm not sure what you're asking for.  Is it
1. Don't make EPUBs that are bigger than 260KB?
2. Make sure each XHTML files in the EPUB is smaller than 260KB?
3. Something else?

**Comment by toshiya44** [comment]
Microsoft Edge is not a software meant to be read ebooks on. It's a web browser. 


@dteviot As far as I know, it's \#2. Calibre recommends keeping xhtml/html files below 240KB, although most software these days can handle a lot more than that.

**Comment by dteviot** [comment]
@annahana
Assuming the second case, please give me with some URLs that have this problem.

**Comment by AzSiAz** [comment]
@toshiya44 
Well now you can since the creator update: https://www.pcworld.com/article/3180753/windows/how-to-buy-and-read-ebooks-in-edge-as-part-of-the-windows-10-creators-update.html

**Comment by dteviot** [comment]
@annahana
Assuming you're asking for the second case, while it sounds simple, doing it correctly for every possible case looks to be difficult.  E.g. 
- Finding the an appropriate place to split is not always obvious.  For example, splitting a table is usually bad.
- Fixing up hyperlinks and anchors after splitting a page.

Solving a specific case may be simpler.  That's why I need to know what files you're having a problem with.  Unless you can provide me with URLs to examine, I'm not willing to invest any more time trying to solve the issue.

**Comment by annahana** [comment]
thanks for that mach replay EPUBs createt from novels translatet on http://unlimitednovelfailures.mangamatters.com/ will have all that problem because the full book will be made to a chapter and the 2 chapter will be the begining of the same book again because the plugin don't handle chapters correctly on that page. that is for my purpos no problem and i make all chapters unchecked in the plugin and just lose the function to jump to the chapter. but the xhtml will be one book with 351KB. here one url that will create exatlly that sice http://unlimitednovelfailures.mangamatters.com/risou-no-himo-seikatsu/risou-no-himo-seikatsu-volume-06/

and sorry for my bad english.

**Comment by dteviot** [comment]
@annahana
>sorry for my bad english.
Your English is fine.  It's the bug reporting that needs work.
FWIW, a bug report should go like this.
1. When I do &lt;list the steps you go through, with sufficient detail that someone can repeat them&gt;
2. I expect &lt;describe what you think should happen&gt;
3. But instead &lt;describe what actually happens that is different from what you expect&gt;

> http://unlimitednovelfailures.mangamatters.com/
Ah yes, my old enemy.  https://github.com/dteviot/WebToEpub/issues/71  I remember it well.
That said, it looks like the site has been cleaned up a lot since I last looked at it.  I _may_ be able to do something for it now.  I won't promise anything, and it may not get done until some time next year.

**Comment by dteviot** [comment]
@annahana
Version 0.0.0.43 has been uploaded to Chrome store.  Your version should automatically update within 24 hours.  Please let me know if it is satisfactory.  I tried the following two volumes and they seemed OK to me.
- http://unlimitednovelfailures.mangamatters.com/risou-no-himo-seikatsu/risou-no-himo-seikatsu-volume-01/
- http://unlimitednovelfailures.mangamatters.com/risou-no-himo-seikatsu/risou-no-himo-seikatsu-volume-02/

**Comment by dteviot** [comment]
Closing.  What I believe is a fix has been committed, and person opening issue has not responded.
