### ISSUE TITLE
Help regarding images

### ISSUE THREAD

**Issue by AishaPB** [dteviot/WebToEpub#1542]
Is there maybe a way to only get images that are directly displayed in the web? Some of the texts are missing because they are linked to an image and webtoepub is directly showing the images instead of the texts. I'm new to this and I've tried using the advanced options but I can't figure out what to do. I don't want to totally skip all the images please help.

**Comment by gamebeaker** [comment]
@AishaPB Can you please share a story url (with chapter) where the problem is?

**Comment by AishaPB** [comment]
Hi ! Thank you for responding. This is the url.
https://taidatranslations.wordpress.com/kaleidoscope-of-death/kod-chapter-56/
![Screenshot_2024_1010_202200](https://github.com/user-attachments/assets/5290749e-436e-42ee-83a4-915d37827126)
![Screenshot_20241010_202046](https://github.com/user-attachments/assets/1ab76b80-09c0-4823-94f2-e9ee7bad46bd)

**Comment by dteviot** [comment]
@AishaPB 

The problem is when WebToEpub sees a link that is to an image, WebToEpub will replace the link with the image.  (Because that's usually what people want.)

As a workaround, you could hack WebToEpub to disable this.
Basic steps.
1. Download the Chrome or Firefox development version of WebToEpub from 
https://github.com/dteviot/WebToEpub/releases/tag/developer-build
2. Unzip the file
3. In file ImageCollector.js, remove line 456.  i.e.
https://github.com/dteviot/WebToEpub/blob/8d00b279380f3c12066167d44cf4c12af247ea99/plugin/js/ImageCollector.js#L453-L459

Remove the line 
```javascript
            ImageCollector.replaceHyperlinkWithImg(hyperlink);
```
4. Run modified version of WebToEpub.  More info at how to do that is at https://github.com/dteviot/WebToEpub

**Comment by AishaPB** [comment]
Thank you!

**Comment by dteviot** [comment]
@AishaPB 
If this solves your problem, please let me know so I can close the issue.

**Comment by AishaPB** [comment]
Hi! 
This fixed my problem. Thank you so much!

I'm sorry for the long wait. I've been so busy. I didn't know you were waiting for my response.
