### ISSUE TITLE
Novelbin.com Page Clutter

### ISSUE THREAD

**Issue by Arsur3215Loki** [dteviot/WebToEpub#1565]
The pages after conversion on the site had so many clutter like the lists from the heading, the code for the ads, and other that I don't know what it is called. I don't know if it works fine with the other stories as I don't go to this particular site, but what I tried converting is this, https://novelbin.com/b/cannon-fire-arc.

**Comment by ImLJS** [comment]
@Arsur3215Loki Can you mention in what chapters the clutter will come.

**Comment by dteviot** [comment]
@Arsur3215Loki 

This sounds like https://github.com/dteviot/WebToEpub/issues/1345, but it was fixed in version 0.0.0.167, from August.
Are you running the latest version, from Chrome or Firefox stores?

I tried the link given, downloaded the epub and examined a number of chapters.
1 to 7, 207, 197, 125.

They all seem fine to me.  I can't see the problem you describe.

Possible things to try.  
1. If you put the epub somewhere I can download it from and email me a link, I can take a look at it.  Don't post the epub here, that would give copyright problems.  Although you could post the content.opf file from the epub here, that might be useful.
2. Issue 1345 above gives a script for EpubEditor to fix the epub.  And Epub Editor is now available on the web at https://dteviot.github.io/EpubEditor/, so you could try that to fix your downloaded epub.


Notes
Time taken: 26 minutes

**Comment by Arsur3215Loki** [comment]
@ImLJS This is what is shown on my phone and my PC. The one on the phone doesn't show on the PC, but its size is too big compared to the other chapters.

![image_2024-11-07_150746287](https://github.com/user-attachments/assets/477753aa-e5c0-4835-abe2-7662151b7e46)
![462550188_1632252874395180_9160716923718142502_n](https://github.com/user-attachments/assets/6870280c-b77e-4868-8069-4374c6a329f4)

**Comment by Arsur3215Loki** [comment]
I've updated it to version 0.0.0.163 from 0.0.0.160, and the clutters are gone. I Haven't checked if the same for the phone but I'm hopeful it would as well. Thanks.
