### ISSUE TITLE
Issue with Vivaldi

### ISSUE THREAD

**Issue by Maradar** [dteviot/WebToEpub#163]
Hello,

Extension started having problem with naming and packing files to proper epub format.
Instead it generates only zip files like this one 291533c8-9155-4954-8463-a93fbe44fe75.zip

Vivaldi | 1.15.1147.36 (Stable channel) (64-bit)
-- | --
Revision | 166efd59c7aba158f456fc82eabf5d0dffdc41f5-
OS | Windows
JavaScript | V8 6.5.254.41
Flash | (Disabled)
User Agent | Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/65.0.3325.183 Safari/537.36 Vivaldi/1.96.1147.36
Compiler | clang

**Comment by dteviot** [comment]
@Maradar 
The only browsers I support are Chrome and Firefox.
While Vivaldi is related to Chrome it's not the same thing.
Given the effort it takes to support just those, I'm not prepared to officially support any others.

That said, I'm prepared to make some suggestions that may help solve the problem.
1. Can you give a URL that shows the problem?
2. Does the URL work if you use the extension in Chrome or Firefox?  If it works in Chrome, then probably the issue is with Vivaldi, not the Extension itself and you should report the problem to the Vivaldi team.
3. The code to do download is the most difficult.  Basically, it needs to be different code for Firefox, Chrome and Firefox for Android.  You might try version 0.0.0.37 of the Extension that'got an older version of the download code that might work.

**Comment by Maradar** [comment]
@dteviot 
Thanks there seems to be problem only in Vivaldi.
I tried this with chrome beta at it works there.

I am guessing that the problem is not with download but with packer. 
Book is downloaded and after changing extension from zip to epub it opens as book with everything in it.

**Comment by dteviot** [comment]
@Maradar 
Latest version of extension (0.0.0.52) has changed code for saving the epub file to disk.
Can you give it a try and let me know if it is now working?

**Comment by Maradar** [comment]
@dteviot 
Sorry for the delay. As to the issue no it still does not work in Vivaldi but works fine in Chrome.
I am using latest version of the extension from the Experimental branch.

**Comment by dteviot** [comment]
@Maradar
Please see https://github.com/dteviot/WebToEpub/issues/191
In short, are you running any other extensions that effect downloads?

**Comment by Maradar** [comment]
@dteviot 
I tried it in the clean profile without any other other extensions installed and the same problem.
So the short answer is no it is not related to any other addons in Vivaldi

**Comment by Christmas-Cavalier** [comment]
Hi @dteviot, just thought I'd drop by and say that the files are now named correctly when using WebToEpub in Vivaldi, at least for me. Though I'm not sure whether it was an update to WebToEpub or Vivaldi that fixed it.

**Comment by dteviot** [comment]
@Christmas-Cavalier  Thank you.
