### ISSUE TITLE
Suggestion to change the Title and File name

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#172]
Option to automatically add info to the title and file name depending on the website and status of the book/story on RRL.
Example for [The Void Wolf](https://royalroadl.com/fiction/11588/the-void-wolf) :
Title changed to (RRL) The Void Wolf (Ongoing)
File name changed to (RRL)The_Void_Wolf(Ongoing).epub
Reason: This helps to know the website in case you want to see it. The status helps in case you want to if you want to update the epub. Like if it says "ongoing" you know it will be obsolete so you should update it after a while. If it says "hiatus" you know you might want to check the website after a long time to check it. Finally, if it says "completed" you know you have no need to check anything.

**Comment by dteviot** [comment]
@JeremyStarten

It looks to me like you’re trying to achieve two things.
-	Keep track of where an epub came from.
-	Note if there might be more of story if come back later.

The first item is already being done.  The URL of the web page that was used to get the list of chapters to fetch is recorded in the epub metadata under the identifier element.  E.g
```xml
<dc:identifier id="BookId" opf:scheme="URI">
https://www.shinsori.com/nigotta-hitomi-no-lilianne/
</dc:identifier>
```

I do realize that for many people, they’re not going to be able to view this information, but if I add an information page (https://github.com/dteviot/WebToEpub/issues/173) then this information is something that would go in the information page.
I’m not comfortable adding a prefix to the filename to indicate the source.  Mostly because there are so many sources, for most people, the prefix is not going to be meaningful.

Question: Is there a reason why you need this to be visible in the file name?

The second item is more difficult.
Firstly, detecting if a story is complete requires per site.  i.e. Each parser will need to implement the logic to do this.
Also, I’m thinking what you really want is a list of “downloaded” epubs.  Something like:
- Title
- Is complete
- Date Downloaded
- Last Chapter in download  (title + url)
- URL with chapter list.

Ideally, WebToEpub would keep and update this log.
Unfortunately, doing that has has privacy issues.  For example, 
- it’s not permitted when running in incognito mode.
- privacy policy needs to be changed,
- assorted legal issues I don’t want to have to deal with.

Best I can suggest is manually keep such a text file. 
 I might be able to add a button that would write the details of finished export to the clipboard, so you could paste them into a text file.  Would that be any use?

**Comment by JeremyStarten** [comment]
To answer the first question, it is that it is more simple to just look at the file name than to have to open it, check, then close it. Especially if I'm thinking of renewing a bunch of books with updated content. Also even if there are many sources I'd think someone would be comfortable with using the same on over again though I guess that is counter to what I am arguing since then they'd know the source.

For the second part, I didn't know that it would be that complacated, sorry. As for adding a button that would copy stuff to a clipboard, I don't think it would be used by me but maybe someone more organized. At this point however I have just opted to manually add (RRL) and ("STATUS") to the story title and file name. But if something changes and allows for such things to be Implemented then that would be great.
