### ISSUE TITLE
URLs to pages not included in the EPUB must be absolute not relative

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#175]
Sometimes in a story on Royal Road, an author puts a relative link that goes to a chapter of a different story or a new story. The link works when viewing Royal Road in a web browser, but does not work in the epub created by WebToEpub. 

An example of this happening in a story is for [Phoenix Rising](https://www.royalroadl.com/fiction/2282/phoenix-rising?review=22024):
[ARC 01: Chapter 2 - Seeking Help [v2]](https://www.royalroadl.com/fiction/2282/phoenix-rising/chapter/19726/arc-01-chapter-2-seeking-help-v2) - Turning this chapter into an epub with webtoepub will result in two broken links in the author's note.

A NOTE FROM VIJAYKAKANI
There is an improved version, **v2**, of this chapter in the **Phoenix Rising v2** story page.
(The bold parts are where the links are in the note)

The links on the page are relative links  (which will only work correctly when viewed on the original web page, using it's base URI.)
```HTTP
<a href="/fiction/Chapter/101992" target="_blank">v2</a>
<a href="/fiction/8978" target="_blank">Phoenix Rising v2</a>
```

Because converting the web page into an epub creates a new web page with a different Base URI, the links need to be converted into absolute URLs so that they are not broken.
```HTTP
<a href="https://www.royalroadl.com/fiction/Chapter/101992" target="_blank">v2</a>
<a href="https://www.royalroadl.com/fiction/8978" target="_blank">Phoenix Rising v2</a>
```

**Comment by dteviot** [comment]
@JeremyStarten
> In Royal Road, it knows to add the https://royalroadl.com before it, however, webtoepub doesn't. 

That’s not the problem.
What’s happening is that the hyperlink is to a web page that is NOT in the chapters of the story.
Neither of them appear in the list of chapters on page https://www.royalroadl.com/fiction/2282/phoenix-rising
In fact:
- https://www.royalroadl.com/fiction/8978 is the table of contents for the rewritten version of the stroy, and
-  https://www.royalroadl.com/fiction/Chapter/101992 is one of the rewritten chapters.


What to do about links that are to outside the story is not clear.  There are three obvious alternatives.
1. Follow the link and include the referenced page.  If the page has additional links, this can wind up fetching a lot of pages.
2. Delete the entire hyperlink.  Doing that results in strings with missing text.  It’s confusing.
3. Leave the hyperlink alone.  This does result in links appearing in the text that can’t be followed. (Although some epub viewers do have internet access and can follow the links.)

I have chosen option 3.
Note, There is still work to do in WebToEpub, Currently, it only fixes up hyperlinks that refer to the same page, it does not fix up hyperlinks between chapters.
Example: Assume you have two chapters 1, and 2.  On chapter 1, there are two hyperlinks, one to a footnote at the end of chapter 1, the other a link to chapter 2.  The link to the footnote will be fixed up and work correctly in the epub.  The link to chapter 2 will not be fixed, and will point to the URL that chapter 2 came from, rather than the URL of chapter 2 in the epub.
