### ISSUE TITLE
Saving as .zip instead of .epub

### ISSUE THREAD

**Issue by Kichiro77** [dteviot/WebToEpub#191]
Hi, 
 From some time my novels are getting saved as a zip file instead of epub, is there any way fix to it? The file name also gets changed to something like this 69dfd590-d947-420a-b7ef-943f12c80a09.zip
     I can retype the name with .epub and it would fix it but I was wondering if there is an option to always save it as .epub like before it used to do.

Thanks for the wonderful extension, it's really helpful to me!

Update:  The problem was a conflict between WebToEpub and another extension (https://chrome.google.com/webstore/detail/downloads-overwrite-alrea/lddjgfpjnifpeondafidennlcfagekbp) 
After disabling downloads-overwrite, WebToEpub works correctly.  
Note, same problem can occur with other extensions that change download behavior.

**Comment by dteviot** [comment]
@Kichiro77 
By any chance, are you using Vivaldi as your browser?  This is a known issue with it.  See: https://github.com/dteviot/WebToEpub/issues/163

**Comment by dteviot** [comment]
@Kichiro77
Please look at https://github.com/dteviot/WebToEpub/issues/153

**Comment by Kichiro77** [comment]
I am not using incognito mode. Just tested ticking do not track option on/off still not working. I am using chrome latest build Version 68.0.3440.106 (Official Build) (64-bit). I have also tried disabling few other extensions that might interfere still no result.

**Comment by dteviot** [comment]
@Kichiro77
Thank you very much for taking the time to respond to me.
As you've probably guessed, I'm still not able to reproduce this.
So, I'm afraid I'm going to have to ask you some more questions.
Normally the sequence for using WebToEpub is:
1. Click the "Pack EPUB" button.
2. Pages are fetched.
3. A Save As dialog appears
4. You can change the filename on the dialog if you wish.
5. Click "Save" button and file is written to disk.

When the "Save As" dialog appears, does the file have the correct (.epub) name or the wrong name (.zip)?  Or does the "Save As" dialog not show?
If the name is mangled on the Save As and you correct the name does the file written to the disk have the correct file nane?
Bascially, I'm trying to figure out: is the name being mangled BEFORE the Save As dialog, or AFTER the Save As dialog.

Next question: can you confirm that the mangled name ends with a ".zip"?  (This bit is really strange, because I never supply that.)  And probably an important clue about what's going wrong.

Also, can you confirm the mangled filename is always a sequence of digits and letters between a and f, made up of 8 characters, followed by 3 sets of 4 characters and finally 12 characters?  (Note, this is a GUID)

Can you check which version of WebToEpub you're running? 
On the search bar type in 
> chrome://extensions/

that should list all extensions, with their versions.

Next question: can you give me all other extensions you have loaded and their versions?

Next question:  is the filename always mangled?

Last question: I may need you to patch the WebToEpub you're running to collect more data.  Are you able (and willing) to build and run from source?  See: https://github.com/dteviot/WebToEpub

**Comment by Kichiro77** [comment]
When the save dialogue appears, it is with wrong name .zip always. If I correct the name on save dialogue, it will become correct on my disk too.

Yes, the mangled file always ends up with .zip but I had right clicked on it and made it so that it always open with ebook viewer so only the name ends up being wrong.

I just tested filename with different novels 5-10 times with different websites. It looks like letters are indeed always between a-f but the characters are like 8-4-4-4-12.

My WebToEpub version is 0.0.0.55. I had even reinstalled it once a day ago to make sure it's up to to the latest version.

Update: It looks like the problem was with my extension, I tried enabling/disabling all of them 1 by 1 when I was typing the reply here and found out the app by name downloads overwrite already existing files 0.0.3 was the culprit. Actually, I was using this app to replace old epubs with the new one so I won't need to manually delete the old ones and it seems to be working for a long time maybe after some update from them it got bugged like this.


Here is the link for that extension https://chrome.google.com/webstore/detail/downloads-overwrite-alrea/lddjgfpjnifpeondafidennlcfagekbp

Thanks for the help!

**Comment by dteviot** [comment]
@Kichiro77 
Thank you very much for finding the cause of the problem.  That will save me some time.

>  It also looks like new files are replacing old ones now even without that app instead of saving as (2) etc.
Correct. The latest version of WebToEpub overwrites existing files.  Although I'm not sure if that counts as a bug or a feature.
