### ISSUE TITLE
[Issue] Comrademao

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#220]
**[not working]**
https://comrademao.com/novel/invincible/

**Comment by dteviot** [comment]
@3dycosmo
Can you be more specific?
The URL is helpful, as I can run it and try to reproduce the problem.
But it would be nice to know what the problem is, so I know what I'm trying to reproduce.

I'll assume your problem is you're getting this message.
> Warning, unable to convert chapter 'Invincible Chapter 1' from 'https://comrademao.com/?p=513394' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. 
Conversion error message was: (This page contains the following errors:error on line 1 at column 379: Specification mandates value for attribute read
Below is a rendering of the page up to the first error.)

If so, the problem is the HTML is invalid.  Eg. it's got suff like this
```HTML
<div read<a="" data-toggle="popover" data-trigger="click" title="能力" data-placement="top">ability="198"&gt;
```

The epub spec requires XHTML, and WebToEpub is unable to figure out how to convert this sort of malformed HTML to XHTML.
You'll need to fix it manually using Calibre (probably not feasible.)
Or tell the site they've got a problem with their readability and ask them very polietly to fix it.

**Comment by 3dycosmo** [comment]
https://comrademao.com/novel/invincible/

I tried to make an all chaps epub, but failed all for all chaps except information page in front

**Comment by 3dycosmo** [comment]
So, for bad html which's xhtml now, to get the div's content, are there no available tag soups in JS?
And thanks a lot (maybe use python)

**Comment by dteviot** [comment]
@3dycosmo
It looks like Calibre can be used to fix the issues.  
At least, it worked for chapters 1 and 3429, which were the only ones I tried.
Steps.
1. Load the epub into Calibre
2. Select the epub in the list of titles, then click the "Edit Book" option from the menu bar at top of screen.
3. Select the "Check book" option from the menu bar at top of screen.  (It looks like a red insect)
4. You should see a number of "Parsing failed: Specification mandates value for attribute read" errors. in the Top Left window.
5. Click on the "Try to correct all fixable errors automatically" in the top right window.
6. The "Parsing failed" errors will go. But new errors "Bare text in body tag" will appear.  
7. Click the "Try to correct all fixable errors automatically" again
8. Errors will now show "CSS: Property: Unknown Property Name"  You can ignore this.
9. Click on File -> Save a Copy.

The resulting epub should be viewable, although you will see some junk at the start of each chapter.
Please let me know how it goes for the other chapters.

**Comment by 3dycosmo** [comment]
Thanks, it's all done

**Comment by dteviot** [comment]
I'm not going to try fixing this.
1. It seems to be the only story on the site with this problem.
2. Fixing in WebToEpub is going to be a lot of work.
3. Can be fixed using Calibre.
