### ISSUE TITLE
Cannot fetch chapters on GravityTales (duplicate #190)

### ISSUE THREAD

**Issue by asifm91** [dteviot/WebToEpub#221]
I am also having a similar problem as #190, the extension gets a 403 error while fetching chapters. I am opening a new issue since the old one is closed.

I am on Firefox and I can view/read chapters normally in the browser.

Sample error message:

```
Fetch of URL 'http://gravitytales.com/novel/versatile-mage/vm-chapter-1' failed with network error 403. onResponseError@moz-extension://9c6d0b5b-141b-4f07-8728-a7f0ae00ca63/js/HttpClient.js:28:25
checkResponseAndGetData@moz-extension://9c6d0b5b-141b-4f07-8728-a7f0ae00ca63/js/HttpClient.js:105:20
wrapFetchImpl/<@moz-extension://9c6d0b5b-141b-4f07-8728-a7f0ae00ca63/js/HttpClient.js:99:20
```

**Comment by dteviot** [comment]
@asifm91

I’ve confirmed that I’m able to download chapters with the latest code base (which is version 0.0.0.61) Looking at the code, for the Gravity Tales parser, there’s been no changes since version 0.0.0.56.  The Firefox release is version 0.0.0.58, so the Gravity Tales code is the same.
I therefore assume issue is the Gravity Tales site has decided to not supply the chapters to your computer for some reason. 

My thoughts/questions on what you might do about this.
1. You could turn on Firefox’s network traffic monitor https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor and see if there’s anything in the 403 response https://developer.mozilla.org/en-US/docs/Tools/Network_Monitor/request_details from Gravity Tales when WebToEpub tries to collect the page(s).  
2. Can you try to download the story from a different PC, on a different IP address?
3. Can you get a friend to install WebToEpub and try to download the chapters?
4. Has the problem only just appeared, or have you never been able to download from Gravity Tales?
5. You could try contacting the Gravity Tales site and ask what’s happening.

**Comment by dteviot** [comment]
@asifm91
I owe you an apology.  
It works for Chrome.  It does not work for Firefox.
I am investigating further.

**Comment by dteviot** [comment]
Working hypothesis.  Problem is Firefox is setting CORS information.
Note the failed request has origin in header.

**The text in the 403 response is**
> Not allowed in CORS policy. 

**Failed request Header (Firefox)**
Headers
Host: gravitytales.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: */*
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
origin: moz-extension://580713a4-7df3-4412-8732-17dfef5a47bd
DNT: 1
Connection: keep-alive
Cookie: __cfduid=d4338902e630d025213fd6f94a6d080f31533941458; XSRF-TOKEN=eyJpdiI6IlJxVGZTenphV3FrUVd6SzRZXC9BZmZ3PT0iLCJ2YWx1ZSI6IlZudlZRc1VIdW5FNW5uZWwzV0JOUHBDWmxvSU8zcmxpdlZiaVIxczVUSEZqQzV3ZThwWndOc1Z0dVhzcmF0cHlKYXVFZmNYSEczWmZoNEZWSDAyK1F3PT0iLCJtYWMiOiI2ZjlmZGM5MGQwMzA4MjU3NGQ1Y2IyY2UwMDhmOTI1YmRlMDlkMTI2ZWJhOGNjYjQ1ZmU5NjVhOTYwYmJmMGNmIn0%3D; gravitytales_session=eyJpdiI6ImRocFhSVFVjdGlYaHY0NkY3U21OOHc9PSIsInZhbHVlIjoiMTQySFVVWDNObkpmeWhXSGJ6UDY1bVdoRTlGR05scmxzNjNTZVwvRDcrWXVLZEtZSDVIWW5DMWlKaVlKdnUyV0F0R0pPN2NnT2FTUVZrRXhHejBLSXV3PT0iLCJtYWMiOiI4YjBmMzEwYmQ4ZjU1ZmI4MTFhYmZkNGNlNjY1YjRkOGMxNDg4YWJlZTMzMWMzMjE5Y2U5NzE2ZGE3MDIxNjcwIn0%3D; DO-LB=node-95710689|W+VAH|W+VAH

**Successful request Header (Firefox)**
Host: gravitytales.com
User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:63.0) Gecko/20100101 Firefox/63.0
Accept: text/html,application/xhtml+xml,application/xml;q=0.9,*/*;q=0.8
Accept-Language: en-US,en;q=0.5
Accept-Encoding: gzip, deflate
DNT: 1
Connection: keep-alive
Cookie: __cfduid=d4338902e630d025213fd6f94a6d080f31533941458; XSRF-TOKEN=eyJpdiI6IkE3Nmw4UXBzZnkwRFhxaFdpME85cWc9PSIsInZhbHVlIjoiemxsZ2pkbitDdFwvRFVvK1JBR2dzVmtlZk1ucmZ6T3BlRmhFUERad0ZiOGEwdE9cL3htWkYxVG1raWdrSE5BalpqZURXWkNLOGdGcWdjU0I1ZDdGVXNmdz09IiwibWFjIjoiZjI4NmUyYmM3M2ZjZGFiZDAwOGY4NDZiMWM0ZGE3MGVlZGFiZWJlMTdhNTIxZGJmNzA4MWRkYjk4MjliYjhjMCJ9; gravitytales_session=eyJpdiI6IlwvWUtCanl1XC9leWtwWG9DVklBM2Zmdz09IiwidmFsdWUiOiJOUWdYeTMwRVlIUzJrODNyakV4TVRUWldnUTBSUjg5Z2gwS0V1NUQwZlZwdE0wdUZhZDdvNE84SHh1dlRqczlKeXowV3AxdTlHRDNxS3ZFS25JZWdGQT09IiwibWFjIjoiMGZlZmQ1ODgzZWQ0ZDgwNTQyYjkwZDQyYTk2OWVhMzU4Y2NiMmNiMzRjNzk5ZmUwMzJiNmRiZTE0MDJlNjE3YSJ9; DO-LB=node-95710689|W+VCl|W+VBh
Upgrade-Insecure-Requests: 1
Cache-Control: max-age=0

**Comment by dteviot** [comment]
@asifm91 
I think I've got this fixed.  If you'd like to install from source from the Experimental Tab Mode branch and let me know how it goes, that would be appreciated.

**Comment by asifm91** [comment]
I've tested a couple of books from gravity tales and the fix works.
