### ISSUE TITLE
Options to remove translator's note on webnovel.com

### ISSUE THREAD

**Issue by diablo348** [dteviot/WebToEpub#230]
The translator's note on webnovel.com novels usualy just spam.

**Comment by dteviot** [comment]
@diablo348 please provide URLs to pages showing the issues.

**Comment by diablo348** [comment]
I was asking if you can add an option to remove translators note just like you add "remove author's note" option on royalroad.

And some novels on wuxiaworld are divided by volumes like:
https://www.wuxiaworld.com/novel/terror-infinity
Can you somehow add those volumes name into toc in the epub, but make it an option since not all novels there have volumes

**Comment by dteviot** [comment]
@diablo348 
>I was asking if you can add an option to remove translators note just like you add "remove author's note" option on royalroad.

I realize that.  I was asking you for the URLs of some pages on webnovel.com that have a translator's note you want removed. So that I can see exactly what you're referring to.  (I don't want to go hunting around and find something that is a translator's note that's NOT what you're after.)

Incidentally, This issue is two requests.  Please create a new issue for the Wuxia world volume page issue.  (It makes things easier for my tracking purposes)  I'd do it myself, but then you wouldn't be automatically updated.

**Comment by diablo348** [comment]
My bad,

https://m.webnovel.com/book/8472024506000205/24304044801587153
The note at the end of the chapter is just the translator spamming patreon link in all chapters.

https://m.webnovel.com/book/11365254206340405/30625279705664746?from=catalog&
This one is original novel and the author just promoted his other novel on author's note section at the end of chapter

**Comment by dteviot** [comment]
@diablo348 
On reflection, providing the “remove author’s note” for Royalroad was a mistake.  Because it’s really a special case of a more general problem.  Specifically: people would like an easy way to remove “garbage items” that appear in multiple places in an epub.

I’ve been working on a tool to do this, which you can find at https://github.com/dteviot/EpubEditor

Follow the instructions to build it and use “div.m-thou.mb48” (without the quotes) as the CSS selector to remove the translator’s notes from epubs from webnovel.com
Please let me know how it goes.

**Comment by dteviot** [comment]
@diablo348
I guess I wasn't clear in my last post.
The purpose of the tool is to remove **any** unwanted element(s) from an epub.
You use a CSS selector to specify the element(s) to remove.
So, figure out the CSS selector for the buttons you want removed and use that. 
(You didn't tell me the URLs of pages with the issue, so I can't provide you with the CSS (as I did for the translator notes.)
But it's probably better if you learn how to do this for yourself.)
Some links that may be useful:
* CCS Selectors: https://developer.mozilla.org/en-US/docs/Web/CSS/CSS_Selectors
* How to find CCS selector for an element using chrome.  (Look at the last answer on the page) https://stackoverflow.com/questions/4500572/how-can-i-get-the-css-selector-in-chrome

Note, you'll need to unzip the epub and look at those pages in Chrome, not the original web pages to get the correct selector to use.  WebToEpub does some re-writing of the HTML, so CCS from original page may not work.
