### ISSUE TITLE
Reddit/r/QidianUnderground

### ISSUE THREAD

**Issue by darkharrycracker** [dteviot/WebToEpub#231]
https://www.reddit.com/r/QidianUnderground/wiki/toc_reup for the table of contents in QidianUnderground please don't mind r/Noveltranslation cause it is to find the webnovels there on other websites. If possible do it from search like ( https://www.reddit.com/r/QidianUnderground/search?q=strongest%20sword%20god&restrict_sr=1&sort=new ) and get it from there but i think the toc_reup is enough because it is up to date. Thank You

**Comment by dteviot** [comment]
@darkharrycracker 
QidianUnderground has a bot that will provide epubs.
Go to discord,and open the #epubs channel. (or try https://discordapp.com/channels/426914189097828352/431377243802173450) and post your request.  (Or just check the history for the epub you want.)
Request seems to be of the form
```
!epub <title> <option>
```

where 
* &lt;title&gt; is the name of the work
* &lt;option&gt; can be number of chapter to start book at, or "latest" to get any chapters since your last request.

Note, I did look into extending WebToEpub, but it's not easy.
Most chapters are held on a privatebin based server, (e.g. https://paste.imirhil.fr) which holds the content in encrypted format.  
And returns the content encrypted.  
So, I'd need to do a **lot** of work to make WebToEpub able to fetch the content and decrypt it.  Refer: https://github.com/PrivateBin/PrivateBin
Given that there's already an ability to make an epub and extending WebToEpub for QidianUnderground is likely to be many days of effort,  I'm going to say "Sorry, but no, I'm not going to do QidianUnderground."

Note, if you know of any other subredits, please let me know and I'll take a look at them.
