### ISSUE TITLE
Add volume page for wuxiaworld

### ISSUE THREAD

**Issue by diablo348** [dteviot/WebToEpub#233]
Add volume page for wuxiaworld so the chapters in toc would be divided by volumes like in Gravity Tales in old version, because some novels' chapter name there actually divided per volume, 
E.g. https://www.wuxiaworld.com/novel/terror-infinity

But make it an option if possible, since not all novels there have volumes.

**Comment by dteviot** [comment]
@diablo348
Updated WebToEpub has been committed to Chrome store.
I did not see any reason to provide an option.  If there are volumes, then the chapters in the Table of Contents are grouped by volume.  When there is only a single volume (or none) there is no grouping.

Note.  I used to provide chapter grouping.  I stopped doing it because:
1. The parser code is more complicated (and takes longer to write, test, debug, etc.)
2. The Parser is more likely to stop working when the site has its layout changed.

I reserve the right to strip out the grouping code the next time the layout is changed and the parser broken.  See: https://blogs.msdn.microsoft.com/oldnewthing/20181210-00/?p=100445
