### ISSUE TITLE
webnovel(dot)com all titles and file names

### ISSUE THREAD

**Issue by darkharrycracker** [dteviot/WebToEpub#250]
when using webtoepub at webnovel(dot)com the title and filename is (Earn Reward)

**Comment by dteviot** [comment]
@darkharrycracker 
I think I have not understood your description of the the problem.
What I did:
1. Open Chrome
2. Browse to https://www.webnovel.com/book/11046203006242805/Prodigiously-Amazing-Weaponsmith
3. Click on the WebToEpub button.
4. On new tab, Title is "Prodigiously Amazing Weaponsmith" and Filename is "Prodigious...eaponsmith"

Please provide more details.

**Comment by JeremyStarten** [comment]
Can confirm this a problem when using webtoepub. Following your steps provided the name and filename  changed to Earn Rewards and Earn_Rewards.
![untitled](https://user-images.githubusercontent.com/39293934/54005942-33737e80-4110-11e9-8de6-1da84135d29b.png)

However after doing a little investigating I found out that this only happens when you you are signed in to an account. Signing out changes the name and filename back to what they should be.
![untitled2](https://user-images.githubusercontent.com/39293934/54005983-61f15980-4110-11e9-8b99-a131f95a87c3.png)

**Comment by dteviot** [comment]
@JeremyStarten
Thank you. 

@darkharrycracker
Issue has been fixed and version in Chrome web store updated.
