### ISSUE TITLE
Allow the combining of multiple websites into one epub

### ISSUE THREAD

**Issue by JeremyStarten** [dteviot/WebToEpub#251]
Sometimes a translator stops working on a novel and someone else picks it up. Would it be possible to add an option to combine or add another webpage full of links? Right now I just open multiple webtoepubs, open the edit links and copy them over but can it be made to be more automatic?

**Comment by dteviot** [comment]
@JeremyStarten
Can you describe what the UI for doing this would be like?

**Comment by JeremyStarten** [comment]
Perhaps add a plus near starting url to add a link below it that allows for a new webpage to "load and analyze". The chapters would start from the first url then down one. You could then just manually uncheck the links that break the chapters (if there are any) when moving from one site to another.

**Comment by JeremyStarten** [comment]
Something like this I guess
![untitled-1](https://user-images.githubusercontent.com/39293934/54007195-797f1100-4115-11e9-98a8-ea1d8e69b9bb.jpg)

**Comment by dteviot** [comment]
@JeremyStarten
Unfortunately, I think there's a hard to solve issue with your proposed solution. 
What to do when there's no parser for the new page to "load and analyze"?

I've added a "Copy Links to Clipboard" button (next to the exising "Edit Chapter URLs" button).
This should make it easier to get a list of Chapter URLs to add.
I think this results in a work flow that's almost as easy as your proposal.

**Comment by skaviouz** [comment]
It is not uncommon for me to use the _**Edit Chapter URLs**_ button. Especially when I need to add chapters from another source, or remove c33p1 c33p2 when there is a c33 version available, when there is a full-text link for a volume, or etc.
However, if the parser is the issue, what about instead of saving to a new file you append to an already existing epub file? use a check box that says whether you add another cover page too.
Don't get me wrong, different from the idea of the issue, but same end goal -> 1 epub. And imho append seems easier than multiple parsers picking and choosing, however I say if someone try to append to a epub 3.0 just throw an error like a boss, we don't serve your kind around here.

**Comment by dteviot** [comment]
@skaviouz
Thanks for pointing out that the ability to add chapters to an epub would also solve this problem.
Unfortunately, adding chapters to an epub is tricky. Which is why https://github.com/dteviot/WebToEpub/issues/145 has been open for 2.5 years now. And, yes, I know it's been solved by https://github.com/JimmXinu/EpubMerge.

**Comment by drjoe123** [comment]
I'll second this request... I've got quite a few "WN XYZ Ch 1-3.epub", "WN XYZ Ch 4-103.epub", "WN XYZ Ch 104-332.epub"

Thanks, 

Joe

**Comment by dteviot** [comment]
@drjoe123
I've got a tool that can combine epubs.
Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing and download MergeWebToEpub zip
Instructions for use can be found at https://github.com/dteviot/MergeWebToEpub
Note, this is still under development, so UI and features are unfinished.

**Comment by drjoe123** [comment]
Thanks, I'll try it.

Joe
________________________________

**Comment by gamebeaker** [comment]
With the [Library](https://github.com/dteviot/WebToEpub/wiki/Library) you can first download Chapter 1-100 from one website than change the url and download 101-200 from a different website. Look [Story URL](https://github.com/dteviot/WebToEpub/wiki/Library#story-url).
