### ISSUE TITLE
Request for an app

### ISSUE THREAD

**Issue by story011** [dteviot/WebToEpub#274]
Hello 

I came around this extension on google chrome desktop and it works amazing 

But i would like to request if you could make an app with all its features for ios devices/ android?

**Comment by dteviot** [comment]
@story011
You should be able to load the Firefox build of the extension (from https://addons.mozilla.org/en-US/firefox/addon/webtoepub-for-baka-tsuki/) onto Firefox for Android.  At least, I was able to in the past.  It has been a while since I last did it.

As regards iOS, sorry but no, I just don't have the time.

**Comment by dteviot** [comment]
Closing.  No response from @story011
