### ISSUE TITLE
babelchain

### ISSUE THREAD

**Issue by Senastra** [dteviot/WebToEpub#277]
Hello,

Recently I wanted to pack the whole serie : https://babelnovel.com/books/my-cold-and-beautiful-wife

But when I tried to use it (example: selecting chapter 151 to 200), the app immediatly crash and it display an error :

pre is null findContent@moz-extension://8112d8e6-5bdf-4455-a167-288a16667a51/js/parsers/BabelChainParser.js:48:26 convertRawDomToContent@moz-extension://8112d8e6-5bdf-4455-a167-288a16667a51/js/Parser.js:62:28 webPageToEpubItems@moz-extension://8112d8e6-5bdf-4455-a167-288a16667a51/js/Parser.js:154:28 webPagesToEpubItems@moz-extension://8112d8e6-5bdf-4455-a167-288a16667a51/js/Parser.js:263:43 epubItemSupplier@moz-extension://8112d8e6-5bdf-4455-a167-288a16667a51/js/Parser.js:247:30 packEpub@moz-extension://8112d8e6-5bdf-4455-a167-288a16667a51/js/main.js:156:37 fetchContentAndPackEpub/<@moz-extension://8112d8e6-5bdf-4455-a167-288a16667a51/js/main.js:135:20 

It worked before but now it didn't work anymore.

**Comment by dteviot** [comment]
@Senastra
Tricky. Site has changed layout. From quick inspection I can see that:
1. Text for each chapter is now in a REST call. e.g. for chapter 151, the HTML call is https://babelnovel.com/books/my-cold-and-beautiful-wife/chapters/c2 but the text is in "content" element of JSON from https://babelnovel.com/api/books/my-cold-and-beautiful-wife/chapters/c2 
2. The content mixes text from multiple stories. The text is "unmixed" by using a Cascading Style Sheet (CSS). Difficulty is that css is obtained from a URL like https://babelnovel.com/content-css?hash=fa180f3c8378668d4fd3e3f4cb04eba3 where the hash value is (probably) per page.  Figuring out how to obtain the hash is going to take considerable effort.

**Comment by Senastra** [comment]
Ok thanks, I hope you will find a way to fix it.

**Comment by dteviot** [comment]
@Senastra
Sorry, I wasn't clear. At this point in time I have no plans to get WebToEpub working with BabelNovel.

Comments on their Discord channel suggest that their monetization strategy is to put novels on Amazon for sale.  As such, they don't want people to download the chapters from their website.
To discourage downloading, BablelNovel is deliberately mixing the stories together.  It doesn't stop the downloading, but the result is not really readable.
Now, I could probably figure out how to to unscramble the text (I think I just have to figure out how to calculate the hash)  But that could take me days of effort.  And in a few weeks, the scrambling method will probably change again.
And, to be perfectly blunt, much as I'd enjoy the intellectual challenge, I've got other things I will enjoy doing even more in my limited spare time.

I will offer the following suggestions:
1. You could contact the operators of BabelNovel and see if they'll offer an unscrambled download to paid members.
2. WebToEpub is open source, so you could have a go at figuring out how to unscramble the text yourself.  I don't know what your programming skills are.  (If you want to go this path, feel free to ask me for assistance.)  Incidentally, if you can figure out how to unscramble the text, I'd probably be willing to implement the code.
3. You could try finding others who want WebToEpub to work for BabelNovel and see if they can help.  (hint @T-Man2000  and @sephile have also asked for babelnovel/babelchain support.)

Good luck, and if you learn anything, please let me know.

**Comment by JeremyStarten** [comment]
Hey so, recently I also wanted to make an epub of a story on babelnovel and saw this post so I am here to offer you my time-consuming workaround that also isn't 100% perfect. Now it is more manual and doesn't involve webtoepub (sorry, not a programmer so can't do option 2) but it worked when I tested it. Unfortunately, it really isn't the best cause it can take some time but the steps are simple.

1. Use a program or plugin that can take a screenshot of the novel, in my case I used [PDF Mage](https://chrome.google.com/webstore/detail/pdf-mage/gknphemhpcknkhegndlihchfonpdcben)
2. Go to the book you want and just keep scrolling through from the chapter you want the epub to start with to the one you want it to end with, this is so the website loads the chapters
3. Use PDF Mage or whatever and create the pdf of the chapters (This can take a long time which is why I said time-consuming, just 25 chapters took like 5-10 min to process and was 91 pages long)
4. Use a program like [Calibre](https://calibre-ebook.com/) to convert the PDF to an epub, please note that while you do this, go into pdf input and check no images, otherwise you will have to manually remove them.

Now the rest is just to clean the epub up, if you don't that's fine but I think it's better if you do.

5. Open the epub in Calibre to edit it, go to edit Table of Contents and click Generate ToC from major headings, remove the entries that are not chapter numbers or the start (I suggest deleting the whole page itself as they are generally not chapters and just say share and stuff)
6. Use the find and replace all function of your editor and remove all the stuff you don't want, like the junk at the end of most chapters.
7. Edit the metadata of the book and put whatever in the correct info.
8. Put a nice cover on

Well, that's it, I have seen some weird spacing between letters rarely, but that's just a result of the conversion from pdf to epub.

Whether or not you use this is up to you, personally I wouldn't unless I really liked the novel as it takes so much time. I'll also attach a result of the process, it's
[My Cold and Beautiful Wife - Ch 151-160.zip](https://github.com/dteviot/WebToEpub/files/3342592/My.Cold.and.Beautiful.Wife.-.Ch.151-160.zip)


Just to note, I have never read that novel before so I have no idea if something is horribly wrong but scrolling through it seemed fine and the one I did for myself was also fine.

**Comment by T-Man2000** [comment]
Copy and paste into a Word file and then use Caliber to convert and edit it into an ePub file. Or the GrabMyBooks extension can help.

**Comment by dteviot** [comment]
@T-Man2000 
I suspect doing copy/paste will give you the mixed up text from multiple stories.

@Senastra, @JeremyStarten, @Senastra 
I think I've figured out how to solve babelnovel.
WebToEpub is in a web browser.  So, rather than try to figure out how to decode everything, I can let the browser do it.  So steps are (for each chapter):
1. Open a new tab for the wanted web page (chapter), 
2. Wait for the page to load.  (The browser will then do all the decoding.)
3. Inject a background script into the web page to collect the content.

I might try this in the weekend, if I can find the time.

**Comment by aurimasniekis** [comment]
@dteviot I needed one book on the go so I made some temp fix which makes it create a book from babelchain its not pretty but it gives you some idea I guess here is PR #290

**Comment by dteviot** [comment]
@aurimasniekis  
Thank you.  Looks like site has stopped mixing content from multiple stores together.
I want to spend more time with your commit.  It's not working reliably for me.  I think it's some sort of timing issue, if I try to open WebToEpub too soon after going to a book.

**Comment by dteviot** [comment]
@Senastra @T-Man2000 @sephile @JeremyStarten
Fix provided by @aurimasniekis (thank you) has been pushed to Chrome & Mozilla stores.
I'm going to call this closed.  Please let me know when the site changes and breaks it again.

**Comment by sephile** [comment]
Ohhh thanks alot man really appreciate your efforts
