### ISSUE TITLE
Paragraph/word deletation when the symbols '<>' are used

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#278]
I came across some VRMMO novels that take liberty with "< system >" and the general use of "<>" parameters every time the author wants to advance the plot. The problem is, when compiling  WebtoEpub will simply ignore the letter or the paragraph that is encased between the parameters.

Reference: Novel (Martial gamer; Chapter 2)

Exact quote: 

> The four of them were in a gaming studio which was dedicated to farming gold in various games and were currently operating in a game called << REBIRTH>>. <<REBIRTH>> was the latest game that Mu Zi Xian's company had released just 3 days ago that was exploding in popularity.

Paragraph with WebtoEpub:

>The four of them were in a gaming studio which was dedicated to farming gold in various games and were currently operating in a game called <>. <> was the latest game that Mu Zi Xian's company had released just 3 days ago that was exploding in popularity.

**Comment by dteviot** [comment]
@DicerX 
I need URL of site (or chapter) please.

**Comment by dteviot** [comment]
@DicerX 
I've tried the following URLs
* https://www.wuxiaworld.co/MMORPG--Martial-Gamer/1147859.htm.  This does not have any "angle brackets" in the text
* https://www.novelspread.com/chapter/mmorpg-martial-gamer/c-2-joining-a-gold-farming-studio This also does not have "angle brackets" in the text
* https://wuxiaworld.live/mmorpg-martial-gamer/chapter-2.  Has text that is sort of mangled like you describe.  e.g. 
> were currently operating in a game called &lt;&lt; REBIRTH&gt;&gt;. &lt;&gt; was the latest game

Note, examining the raw HTML shows the problem is the "angle brackets" in the second case are not being properly escaped.

To make any more progress, I need the URL for the source.

**Comment by DicerX** [comment]
Sorry for the delay, but I just came back to recompiling this epub, and it turns out that this is not a problem from your side at all.

I use Sigil for heavy duty editing on my epubs, and it is the reason for paragraph/sentence deletion, it immediately seeks "to correct" these paragraphs by adding </REBIRTH> to <<REBIRTH>> and so on. This just destroyed half this novel. Sorry for bothering you with this mate.
