### ISSUE TITLE
does not work in https://www.machine-translation.org

### ISSUE THREAD

**Issue by itsyahma** [dteviot/WebToEpub#294]
After the packing epub process is complete sometimes webtoepub cant pack the epub

**Comment by dteviot** [comment]
@itsyahma 
That's not a lot to go on.
Can you describe in more detail what you mean by "can't pack the epub".
That said, my initial guess is WebToEpub is running out of memory.  Do the stories have thousands of chapters?
Also, does it consistently fail for specific chapters?  If so, can you give me the URLs for a couple that fail and a couple that succeed?

**Comment by itsyahma** [comment]
Yes,it dies have thousands of chapters but after the initial process loading the chapters, webtoepub just stops responding and stops working

**Comment by dteviot** [comment]
@itsyahma 
Sorry, error on my part.  I meant to ask, what's the URL of the STORY(s) that have a problem.  (So I can try to reproduce.)

**Comment by itsyahma** [comment]
https://www.machine-translation.org/novel/59a0fdb102f27493/fantasy-world-transmigration.html try this url

**Comment by dteviot** [comment]
@itsyahma 
Thank you for the link.
I still suspect you're hitting a problem with running out of memory.
Loading the 1385 chapters of the story into memory consumed 3.2 Gigs of memory (Chrome only gives an extension no more than 4 Gigs to work with, regardless of how much memory the PC has.)
And that 3.2 was before it's packed into an epub (which takes more memory).
Unfortunately, for security reasons it's not possible for an extension to tell how much memory it has/is still available, so I can't get WebToEpub to give a warning when it's running low.
You can check the memory (and CPU consumption) yourself by opening the Chrome Task Manager https://www.howtogeek.com/437681/how-to-use-chromes-built-in-task-manager/

Anyway, I suggest you try packing no more than 500 chapters into a single epub at a time and see if that behaves.  (And let me know the results.)
Note, I've created a parser explictly for Machine-Translations, so that's a bit more memory efficient.  
I'll push the updated version to the Chrome web store probably tomorrow.

**Comment by itsyahma** [comment]
thanks, will check after the update

**Comment by dteviot** [comment]
@itsyahma
Updated version has been pushed to Chrome and Mozilla stores.  Should be available within a few hours.

**Comment by dteviot** [comment]
Closing due to no response from original opener.  If there's a problem, let me know and I'll re-open

**Comment by itsyahma** [comment]
Thanks it works, just forgot to reply
