### ISSUE TITLE
BabelNovel, save is blowing up since Nov 1

### ISSUE THREAD

**Issue by 8917489712a** [dteviot/WebToEpub#300]
The chapter prefix used to work with C now needs a lower case c.  In addition, just today there seems to be some ddos thing from cloudflare

--
Error: Fetch of URL 'https://babelnovel.com/api//books/supreme-evil-sovereign/chapters/c98' failed with network error 429.     at FetchErrorHandler.onResponseError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:25)     at Function.checkResponseAndGetData (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:163:45)     at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:157:31     at async Promise.all (index 1

**Comment by dteviot** [comment]
You're right about the lower case 'c'.
As regards the 429 error, it's not responding with a retry after, so don't know how long to wait.
If you try for about 50 chapters every 10 minutes or so, seems to be happy.
I could look at implementing an exponential back-off on a 429 error, but that's not doing to be done for days at least.

**Comment by dteviot** [comment]
@8917489712a 
As you seem to have some skills (you figured out the issue with c and seem to have fixed it yourself)  I think a quick and dirty fix for the 429 bug would be add that to the error cases in the function getAutomaticRetryBehaviourForStatus(status) in the file HttpClient.js.  e.g. 
```javascript 
        case 429: 
            // server is rate limiting
            return {maxRetry: 1, promptUser: true};
```
This should result in Web To Epub stopping when a 429 error occurs and offering you the chance to start again.  So, something of a manual process, but I think would at least let it work, until I can come up with a better solution.

**Comment by dteviot** [comment]
@8917489712a 
Thanks for the information.  Have made following changes
1. Added hard coded throttle of approximately 20 chapters per minute to BabelNovel parser.  This seems to avoid triggering the Cloudflare rate limit.
2. Fixed case in chapter names.

New version (0.0.0.92) has been uploaded to Chrome and Mozilla stores.  Your copies should update automatically within 24 hours.

Note, the rate limiting is something of a band aid fix.  I'll still need to add automatic handling of HTTP 429 errors.  But at least this should stop people complaining that BabelNovel doesn't work.  (At least until the next time the site changes and something breaks.)

**Comment by joonsaepark** [comment]
The latest and greatest babelnovel returns the json below so there's probably some magic that needs to happen

{
"data": {
"prevId": null,
"nextId": "0537b8a8-01ec-47e6-af90-d583bdb708be",
"index": 1,
"brick": 4,
"isFree": true,
"isBought": false,
"isBorrowed": false,
"chapterOrderId": null,
"isLimitFree": true,
"originBrick": 4,
"discountRate": 0,
"bookId": "dc7f7672-6876-454e-87cd-17005f15de85",
"content": "Please update the Babelnovel app.",
"url": null,
"type": "babelchain",
"zhSourceURL": null,
"zhTitle": null,
"name": "C1 Beauty Genius and Good-for-nothing",
"num": 10000,
"publishTime": "2018-08-29T00:00:00Z",
"translatorId": null,
"canonicalName": "c1",
"translateStatus": "finished",
"voteId": null,
"isPublish": true,
"updateTime": null,
"createTime": null,
"id": "82a3f4a9-1803-499f-8dc4-2cb4da39e2e1"
},
"code": 0
}

**Comment by joonsaepark** [comment]
apparently content was added as a suffix

    static guessChapterList(bookEntity) {
        let list = [];
        for(let i = 1; i <= bookEntity.chapterCount; ++i) {
            let name = `c${i}`;
            list.push({
                sourceUrl: `https://babelnovel.com/books/${bookEntity.canonicalName}/chapters/${name}/content`,
                title: name
            });
        }
        return list;
    }

**Comment by dteviot** [comment]
@joonsaepark 

Unfortunately, it turned out to be more complicated than that.
Using the REST URL you suggest returns text from multiple chapters mixed together (probably to discourage things like WebToEpub.)  See https://github.com/dteviot/WebToEpub/issues/277
The good news is, I believe I've found where the hash mentioned in that issue is.

So, I believe the steps for unscrambling the content are as follows:
1. Assume we want c1 for a story.
2. Fetch the HTML page at https://babelnovel.com/books/peerless-divine-emperor/chapters/c1
3. Find the script element with `window.__STATE__`, unpack this. See function getStateJson() in BabelChainParser.js
4. Extract the hash from the JSON.  Hash is found in member `chapterDetailStore.cssUrl` and looks like /content-css?hash=5e60164cffb59e1c13967652156aa007
5. Get the CSS file at https://babelnovel.com/content-css?hash=&lt;hash&gt;  (where &lt;hash&gt is value from previous step.)
6. in CSS file, find line where selectors are set to: width:0; height:0.  These are selectors for elements to remove
7. Make REST call to get content: https://babelnovel.com/api/books/peerless-divine-emperor/chapters/c1/content
8. Remove the unwanted elements from content.
9. Convert &lt;span&gt; elements into &lt;p&gt; to clean up the output.

Updated version has been pushed to Chrome web store.  Google tells me it might take 30 days or more to be approved and available in store.

**Comment by dteviot** [comment]
Version on chrome store has been updated.
