### ISSUE TITLE
BabelNovel - Temporary free novel

### ISSUE THREAD

**Issue by Flwk** [dteviot/WebToEpub#309]
Hello

Now, BabelNovel have some novel that can be temporary free like [this](https://babelnovel.com/books/my-wife-is-a-beautiful-ceo), but the plugin doesn't work and we have some epub like [this](https://we.tl/t-xQjDaxSikL)

Is it possible to resolve this issue ? 

Best regards and thanks for the works,
Flw

**Comment by dteviot** [comment]
@Flwk 
This looks like the problem version 0.0.0.92 of WebToEpub had when BabelNovel changed their site recently.
It was fixed in version 0.0.0.93
Note, Initially I only updated the version on the Chrome store to 0.0.0.93.
I've just uploaded the new version to the Mozilla store.
So, 
1. If you're running the Chrome version of the extension, please check it's version 0.0.0.93.  If it's not,, manually update it.  https://gadgets.ndtv.com/apps/features/how-to-manually-update-google-chrome-extensions-661907
2. If you're running Firefox, follow these instructions to update. https://support.mozilla.org/en-US/kb/how-update-add-ons  And my apologies for the trouble this has caused you.

Please let me know if this has solved your problem.

**Comment by dteviot** [comment]
@Flwk
I double checked the sample epub you provided.  It was created using version 0.0.0.92.
I'm confident upgrading to 0.0.0.93 will solve the problem.
