### ISSUE TITLE
Getting the CSS element

### ISSUE THREAD

**Issue by wintersnew** [dteviot/WebToEpub#314]
Hi, I'm having a problem on how to resolve this. It seems it can't get the css of the highlighted box below:
![Capture](https://user-images.githubusercontent.com/38267997/71239299-2a6f3900-2341-11ea-8d42-2473d757ca2c.PNG)

This is the only thing i can get right now, and its incomplete
![Capture2](https://user-images.githubusercontent.com/38267997/71239301-2a6f3900-2341-11ea-8486-d6c48b56b165.PNG)

As for the the source here it is: https://webnovelonline.com/chapter/the_beginning_after_the_end/chapter-1

**Comment by dteviot** [comment]
@wintersnew 
The problem you've having with webnovelonline.com is that the raw HTML from the site only has the start of the chapter's text in the 
```html
<div class="chapter-content">
```
element.  The whole text is inside a block of JSON that's inside one of the &lt;script&gt; elements.  The page then uses Javascript to move the whole text into the "chapter-context' element when it's viewed in a web browser.
As WebToEpub works on the raw HTML, this requires building a full parser extract the full chapter text.
Which I did 'yesterday https://github.com/dteviot/WebToEpub/commit/c0ca5935f6f1ecb5a1137ccb035190a073dec26f#diff-49b386c1b8ce1207820d00a2827c299a for your request https://github.com/dteviot/WebToEpub/issues/313.  
However, I haven't updated the version in the web store as yet, because this week I got requests to add 5 new parsers and I haven't yet received confirmation that dark-novel.ru is working.  Due to holidays, and assorted other things, I would not expect it to be available in the Chrome store for downloading for at least a week.

If you'd like it sooner, you could go to https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode and follow the instructions for "Install from Source" from **the current development branch**. (Do NOT use the master branch, that tracks the latest version available from the store.) Please let me know if you have any issues.

**Comment by wintersnew** [comment]
Oh, i see ... gonna try it then.

**Comment by wintersnew** [comment]
It works. Thanks a bunch.
