### ISSUE TITLE
Error when running node pack.js

### ISSUE THREAD

**Issue by tcgoetz** [dteviot/WebToEpub#318]
I wrote a new parser and was attempting to lint it before submitting a pull request, but I 

I get the following error when running `node pack.js`: 

`TypeError [ERR_INVALID_CALLBACK]: Callback must be a function. Received undefined
    at maybeCallback (fs.js:135:9)
    at Object.writeFile (fs.js:1234:14)
    at /Users/tgoetz/Projects/WebToEpub/eslint/pack.js:101:12 {
  code: 'ERR_INVALID_CALLBACK'
}`

complete output attached: [log.txt](https://github.com/dteviot/WebToEpub/files/4022056/log.txt)

**Comment by dteviot** [comment]
@joarder

The error message indicates the problem starts at line 101 of the file pack.js
which is a call to fs.writeFile().
https://github.com/dteviot/WebToEpub/blob/efadd8b87c894fea5a729815563c4365f1b4d9ec/eslint/pack.js#L86-L105


A quick Google suggests the fix is to replace the calls to fs.writeFile() in that function with fs.writeFileSync().
https://github.com/awslabs/aws-data-lake-solution/issues/37
Note, there is also a call to writeFile() in line 48, but that DOES supply a callback.

I suspect the problem is you're using a newer version of node than I am and with the newer version the callback parameter is not optional.
FWIW, I'm running version 6.9.1  (Yes, I know, I should update it)
Anyway, I've committed fix to the ExperimentalTabMode branch.

**Comment by tcgoetz** [comment]
Works for me.
