### ISSUE TITLE
Chrome fails to save epub if it has tilde (~) in Filename

### ISSUE THREAD

**Issue by 3dycosmo** [dteviot/WebToEpub#322]
Only on Chrome (works on firefox) quite weird cases after changing the filename
![Screen Shot 2020-01-22 at 18 00 49](https://user-images.githubusercontent.com/4585442/72888997-51a29700-3d41-11ea-83d7-d1f1dc36a9f0.png)

https://novelplanet.com/Novel/Maou-Sou-da-Yuusha-wo-Yome-ni-shiyou
after that, I changed the Filename field to 

> Maou ~ Sou da, Yuusha wo Yome ni shiyou ~ [Complete] JP

not packaging albeit finished parsing all pages
and if I parsing without changing the name is fine tho
Mac Chrome 79.0.3945.130

**Comment by dteviot** [comment]
@3dycosmo

I'm not entirely sure from your description, but it sounds like the problem might be the value you're setting for Filename might be a problem on a Mac.
That is, it's not the packing that's a problem, but the writing to a file because the filename isn't legal.
I don't have access to a Mac but you might like to run some tests to confirm the hypothesis.

To make things quicker, instead of saving an entire story, set it to a single chapter for the following steps.
1. Try saving a simple filename, Say "Maou"
2. If that works, confirm by opening the epub file.
3. Then try extending the name a bit more e.g. "Maou ~ Sou"
4. If that works, confirm by opening the epub file.
5. Keep on extending until it the save fails.  That should tell us what part of the filename is giving problems.  

Once you know what part of the Filename causes the problem, Please let me know.

**Comment by dteviot** [comment]
@3dycosmo
Seems to be a bug in Chrome.  Also appears on Windows version of Chrome.
Having a "~" in the filename means it fails to write to the epub to disk.  
Opening the console shows the error
> runtime.lastError: Invalid filename

**Comment by dteviot** [comment]
Looks like it's known behavior.,  https://stackoverflow.com/questions/30960190/problematic-characters-for-filename-in-chrome-downloads-download.
Fix will be to add the tilde to characters WebToEpub won't allow in the Filename.
