### ISSUE TITLE
https://www.mtlnovel.com/god-of-fishing/ error

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#337]
https://www.mtlnovel.com/god-of-fishing/
Was able to DL few days ago half of it, now it show error. Other novel seems to work just fine on same site

Tested on firefox and chrome version, both error

SyntaxError: Unexpected end of JSON input
    at JSON.parse (<anonymous>)
    at FetchJsonResponseHandler.<anonymous> (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:212:31)
    at async MtlnovelParser.getChapterUrls (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/parsers/MtlnovelParser.js:21:28)

**Comment by dteviot** [comment]
@Finks82 
Sorry for delay in getting back to you, I've been busy the last few days.

Anyway, the problem is the Table of Contents for that story is broken.
You can see it for yourself:
1. Go to https://www.mtlnovel.com/god-of-fishing/
2. Click on the "Chapters" tab
3. Expand "Chapters 1 - 250".  No chapters are shown.  (Looking at network traffic, the call to https://www.mtlnovel.com/json/89777-c-4-3.json?__amp_source_origin=https%3A%2F%2Fwww.mtlnovel.com which should return the chapters returns nothing.)

My suggestion is to contact the site admins and inform them of the problem.

**Comment by dteviot** [comment]
Closing due to no response from @Finks82
