### ISSUE TITLE
error novelspread

### ISSUE THREAD

**Issue by Garbok** [dteviot/WebToEpub#339]
When I tried to create epub of series Thriller paradise [https://m.novelspread.com/novel/thriller-paradise] with selector "body", this Is the result: 
[We're sorry but m.novelSpread.com doesn't work properly without JavaScript enabled. Please enable it to continue.]

**Comment by dteviot** [comment]
@Garbok 
Updated version (0.0.0.105) has been posted to Chrome and Firefox stores. Firefox store has new version available. Chrome will be a few days to finish review.
If there are any issues, Just add a comment to this issue and I'll reopen.

FWIW, Looks like this site is mobile version of novelspread.
You get that message because this site doesn't put the content in the html.  
Instead the page runs javascript to fetch the content from elsewhere and insert into page.
