### ISSUE TITLE
request add readlightnovel.cc

### ISSUE THREAD

**Issue by minshimun** [dteviot/WebToEpub#341]
I'm using firefox android

**Comment by dteviot** [comment]
@minshimun 
Site isn't working for me.  For example, 
1. I go to https://www.readlightnovel.cc/Release-that-Witch/
2. I get a list of chapters, but they all link to the same URL, (the home page above)  Clicking on any of them just reloads the page.  Looking at the raw html, their href attribute, which should be the chapter's URL, is empty.
Same thing for 
* https://www.readlightnovel.cc/Martial-God-Asura/
* https://www.readlightnovel.cc/Naughty-System-In-The-Multi-Universe/

**Comment by minshimun** [comment]
Apparently the sites not working properly today

**Comment by minshimun** [comment]
@dteviot 
It now works

**Comment by dteviot** [comment]
@minshimun
I've attempted to add support for this site.  However, site's playing up again, so I wasn't able to fully test.
Updated version (0.0.0.107) has been posted to Firefox store and is available. There is no chrome version because you're using Firefox.
When the site starts to behave again, please let me know if WebToEpub is working OK or not.

**Comment by dteviot** [comment]
Closing due to lack of response from @minshimun  If there are problems, please let me know.
