### ISSUE TITLE
CORS policy related errors - solvable?

### ISSUE THREAD

**Issue by lll000111** [dteviot/WebToEpub#351]
I get

> popup.html:1 Access to fetch at 'https://www.royalroadcdn.com/covers/15538-displaced-full.jpg?time=1590522256' from origin 'chrome-extension://akiljllkbielkidmammnifcnibaigelm' has been blocked by CORS policy: The value of the 'Access-Control-Allow-Origin' header in the response must not be the wildcard '*' when the request's credentials mode is 'include'.

and I don't know if there is a solution for those. Not a single image in epubs from RoyalRoad because of this (other then asking RR to change their CORS policy - which won't happen).

Could the extension work inside the page itself instead of opening a tab? No idea.

I tried two CORS-changing Chrome extensions, [this one for example](https://chrome.google.com/webstore/detail/allow-cors-access-control/lhobafahddgcelffkeicbaginigeejlf?hl=en), and next [this one](https://chrome.google.com/webstore/detail/cors-unblock/lfhmikememgdcahcdlaciloancbhjino?hl=en), without success.

I found Chrome flag `chrome://flags/#cors-for-content-scripts` and set it to "Disabled", again without success.

Feel free to just close if there is no (good) solution from your side.

Example: https://www.royalroad.com/fiction/15538/displaced

Result: ![image](https://user-images.githubusercontent.com/25476357/85832797-03327200-b791-11ea-8145-7e36e17c7303.png)

**Comment by dteviot** [comment]
@lll000111 

That's very odd.  I just tried https://www.royalroad.com/fiction/15538/displaced  and did not get any of the issues you show.  And the epub seems to have the images. I'm using Chrome version  83.0.4103.116 
I don't know why it doesn't work for you.  I see you have a number of other extensions loaded, possibly there's some conflict with one of them?
Has this problem suddenly appeared, or has it never worked?
I also have a firefox version of the extension, it's got some code for messing with CORS (see below) you might try it.

I see you have developer skills, so there's a couple of things you could try.
1. The error says can't use a wildcard with "include".  So, you could remove "include" from the fetch call.  (Note, this will mean any cookies that are used for authentication won't be passed to the site.  May give problems.)
https://github.com/dteviot/WebToEpub/blob/e261941a010ef3f523465416a79513835429106a/plugin/js/HttpClient.js#L109-L112

2. The Firefox version of the plug-in uses the webRequest API to remove the origin line (Chrome version doesn't because Google  gets... difficult about approving extensions use that API).  Anyway, you might modify that code to tweak the origin in a request.
https://github.com/dteviot/WebToEpub/blob/e261941a010ef3f523465416a79513835429106a/plugin/js/Firefox.js#L10-L19

**Comment by lll000111** [comment]
> I see you have a number of other extensions loaded, possibly there's some conflict with one of them?

I tried in Anonymous Mode, where only uBlock Origin is enabled, same result. I'll experiment a bit more.

**Comment by dteviot** [comment]
@lll000111

Googling the error message leads me to https://stackoverflow.com/questions/42803394/cors-credentials-mode-is-include
Following the links to http://50linesofco.de/post/2017-03-06-cors-a-guided-tour suggests error message is a fetch request using a wildcard cors 
> res.set('Access-Control-Allow-Origin', '*')
and credentials.  (apparently a no-no).
The weird thing is, WebToEpub doesn't use CORS.  At least, I don't remember doing it.  And grep doesn't show Access-Control-Allow-Origin.  Also when I check the networking tab, I don't see it in the headers.  So, I'm thinking something your side is trying to add CORS headers to the calls.  
At this point, I don't think I can do much more to help you.

**Comment by lll000111** [comment]
Fair enough, I'll close and experiment.

**Comment by lll000111** [comment]
@dteviot 

SOLVED

In the settings page for all Chrome extensions there is a section

> Site access
> Allow this extension to read and change all your data on websites you visit:
> &#9678; On click
> &#9678; On specific sites
> &#9678; On all sites

I had switched to "On click", which leads to the above problem. If it is set to "On all sites" it works.

**Comment by dteviot** [comment]
@lll000111

Thank you for letting me know.  Much appreciated.
