### ISSUE TITLE
Add option to Bold text in Quotation marks

### ISSUE THREAD

**Issue by ragen123** [dteviot/WebToEpub#360]
Can you add an option to bold text in Quotation marks?

Like this  **“The best investments today”**

https://www.asianovel.com/ epub maker automatically does it. It would be cool to add it to webtoepub too. Thx

**Comment by dteviot** [comment]
@ragen123
This seems more like a "Modify an epub" feature, rather than a "Make an epub".
So, I'm not willing to add it to WebToEpub.
However, https://github.com/dteviot/EpubEditor, one of my other projects, is a tool for modifying epubs.
If you re-raise this request on that project, I'll see what I can do when I have some time.  (Might be a while.)
Alternatively, you could ask around on the Calibre forum https://www.reddit.com/r/Calibre/ if they have a plugin that does what you're asking.

**Comment by ragen123** [comment]
Thx for answering, will try out caliber.
