### ISSUE TITLE
Incorrect blogspot url conversion

### ISSUE THREAD

**Issue by mobedoor** [dteviot/WebToEpub#389]
Hi. In [this](https://skythewood.blogspot.com/2018/02/GJ1010.html) page
This [image url](https://lh4.googleusercontent.com/IACIoq8JcJb5rc4qfz0WK34_X19WnCgHfTfIiSq17ocsRGhMppYrlD2YgTtHp8zlnKS7jtv-X9FttHMlafhLQUDJ9mFem6_fucgvecoC4QZnEqtqU9YC9stpKUj_9XehrxNZqCZL) is replaced by https://lh4.googleusercontent.com/s0/IACIoq8JcJb5rc4qfz0WK34_X19WnCgHfTfIiSq17ocsRGhMppYrlD2YgTtHp8zlnKS7jtv-X9FttHMlafhLQUDJ9mFem6_fucgvecoC4QZnEqtqU9YC9stpKUj_9XehrxNZqCZL
The added s0 in this case does not redirect to anything.

**Comment by dteviot** [comment]
@mobedoor

Thank you for bringing this to my attention.

*Note to self.  Root cause of problem*
To make error clearer. a /s0/ is added to the image's URL.
Reason for this is:
A previous request to get full size images on blogspot.  To do this, make sure s0 is in URL's path before the final name.
However, in this case, while HTML is hosted on blogspot, Image is NOT hosted on blogspot.
So, before trying to modify URL to fetch full size image, check IMAGE is also hosted on blogspot.

**Comment by dteviot** [comment]
@mobedoor
Fix has been committed.  Won't be available in Chrome or Firefox stores until next update (perhaps this weekend.)
If you can't wait, you can get the unsigned extensions from https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing
and load manually using these instructions. https://www.cnet.com/how-to/how-to-install-chrome-extensions-manually/
Note, you don't need to look for the crx file or convert to zip.  I've already done that for the files there.
Note, you want the 121 version for Chrome or Firefox.  Ignore the Oxford versions.

**Comment by mobedoor** [comment]
Works perfectly @dteviot .
Thanks a ton.
