### ISSUE TITLE
Request: Warning popup if I try to close the WebtoEpub tab when it's working

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#394]
Often I accidentally close the WebtoEpub tab while it is the middle of a very long compilation. I wish if there's a popup that prevents the closure of the tab when WebtoEpub is working.

Cheers

**Comment by dteviot** [comment]
Note to self:
See: https://developer.mozilla.org/en-US/docs/Web/API/WindowEventHandlers/onbeforeunload
Quote
> When this event returns (or sets the returnValue property to) a value other than null or undefined, the user will be prompted to confirm the page unload

**Comment by dteviot** [comment]
Unfortunately, it's a bit hard to tell if busy or not.  Work is done in background threads, and the error handling doesn't work quite right.  That is, if an error occurs, main window might not know processing has ended due to error.

**Comment by DicerX** [comment]
Suppose you're asking if I'm busy then not. Not this year at least. Willing to test anything you throw at me no problems, but I'm a bit of a dimwit when it comes to coding apologies.

**Comment by dteviot** [comment]
@DicerX
No. that was a note for me.  The error handling in WebToEpub is a bit broken.  I'd fix it, but it's really complicated and I'm somewhat worried that trying to fix it might break it in other ways.
This might be an issue because we don't want the "are you sure you want to close this window" warning should only appear if WebToEpub is busy.
So, WebToEpub should set a flag when it starts processing an epub, and clear the flag when it finishes.
However, due to the above bug, if somehting goes wrong, the "finish" is never reached (even if processing halts).  And hence, the flag is never cleared.  So, you'd always get the warning if an error occurred.
Which, on reflection, might not be an issue.

What do you think?

**Comment by DicerX** [comment]
>So, you'd always get the warning if an error occurred.

Since in both cases, we get a popup, we just have to live with it. And in my experience, unless I am manually setting up WebtoEpub on a novel site, you'd rarely, if ever, get an error notification. 

You call it a bug, but I see a feature, go for it, mate. 

Regards

**Comment by dteviot** [comment]
@DicerX 
I've made the change.
As it will be a while before I update the versions in the Chrome and Firefox stores (there are other features/fixes I need to do)
I've posted Chrome and Firefox versions to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing
You can load them using the "Install from source" instructions found at https://github.com/dteviot/WebToEpub#how-to-install-from-source and try it out.

Note, the zip files contain all the files needed. So you can skip most of the steps.
For Chrome, Just do step 2, then go to step 6
For Firefox, Do step 2, then go to step 8

**Comment by DicerX** [comment]
Terrific, just tested, works like a charm. I will close this issue now.

Regards

**Comment by dteviot** [comment]
@DicerX
Reminder: Please raise an issue against WebToEpub
> I always remove habitually now is the information page at the start of every epub, is it possible to disable it completely in the advanced section

**Comment by DicerX** [comment]
Alright will do so. I just recalled that I wrote that when I was a little
tipsy so I'll fix the phrasing there lol.
