### ISSUE TITLE
Please Fix noveltrench support and add support for active translation

### ISSUE THREAD

**Issue by darkharrycracker** [dteviot/WebToEpub#401]
Please Fix noveltrench support and add support for active translation:
- [x] in https://noveltrench.com/ you only get the discordlinks not the chapters
- [x] https://activetranslations.xyz/ is a good website
- [ ] also wuxiaworld.site it stops after the first chapter

**Comment by darkharrycracker** [comment]
also wuxiaworld.site it stops after the first chapter

**Comment by darkharrycracker** [comment]
[https://imgur.com/CsO6SzT](url)
this is what i did Noveltrench but i need to put chapter url cause it is wrong and i dont know how to edit your URL grabber

**Comment by dteviot** [comment]
@darkharrycracker
> also wuxiaworld.site it stops after the first chapter

https://wuxiaworld.site/novel/ill-add-points-to-all-things/ works fine for me.  Please give URL that doesn't work.

**Comment by MirCton** [comment]
@dteviot i think he's using the mobile version

**Comment by MirCton** [comment]
@dteviot wuxiaworld.Site stops working after a few tries.

**Comment by dteviot** [comment]
@MirCton 

Can you be more detailed?
e.g. 
1. What do you mean by "after a few tries"?  How many attempts of doing what exactly?
2. What do you meant by "stops working"?

Note, It sounds to me like site might be doing some sort of throttling/rate limiting.

**Comment by dteviot** [comment]
@darkharrycracker
noveltrench.com was easy to do.  It has same layout as webnovel.live
activetranslations.xyz will be a few days (I hope)

As it will be a while before I update versions in stores (because there's more tasks in my to do queue first) you might like to install from source.
Firefox and Chrome versions have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing

You can use the "Install from Source" instructions at https://github.com/dteviot/WebToEpub.

>  i did Noveltrench but i need to put chapter url cause it is wrong and i dont know how to edit your URL grabber.
Some novel you just have to reverse the url then trim it a little and its fine.

I'm not sure I understand the problem.  Click the "Reverse Chapter URLs Order" button (just above the list of chapters) to reverse the order of the chapters in the EPUB.

**Comment by MirCton** [comment]
@dteviot this 
![Screenshot_20201024_142403](https://user-images.githubusercontent.com/73046010/97069708-99be5500-1604-11eb-8ee5-0213ad9725fe.jpg)
might be the reason it stops.

**Comment by darkharrycracker** [comment]
@dteviot when creating the epub in WW.site when i press pack epub the progress stop at the first chapter and "it times out"/the epub gets downloaded with only the summary or first chapter.

**Comment by dteviot** [comment]
@darkharrycracker
As MirCton said, you're probably running into the Cloudflare DDoS protection.

**Comment by dteviot** [comment]
@darkharrycracker
I believe I have active translations working.  Note, because a number of chapters are listed as premimum, I can't test them.  Also, as the ToC don't mark premium chapters, WebToEpub can't automatically unselect them.

I'm not going to try an fix the Cloudshare DDOS problem with wuxiaworld.site.  It's more effort than it's worth.
You might try waiting a few days, then make sure you set "Max web pages to fetch simultaneously" under the advanced tab to 1 for that site.  But I'd just try looking for the stores on an aggregator site.  e.g. https://novelfull.

Anyway, updated version 0.0.0.121 has been uploaded to Firefox and Chrome stores.  Firefox version is available, Chrome should be available in a few days once it finishes review.


At any rate, new v
