### ISSUE TITLE
Add

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#402]
please add https://engnovel.com/ to the list.
And can https://translatinotaku.net/ be added too?

**Comment by dteviot** [comment]
@sigmatc
One site per request, please.

**Comment by sigmatc** [comment]
https://engnovel.com/ please
translatinotaku.net seems to frequently change the layout.

**Comment by dteviot** [comment]
@sigmatc
What part of "One site per request" do you not understand?

**Comment by dteviot** [comment]
D'oh!.  Sorry, misunderstood you.

**Comment by dteviot** [comment]
@sigmatc
I think I've got engnovel working.
translatinotaku.net is mostly working.  You need to manually open the Tables of Contents to show the chapters for WebToEpub to be able to find them.  (For the 10 or so stories on the site, I'm not willing to spend more time on it.)

As it will be a while before I update versions in stores (because there's more tasks in my to do queue first) you might like to install from source.
Firefox and Chrome versions have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing

You can use the "Install from Source" instructions at https://github.com/dteviot/WebToEpub.

**Comment by dteviot** [comment]
@@sigmatc
Updated version 0.0.0.121 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in a few days once it finishes review.
