### ISSUE TITLE
Teasers of upcoming chapters on WuxiaWorld break the epub lol

### ISSUE THREAD

**Issue by Paradoxicaily** [dteviot/WebToEpub#406]
I am trying to make an epub for "Trash of the Counts Family" on "Wuxiaworld."
" https://www.wuxiaworld.com/novel/trash-of-the-counts-family "
First I'll give an example of a teaser 
" https://www.wuxiaworld.com/novel/trash-of-the-counts-family/tcf-chapter-50 " Its at the very bottom, the little yellow box that you have to click to open. It has an image in it and when you make the epub of the novel it creates an error I think. Because the error says its because of an image. But thats the only image I see...
But it only gets the error when the epub is large. 
So say that I make the epub from 1 to 618 (the current chapter) I get around 50+ of these errors
If I go from 1 to 200 I still get about 20.
But if I go from 1 to 100 I dont get any... at least not yet. (I've only done this once so far)
I should also say that I read online that using Epub 3 is better so Im making them in epub 3 for the 1 to 100 chapter epubs.
But I have tried to make the 1 to 618 using a normal epub and an epub 3 and both failed because of that same error.
The same error showed up with "Yamas Rising" also on Wuxiaworld. When I tried to make an epub from chapter 1 to chapter 196 (current newest chapter) This was also done in epub not epub 3.
I will have more information on this soon just tell me if you would like me to edit my main post to add the information like this
"Edit 1: _____"
or if you would like me to add replies to this post.
or if you know about this and have known about this and I'll get out of your hair.
(If I sound dumb right now, just know this is my first post so I have 0 clue what Im doing I really hope that this info helps to make the extension better though. I love what you do thank you for making it.)
(Also, also if you need screenshots please tell me in depth how you would like them. I dont know if I can just add them or not lol. But if its as simple as a quick google search then I've got you.)
(Also also when I say normal epub I mean whatever is the default epub [when you dont have epub 3 checked])

**Comment by dteviot** [comment]
@Paradoxicaily 
I'd really like to see the error message(s)
Probably the easiest way is:
1. Click the "Advanced Options" button
2. Make sure  "Write error messages to file" is checked.
3. Create an epub
4. At end, after trying to save Epub (click "OK") will then try to save the errors.
5. Attach file to this incident.

Failing that, you should be able to select the error text, then just copy and paste it into a message here.

**Comment by dteviot** [comment]
@@Paradoxicaily
OK, I just went to https://www.wuxiaworld.com/novel/trash-of-the-counts-family and built an epub from chapter 1 to 618
It created an epub, but also gave a number of errors.
The error messages were of the following 2 forms

Error: Fetch of image 'https://cdn11.bigcommerce.com/s-5uqrjcd/images/stencil/1280x1280/products/39341/56418/RRNF_MonstersOnLand_CVR_RGB__27775.1429221653.jpg?c=2&imbypass=on' for page 'https://www.wuxiaworld.com/novel/trash-of-the-counts-family/tcf-chapter-303' failed with network error 404.
    at FetchImageErrorHandler.onResponseError (chrome-extension://ibocneadjplakiolkocjijamlalnhnlk/js/HttpClient.js:28:25)
    at Function.checkResponseAndGetData (chrome-extension://ibocneadjplakiolkocjijamlalnhnlk/js/HttpClient.js:160:45)
    at chrome-extension://ibocneadjplakiolkocjijamlalnhnlk/js/HttpClient.js:154:31
    at async Promise.all (index 6)


Warning: image file 'Images/0001_a3voa13z.png' is in webp format.  Your epub viewer may not be able to render it.


You don't really need to worry about these.
The first sort of error message is saying that the page has a link to an image, but WebToEpub was unable to get the image, probably because the image is no longer there.
You could try opening the page in the browser and see if the image shows.
In the case of https://www.wuxiaworld.com/novel/trash-of-the-counts-family/tcf-chapter-303, you are correct, it's a hyperlink to the teaser.
(WebToEpub sees it as a hyperlink to an image, and is attempting to fetch the image.)

In the second case, WebToEpub has fetched the image.  However the image is a webp file, so most epub readers won't show it.
I've got a tool that can convert the webp files in an epub into jpegs. Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing and download the MergeWebToEpub zip

**Comment by dteviot** [comment]
@Paradoxicaily
I think I've fixed the problems.
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing.  Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know if that solves most of your problems.

**Comment by Paradoxicaily** [comment]
I was working a lot sorry about not getting back to you. I see what you are saying thank you for fixing the problem If I find another I will let you know.
