### ISSUE TITLE
[Enhanchement] Firefox - Keep compatibility with non-WebExtension Browser

### ISSUE THREAD

**Issue by typhoon71** [dteviot/WebToEpub#42]
If it's possible and not too much work, I suggest to keep compatibility with non-WebExtension "enabled" Browser.
This includes Firefox 47 which is the last stable since Firefox 48 should be out in August(and support WebExtension), and other forks like Palemoon.
I won't ask for Other Chrome derivates because they should already be working (Iron does work).

**Comment by dteviot** [comment]
@typhoon71
I'm sorry, but I don't understand the request.

Here's the situation.
WebToEpub was originally written as a Chrome extension.  (Actually, I first considered making it a Firefox XUL extension, but when I saw the work required to do that I changed my mind and went the Chrome extension route, much less work.)

When I saw that FireFox is able to run Chrome extensions via WebExtensions, I offered the Extension for Firefox.  There was one issue were the "download the packed epub" worked on Chrome but not Firefox. Gusser93 provided a fix.

So, to re-iterate.  There is only one WebToEpub.  To make the Firefox version I literally take the WebToEpub.zip file I send to Google, rename it to "WebToEpub.xpi" and send that to Mozilla.  It works because it uses the WebExtensions.

**Comment by typhoon71** [comment]
mmmm, what you wrote means that the addon should never have worked on Firefox 47, since WebExtensions aren't supported on it... But I'm pretty sure I was able to use it a couple of times...
Just asking, did something change in the code that downloads the images? 
(issue #27, the second image I posted is what I'm referring to)

**Comment by dteviot** [comment]
@typhoon71
Firefox 47 has some WebExtensions support.  It's just not fully implemented.
And I've seen the plug-in do funny things on Firefox 47.
As regards downloading, yes, there were some changes in the released 0.0.0.9, to support user specifying Cover as a URL.  Is it still not working on Firefox?

**Comment by typhoon71** [comment]
Nope, it's not working on my firefox (47.0.1)
It didn't work on Firefox 48b5 too.
Maybe it works in Aurora? I will try tomorrow.

**Comment by typhoon71** [comment]
Awww, wrong button.
Anyway I made an effort and checked with Firefox 49.0a2, and it works.

**Comment by typhoon71** [comment]
OK, I did some more testing and found that the plugin seems to have compatibility issues with some firefox addons even on Firefox 49.0a2, but it work with a "pure" profile.
I'll test my addons one by one and report back in a new issue.
I'm closing this one (I didn't know it was born as webextensions addon).
