### ISSUE TITLE
Request for CHYOA or is it too much? 

### ISSUE THREAD

**Issue by MirCton** [dteviot/WebToEpub#426]
Been reading stuff on it but Internet here is unstable was thinking if it's possible for webtoepub to include the choices

Example https://chyoa.com/story/The-Gamer%2C-Chyoa-edition.12004

**Comment by dteviot** [comment]
@MirCton
It should be possible.
The stories provide a map, that can be used to get list of chapters.
However,for reasons that are not clear (and I don't have time to look into) the code that's supposed to fix-up the hyperlinks to point to other chapters in the epub does not work.

**Comment by MirCton** [comment]
It will do

**Comment by dteviot** [comment]
@MirCton
OK then, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Warning, you should probably start with story with only a few chapters.  Some of the stories are large, and
1. Take a long time to fetch
2. Make WebToEpub run out of memory and crash.  (Sorry, I can't do anything about that, I've tried.)

**Comment by MirCton** [comment]
Thank you

**Comment by dteviot** [comment]
@MirCton
Updated version 0.0.0.124 has been uploaded to Firefox and Chrome stores. Firefox version is available, Chrome should be available in 3 to 7 days, once it finishes review.
Note, it still has the problems I mentioned above.
As regards the problem of links to chapters not working, I believe I have a solution.  
WebToEpub can't fix up the hyperlinks, because when it processes each page, it doesn't know what name it will assign the destination to in the epub at that time.  The links need to be fixed up after the epub is made.
I'm working on a tool to do that.

**Comment by dteviot** [comment]
@MirCton
Well this is embarrassing.
Looks like SOME of the links are fixed up.  The links to forward chapters ARE being fixed up.
The links on each chapter to "Previous Chapter" and "Start Over" are not fixed up, but that's because the URLs are different to the ones used to get to the chapter, so WebToEpub doesn't recognize them.
So, at this point, I'm going to call it done.
