### ISSUE TITLE
Delay every few chapters

### ISSUE THREAD

**Issue by Windklingenherr** [dteviot/WebToEpub#442]
Hello,
I am using Version 0.0.0.124 on Firefox.
Lately, every time I download a novel from RoyalRoad (https://www.royalroad.com) there is a short delay every 5-6 chapters. This happens with every novel that is longer than the aforementioned amount of chapters. I assume this happens if there are too many requests per second, as I once got an error message saying this while opening more chapters in another tab. However, I was unable to reproduce this.
Is it possible to add an option in the advanced option that lets people control that?

**Comment by dteviot** [comment]
@Windklingenherr 
See: https://github.com/dteviot/WebToEpub/issues/420
You're seeing the delay because RoyalRoad is telling WebToEpub to back-off, and it's doing so.  Then resuming.
However, as you're the 3rd person making this request in the last few days, it looks like the code might need improvement.
