### ISSUE TITLE
add an option to delay grabbing the next chapter by a set amount of seconds to avoid site throttling

### ISSUE THREAD

**Issue by alexrc55** [dteviot/WebToEpub#457]
i want to pull a story from a website but i can only get 15 pages before a throttle kicks in and creates the epub with only some of the chapters. https://re-library.com/ is the site in question but i think a manual delay where i can set a number of seconds to wait before going after the next chapter would be a somewhat universal fix and would allow this to be dealt with on any site.

**Comment by dteviot** [comment]
@alexrc55
OK, I see the problem.
Site is returning a HTTP 509 error (Bandwidth exceeded), instead of a 429 error (Too Many Requests)
I've patched WebToEpub to treat a 509 same as a 429 (do an exponential back-off)
Seems to work, provided you set Max web pages to fetch simultaneously to 1.
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by alexrc55** [comment]
it seems to work thanks

**Comment by dteviot** [comment]
@alexrc55
Updated version (0.0.0.126) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.
