### ISSUE TITLE
Add Site https://hostednovel.com/

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#465]
https://hostednovel.com/

**Comment by dteviot** [comment]
@sigmatc
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note, for it to work properly, launch WebToEpub when viewing a synopsis tab (e.g. https://hostednovel.com/6/novel/era-of-disaster) rather than the "chapter list" tab (https://hostednovel.com/6/novel/era-of-disaster/chapters)

**Comment by dteviot** [comment]
@sigmatc
Updated version (0.0.0.126) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be avaiable in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

**Comment by Flwk** [comment]
Hello

It seems that it doesn't work anymore : 

![image](https://user-images.githubusercontent.com/3245665/113498430-2e5ea480-950d-11eb-8e7c-912a85c2509f.png)
