### ISSUE TITLE
Missing namespace?

### ISSUE THREAD

**Issue by toshiya44** [dteviot/WebToEpub#49]
> This file has no namespace. Its namespace must be http://www.w3.org/1999/xhtml. Set the namespace by defining the xmlns attribute on the <html> element, like this <html xmlns="http://www.w3.org/1999/xhtml">

This is the error calibre's editor tells me. It asks me to put `<html xmlns="http://www.w3.org/1999/xhtml">` instead of writing just `<html>` in the xhtml or html files in the book. 

Also, every single paragraph and heading tag has `xmlns="http://www.w3.org/1999/xhtml"` written inside it. Sample,
`<p xmlns="http://www.w3.org/1999/xhtml">`
`<h2 xmlns="http://www.w3.org/1999/xhtml">`
`<h3 xmlns="http://www.w3.org/1999/xhtml">`

Calibre can still open the book, but I guess it might be an issue for other lightweight apps.
(using Firefox 49.0a2)

**Comment by dteviot** [comment]
I didn't see this with Chrome.
Looks like Firefox handling of namespaces is a bit different that Chrome's.
FWIW, the two effects are related.  If you apply the Namespace to a parent element, the child elements inherit it automatically, so they don't need an explicit xmlns element.  As it hasn't been applied to the <html> element, Firefox is applying it to the children.    If that makes sense.  This is related to https://github.com/dteviot/WebToEpub/issues/50

**Comment by dteviot** [comment]
Thinking about this, should be possible to prove this by running the unit tests. Try opening the file Tests.html in the unittests folder.  Should get a huge number of errors.

**Comment by belldandu** [comment]
Can confirm i had these issues even when opening Tests.html in firefox aurora. I had initially ignored them because it didn't seem like they cause any issues however you are right it could potentially cause issues in the more light weight readers.

**Comment by dteviot** [comment]
Well, here's your problem:  
https://developer.mozilla.org/en-US/docs/Web/SVG/Namespaces_Crash_Course
Unfortunately, I haven't yet figured out how to generate elements using a namespace prefix.  Firefox seems to want to generate a full xmlns element.  Which I think is going to confuse the simpler readers.

Of greater concern, I suspect that when the HTML elements from Baka-Tsuki are copied into an XHTML document, they're still going to be HTML elements.  So they'll need to be rewritten to XHTML.  Chrome seems to be smart enough to figure out this is what's going on and rewrites the elements for us. Which is why it closed the &lt;br&gt; elements. I **suspect** we got epubcheck errors with &lt;br&gt; elements when running under Firefox because FireFox doesn't change the elements.  Note, I'll need to confirm this.

How to fix:
- We could do the HTML to XHTML conversion ourselves.  Could have a lot of tricky edge cases.
- We go to EPUB3, which allows HTML5 for items, and ignore the XHTML completely.  This means however we only support EPUB3 capable readers.

**Comment by belldandu** [comment]
Priority changed due to affecting firefox review.

**Comment by belldandu** [comment]
HTML to XHTML
CONS:
1. Edge Cases can cause a multitude of problems
2. Readers could possibly non complaint and *NO LONGER ACTIVELY DEVELOPED*
3. Ugly code.
PROS:
1. We don't have to rewrite much.

HTML5 & EPUB3
CONS:
1. We have to rewrite a lot.
2. We would be in beta for a while which means no releases for a while.
PROS:
1. While we may have to rewrite a lot we won't have to worry about a LOT of edge cases since HTML5 is VERY lenient and is Globally accepted even on desktop environments (meaning we could make a desktop app out of it if we decided to be derp enough to do it xD).
2. Readers will most likely be MORE compliant because EPUB3 is fairly new as well as HTML5.
3. Readers are *ACTIVELY DEVELOPED* and are more willing to accept changes to make them more complaint with a standard because of this.
4. Can use the HTML5 Standard to make cosmetic changes we normally wouldn't be able to do with xhtml

Thats all from me @dteviot

**Comment by dteviot** [comment]
@belldandu 
I was under the impression that a minimal level of EPUB3 support isn't difficult.  Really, just need to add a table of contents.  But then I've barely looked at EPUB3.

**Comment by dteviot** [comment]
Should now be fixed.

**Comment by belldandu** [comment]
@dteviot i was mainly listing all the potentials. As for EPUB3 i haven't looked at it much myself either.

**Comment by toshiya44** [comment]
@belldandu We won't be using any fancy EPUB3 features, so there won't be any compatibility issues with readers. 
But I think having a valid xhtml output is still the best option, for compatibility reasons. What are the edge cases are you talking about?

**Comment by toshiya44** [comment]
Since the original issue was fixed, should I close this?

**Comment by dteviot** [comment]
@toshiya44
>What are the edge cases are you talking about?

Well, one of the ones I know about is that this is legal in HTML, but not in XHTML.
```html
<b><i>some text</b></i>
```
Note that the two tags overlap, rather than one enclosing the other.
What really concerns me is the edge cases I don't know about.
However, it turns out the CORRECT way to convert nodes from XHTML to HTML is to use document.importNode().  Which is what I'm doing now and it works for both Firefox and Chrome.
That being the case, I think the question of how to convert is solved.

> Since the original issue was fixed, should I close this?

Yes please.
