### ISSUE TITLE
Add website specific code for hosting on a server

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#51]
requested by amit34521 over at Baka-Tsuki

> Can someone add a similar generator for the mobile users or some other option for the mobile users who used the epub generator before???

Simply add an index.html file and call the required files and add more javascript if need be.

I can easily host it on my dedi when this is done :D

**Comment by dteviot** [comment]
We may need to discuss this some more.  I think it's closely related to https://github.com/dteviot/WebToEpub/issues/23  In that if the extension is opened as a tab, (rather than a popup) it looses many of an extension's abilities.  So, in that mode it's running exactly like a normal web page.  i.e. Implementing https://github.com/dteviot/WebToEpub/issues/23 should provide same code needed for server hosting.

**Comment by belldandu** [comment]
@dteviot Sure

**Comment by belldandu** [comment]
See #23
