### ISSUE TITLE
Please add a list of all the supported sites to readme.

### ISSUE THREAD

**Issue by credulous2skeptic** [dteviot/WebToEpub#510]
**Is your feature request related to a problem? Please describe.**
Currently the readme contains the list of a couple of sites supported by webtoepub followed by the text "and many other sites". But no indication of what other sites are supported.

**Describe the solution you'd like**
Please add a list of all supported sites to the readme.

**Comment by gamebeaker** [comment]
@credulous2skeptic 
you can have a broad view here https://github.com/dteviot/WebToEpub/tree/master/plugin/js/parsers name of the .js file is normally the website name. There are more Websites included but they don't have an extra file because sometimes one file is the same for multiple sites (if the sites have the same layout for example). 
Example: MadaraParser.js include the sites listnovel.com, readwebnovel.xyz, wuxiaworld.site, pery.info, morenovel.net, nightcomic.com, webnovel.live, noveltrench.com, mangasushi.net, mangabob.com

If you only want to check if one site is included you can open all .js files in notepad++ and search with crt+f "Find all in All Opened Documents"

Alternative:
If you want to know if your site is included simple try to download from this web site and if it isn't supportet you can request this site here on GitHub or create your own parser. tutorial: https://dteviot.github.io/Projects/webToEpub_DefaultParser.html 

Maybe if i am bored i am going to post one complete list in this issue.

**Comment by dteviot** [comment]
@gamebeaker 
Unfortunately, It's not that simple.
While there are parsers for specific sites (host names), WebToEpub also looks for some common formats and can handle them automatically.  e.g. It can detect sites made using Madara theme.  Likewise, a large number of sites (but not all) based on WordPress and BlogSpot can be automatically handled.

And arguably, any site that can be handled by the default parser (with some configuration by the user) could also be classed as supported.

**Comment by dteviot** [comment]
@credulous2skeptic
What do you hope to gain from having such a list?
The easiest way to see if WebToEpub works for a site is browse to a site and click the WebToEpub button.

**Comment by credulous2skeptic** [comment]
Yeah I guess I could just browse to a site and try downloading. I asked because I have seen a similar project with a list of all the sites. I'll close the issue now.
