### ISSUE TITLE
Please add site: https://babelnovel.com/

### ISSUE THREAD

**Issue by AzureSky191** [dteviot/WebToEpub#524]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by AzureSky191** [comment]
The website is https://babelnovel.com/

URL of novel chapter list:
https://babelnovel.com/books/skirt-chasing-young-monarch-city-lady-killer/chapters

**Comment by dteviot** [comment]
@AzureSky191
BabelNovel is already supported (for various values of supported) by WebToEpub.

Seems to be an issue with that story, as I can't view the chapters with an ordinary browser.  E.g.
1. Open a browser, 
2. Go to https://babelnovel.com/books/skirt-chasing-young-monarch-city-lady-killer, 
3. Click on 'C1', the resulting page is a 404.

However, if I try: https://babelnovel.com/books/immortals-dump-waste-in-my-home
I can get chapters 1 to 3 with no problem.  Note, I didn't try for more than that, and I don't know what happens when you hit your chapter limit for the day.

**Comment by dteviot** [comment]
@AzureSky191
Closing due to lack of response.
