### ISSUE TITLE
Please add site https://aerialrain.com

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#540]
![Screenshot 2021-06-01 074951](https://user-images.githubusercontent.com/67751123/120256699-6e909800-c2ae-11eb-8931-a35cf003ebab.jpg)

the-healer-demands-payment/

I tried doing it on my own but this was the result - the Title was ok, content was ok, removed the TOC NEXT and back 
only one chapter was done

Not in the field but i tried and found the limit

**Comment by sigmatc** [comment]
![Screenshot 2021-06-01 075134](https://user-images.githubusercontent.com/67751123/120256855-c4654000-c2ae-11eb-8292-e7c92d73a966.jpg)

**Comment by dteviot** [comment]
@sigmatc 
You were pretty close.  
The CSS selector for the content was just "div.entry-content"
and the selector for title of chapter was "div.post-header h1"
I suspect it failed on other pages is because the #post-120 changes on each page.
Anyway, I've added a parser for this site.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

For my notes: this was an easy one, 20 minutes to do.

**Comment by dteviot** [comment]
@sigmatc
Updated version (0.0.0.133) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
