### ISSUE TITLE
Please add site https://chichipeph.com/

### ISSUE THREAD

**Issue by sigmatc** [dteviot/WebToEpub#546]
https://chichipeph.com/the-former-wife-of-invisible-wealthy-man/

### Did you try using the Default Parser for the site?  If not, why not?

Yes i tried.

### What settings did you use?  What didn't work?
* https://chichipeph.com/2020/11/19/fw-chapter-1-1/
* div.entry-content
* h3.overlay-h-title
* div.entry-meta

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
 Sorry, not in the field
 
![Screenshot 2021-06-10 100230](https://user-images.githubusercontent.com/67751123/121464401-8addb480-c9d3-11eb-8aaf-f4542447a7f0.jpg)
![Screenshot 2021-06-10 100256](https://user-images.githubusercontent.com/67751123/121464408-8ca77800-c9d3-11eb-8436-ee2d9c1053f9.jpg)

**Comment by sigmatc** [comment]
4 chapters could be downloaded but other than that ... nothing
first it was upto chapter 4 but the next it was 7

**Comment by dteviot** [comment]
@sigmatc 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Follow the "How to install from Source" instructions at https://github.com/dteviot/WebToEpub#how-to-install-from-source and let me know how it goes.

Note:  Some of the chapter links seem to be wrong.  If you tick the "Show URLs of Chapters" button, you will see that some chapters have URLs like https://chichipeph.com/wp-admin/post.php?post=445&action=edit, instead of URLs like https://chichipeph.com/2020/11/22/gtvftbv-chapter-19/.  Those URLs don't work.  Try clicking on chapter 4 and following it normally in a browser.  You should probably contact the site and inform them of the problem.

For my notes: time taken to write parser: 35 minutes.

**Comment by dteviot** [comment]
Updated version (0.0.0.134) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
