### ISSUE TITLE
Website Chrysanthemum Garden have a problem

### ISSUE THREAD

**Issue by KaterinaSawyer** [dteviot/WebToEpub#591]
I tried to turn Chrysanthemum Garden's web into an epub but some paragraphs came out as jumbled texts and can't be read at all. Is there a way to fix this?

![39EB231F-05C5-4167-A2FA-60729FD34545](https://user-images.githubusercontent.com/90402642/132707557-5a7e6ff6-5763-4ba7-acad-ee4c62fa3f65.jpeg)

**Comment by dteviot** [comment]
@KaterinaSawyer
It's probably fixable.  To save me time, 
1. What's the URL of a story you're having problems with, and which chapters?
2. Do all stories show this, or just some?

**Comment by KaterinaSawyer** [comment]
1. https://chrysanthemumgarden.com/novel-tl/pisdd/pisdd-1/
2. Yes, all stories show this

Really grateful if you can fix this, thank you very much.

**Comment by dteviot** [comment]
@KaterinaSawyer
Apologies, This is a repeat of https://github.com/dteviot/WebToEpub/issues/354

Short answer:  
1. Go to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing and download EpubEditor.zip
2. Unpack the zip and open the file Open main.html in chrome.
3. Drag and drop Chrysanthemum Garden epub onto the drop zone.
4. A set of buttons will appear, click the second from bottom labelled "Clean ChrysanthemumGarden"
5. Wait a little bit.  You should get a file dialog asking you for name to save the fixed epub.

Slightly longer answer.
Basically, in order to prevent the chapters on site being copied, the site scrambles the text and uses a special font to unscramble the text.  Because this is done as a copyright mechanism, if WebToEpub was to unscramble the text it would get WebToEpub removed from the chrome store.
However, I can provide a tool to unscramble the file that's not on the Chrome store.

 If you have any problems, please email me at dteviot@gmail.com

**Comment by KaterinaSawyer** [comment]
Just wanted to say, thank you very much! It worked well!

**Comment by LadyAmalthia** [comment]
Thank you so much for this fix!
