### ISSUE TITLE
For some browsers, I think calling window.alert() crashes the extension.

### ISSUE THREAD

**Issue by dteviot** [dteviot/WebToEpub#61]
Need to investigate further.
Firefox docs say don't do it.  https://developer.mozilla.org/en-US/docs/Web/API/Window/alert  but I'm not sure the recommended alternate works on Chrome.

**Comment by belldandu** [comment]
@dteviot As far as i know for both chrome and firefox window.alert brings up a box on the whole browser that stops all interaction. So if someone where to click on it and hold for too long the extension would close because you "technically" clicked outside of the popup. I have actually done this several times while testing. I clicked the ok button for the alert and held for to long so the browser recognized that i clicked outside of the extension popup and closed it.

In any case i will only be available for 9 more hours after which no one will be able to contact me for 6 months.

**Comment by dteviot** [comment]
On further investigation, window.alert() is not crashing the extension. When extension has opened as a popup window, window.alert() **_hides_** the popup window.  If you set Firefox to "disable popup auto hide", the extension's popup window remains visible.  Have not yet found out how to restore window's visibility in code.  Aside: if open extension's window as Tab, this is probably a non-issue.

**Comment by dteviot** [comment]
Issue https://github.com/dteviot/WebToEpub/issues/69 requires removing all use of alert().
Which renders this bug moot.
