### ISSUE TITLE
Please add site https://https://chrysanthemumgarden.com/novel-tl/wcsp/

### ISSUE THREAD

**Issue by sakunakai** [dteviot/WebToEpub#629]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by sakunakai** [comment]
I tried creating the epub from this site https://chrysanthemumgarden.com/ but the file is not downloading fully. First few chaps get downloaded then when I click again to download a chapter gets omitted automatically.

**Comment by dteviot** [comment]
@sakunakai 
I just tried https://chrysanthemumgarden.com/novel-tl/voac/ with no problems.
What's the URL of story you're having a problem with?

**Comment by sakunakai** [comment]
https://chrysanthemumgarden.com/novel-tl/wcsp/

**Comment by sakunakai** [comment]
@dteviot I'm also facing problems with the image for this novel: https://amytranslations929.wordpress.com/lovely-allergen/
After the file is downloaded an error shows which states that the image cannot be fetched from this URL.

**Comment by sakunakai** [comment]
Error: Fetch of image 'https://media.chrysanthemumgarden.com/2019/11/75A5A006-87D1-4CB5-B30B-79052389DB2B.png' for page 'https://chrysanthemumgarden.com/novel-tl/sbme/sbme-1/' failed with network error Failed to fetch.
    at FetchImageErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:158:45
    at async Promise.all (index 0)
    at async WordpressBaseParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)

**Comment by dteviot** [comment]
Seems to be a malformed &lt;img&gt tag on chapter 18.
As a work around, open the advanced settings and put a tick the "Skip Images" option.

**Comment by sakunakai** [comment]
Error: Fetch of image 'https://scontent.fdac134-1.fna.fbcdn.net/v/t1.15752-9/249897242_409994264104762_1757098495241730874_n.jpg?_nc_cat=110&ccb=1-5&_nc_sid=aee45a&_nc_ohc=zJuW_02AqrYAX-7-518&_nc_ht=scontent.fdac134-1.fna&oh=e30ed6f554d15bac2c4d9fc924e7793f&oe=61AE6D93' for page 'https://chrysanthemumgarden.com/novel-tl/sbme/sbme-1/' failed with network error Failed to fetch.
    at FetchImageErrorHandler.onFetchError (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:28:31)
    at chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/HttpClient.js:158:45
    at async Promise.all (index 0)
    at async WordpressBaseParser.fetchWebPages (chrome-extension://akiljllkbielkidmammnifcnibaigelm/js/Parser.js:462:17)

**Comment by dteviot** [comment]
@sakunakai 
I've think I've solved the problem with WebToEpub halting with the malformed image on https://chrysanthemumgarden.com/novel-tl/wcsp/
Note, you'll still get the ugly error message, but the epub will be produced and images will be there.
(You won't see the images for chapter 18 because the first image is a emoticon that the site has a weird way of formatting and the second one is the malformed img tag, so doesn't have an image.) Chapters 10 and 26 do have images.

I've also tried:
* https://chrysanthemumgarden.com/novel-tl/sbme/, which doesn't seem to have any images.
* https://amytranslations929.wordpress.com/lovely-allergen/, and it seems to have collected images without any problem.
I don't know why you had problems with them.  Possibly there were network issues.  That's usually when I see the error message "failed with network error Failed to fetch."

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

(REMEMBER TO TURN OFF "Skip Images".)

**Comment by dteviot** [comment]
@sakunakai 
Updated version (0.0.0.143) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
