### ISSUE TITLE
Please add site https://web.archive.org/web/20161119214524/http://www.wuxiaworld.com/cdindex-html/

### ISSUE THREAD

**Issue by budikesuma** [dteviot/WebToEpub#634]
Hello Devs...
since the completed novel in WW locked by karma.  So working from web archive sources will solve the problem, as some people prefer the original format over unclean aggregated sources.  So I ask developers to start adding web archive sources for us, thanks.

`Sample of Completed novel url: `
https://web.archive.org/web/20161119214524/http://www.wuxiaworld.com/cdindex-html/

**Comment by Synteresis** [comment]
Not the one to make the call, but depending on the website, getting every webarchive chapter would be many times slower than normal as well as older versions of the same sites having a different format compared to newer ones.

**Comment by dteviot** [comment]
@Synteresis 
There's code in ParserFactory.js that's supposed to handle web archive.  I'm not sure why it's not working.  I'll look into it in the next few days if I can find the time.

**Comment by dteviot** [comment]
@budikesuma 
Sorry, the problem is the Wuxiaworld site changed its format, and the current version of WebToEpub only knows how to handle the current format. 
It looks like build 0.0.0.45 of WebToEpub was last version that supported this particular format.

Unfortunately, I don't have a copy of that build still around.  If you want, I can probably try and build a custom version of WebToEpub that would work for this case. but it would not work for the current Wuxiaworld site.

**Comment by budikesuma** [comment]
> @budikesuma Sorry, the problem is the Wuxiaworld site changed its format, and the current version of WebToEpub only knows how to handle the current format. It looks like build 0.0.0.45 of WebToEpub was last version that supported this particular format.
> 
> Unfortunately, I don't have a copy of that build still around. If you want, I can probably try and build a custom version of WebToEpub that would work for this case. but it would not work for the current Wuxiaworld site.

no problem, I can use the CSS method manually, so I'll close this. Thankfully...
