### ISSUE TITLE
Fanfiction.net - Incorrect Chapter URLs in Chrome

### ISSUE THREAD

**Issue by duplaja** [dteviot/WebToEpub#670]
**Describe the bug**

When using the extension on Fanfiction.net, it removes the story ID from the URL in the chapter URLs, and replaces it with the chapter id.

**To Reproduce**
1. Go to a FFN story.
2. Run Extension

**Expected behavior**
Correct chapter URLs

**Screenshots**
![chapter-links](https://user-images.githubusercontent.com/20245408/147424576-17273998-620d-49a6-be0a-de9b255ad617.png)

**Desktop (please complete the following information):**
 - OS: Ubuntu 20.04
 - Browser Chrome
 - Version: Latest

Tested with version from Chrome Web store, and version from the Google Drive.

**Comment by gamebeaker** [comment]
Hi i tried to replicate your error but wasn't able to.
The nearest i got was when i modified the Starting URL from: https://www.fanfiction.net/s/9472509/1/Red to: https://www.fanfiction.net/s/9472509/1 
I don't know how you got the wrong Starting URL. If you paste the "wrong" URL in your browser it will show the correct page but it will not work inWebToEpub.
How do yout got the "wrong" URL? (How did you navigate there? Because if you open the book from the autor page: https://www.fanfiction.net/u/1597325/Ludwig-Mies-van-der-Rohe it redirects you to the "right" URL. Same if you open it from the search.)
Hope i was able to help.

**Comment by dteviot** [comment]
@gamebeaker, thanks for your help.

@duplaja 
It looks like, if you try opening https://www.fanfiction.net/s/9472509/
it goes to https://www.fanfiction.net/s/9472509/?__cf_chl_jschl_tk__=7z1IfW2gZS9tXgi86cadkECEOW.4iHRifbpGE6j7Nlc-1640674012-0-gaNycGzNCRE
Which does not work using the current logic to build the chapter URLs.
Need to build chapter URLs using onchange attribute of the &lt;select&gt; element.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

I tested against https://www.fanfiction.net/s/9472509/?__cf_chl_jschl_tk__=7z1IfW2gZS9tXgi86cadkECEOW.4iHRifbpGE6j7Nlc-1640674012-0-gaNycGzNCRE

For my notes: 43 minutes work.

**Comment by duplaja** [comment]
Thank you, that took care of it! I appreciate it!

**Comment by dteviot** [comment]
@duplaja @gamebeaker 
Updated version (0.0.0.145) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
