### ISSUE TITLE
Problem with Vivaldi 1.3.551.17 and Saving Epubs

### ISSUE THREAD

**Issue by dergrossealtertas** [dteviot/WebToEpub#68]
Saving Epubs doesn´t work with Vivaldi (no problem with chrome).
You can click on Pack Epub, after the loading is done nothing happens (allready tried automatically saving to default location), the file doesn´t download.
If you use the "Open as Tab" option the file downloads without any problems.

**Comment by dteviot** [comment]
@dergrossealtertas
I don't support the Vivaldi browser.
Given the amount of time (and effort) it takes just to support Firefox as well as Chrome, I'm not willing to support any other browsers.  If it works, fine.  If it doesn't, sorry, you'll need to find someone else to fix it.

That said, given that it works when running in Tab mode, the problem is probably that when running in popup mode the Extension's window is hidden when it loses focus.  It's loosing focus because there's a download dialog popping up.  That is, a "download" dialog is being opened, but you can't see it, and it's waiting on you to OK the download. I suggest you email the Vavaldi developers to see if they can look into it.

**Comment by dergrossealtertas** [comment]
Thanks for the fast response :)
"That said, given that it works when running in Tab mode, the problem is probably that when running in popup mode the Extension's window is hidden when it loses focus. It's loosing focus because there's a download dialog popping up. " 
Yeah I thougt so too at first, that´s why I tried the "Automatically Save to default location" option in vivaldi (no download dialog appears), but that too doesn´t work.

Today I opened a ticket on the vivaldi bugtracker, thank you for your help.

**Comment by dteviot** [comment]
@dergrossealtertas
> Today I opened a ticket on the vivaldi bugtracker, thank you for your help.

Can you please give me the ticket details, I'd be curious to learn what happens.  I might learn something useful.

**Comment by dergrossealtertas** [comment]
@dteviot 
Sure, Ticket Number is VB-20212, just don´t expect too much, they don´t have a public bug tracker. Even I can´t track the progress of the ticket ...

**Comment by dteviot** [comment]
@dergrossealtertas 
Thanks.

**Comment by dteviot** [comment]
@dergrossealtertas 
As extension now opens in tab mode by default, and this works in Vivaldi, I'm going to call this closed.
