### ISSUE TITLE
cheeki request add support for https://web.archive.org/web/20211119045220/https://www.royalroad.com/fiction/36049/the-primal-hunter/ possible? reason in comments

### ISSUE THREAD

**Issue by mhussaincov93** [dteviot/WebToEpub#708]
hi
would it be possible for web to epub to support this?
it has all chapters vs on the non web archive.org site which has chapters now removed.
this would also be a greate way to get old fics that no longer are hosted on rr.
and other sites like ff.net via web archive.
exammple.
https://web.archive.org/web/20160509043825id_/https://www.fanfiction.net/s/2159217/1/
I realize that they are 2 different sites.
thank you for considdering my request.
Majid

**Comment by mhussaincov93** [comment]
note the url change in my comment
the
id_  is important.
so a url would look like this:
https://web.archive.org/web/20211119045220id_/https://www.royalroad.com/fiction/36049/the-primal-hunter/chapter/565298/chapter-19-everybody-loves-blue-mushrooms

**Comment by dteviot** [comment]
@mhussaincov93 
In future, one site per request please.  It makes it easier for me to keep track of things.

The given fanfiction.net link https://web.archive.org/web/20160509043825id_/https://www.fanfiction.net/s/2159217/1/
Doesn't seem to work.  I can go to that link, but if I try to go to any other chapters of the story, they don't seem to be archived.
I think the problem is, fanfiction.net doesn't have links to other chapters on the page, so the web archive doesn't have anything to follow and archive.

I tested, https://web.archive.org/web/20211129005747/https://www.royalroad.com/fiction/36049/the-primal-hunter.  Chapters 1 and 303 worked with no problems.  Note, when I tried getting ALL chapters, web archive complained about the load, so you'll need to set the rate limiting options.  And I can't guarantee web archive has saved all chapters.

For my notes: 15 minutes work.
