### ISSUE TITLE
Webnovel chapters no longer load

### ISSUE THREAD

**Issue by Kiradien** [dteviot/WebToEpub#717]
**Describe the bug**
Generating an epub from Webnovel runs into a content detection error. 
Error: Could not find content element for web page

After inspecting the retrieved dom element, page has several signs that it is still in a "loading" state and has not yet retrieved the chapter data.

**To Reproduce**
1. Go to 'webnovel.com' and select any novel on the Table of Contents view
2. Click on 'Pack Epub'
3. Generation will fail on first chapter.

**Expected behavior**
Generation to go through successfully

**Desktop (please complete the following information):**
 - OS: Windows 10
 - Browser: Chrome
 - Version: 99.0.4844.84 (Official Build) (64-bit)
 - WebToEpub version: 0.0.0.147

**Additional context**
The main problem relates to content retrieved when calling HttpClient.wrapFetch

**Comment by SpiralBaka** [comment]
I'm not the developer, or rather, I'm not a developer at all, but I'll help a bit.
the problem is Webnovel.com changed the format of the page (is that what it's called?). right now it looks like this:

![webnovel 2](https://user-images.githubusercontent.com/70971903/163072026-327b45ad-eb45-431b-b94c-5a15a2f6bbae.png)

**chapterId** is the chapter title, and **contentId** is the start of the paragraph
from: [https://www.webnovel.com/book/high-human-in-crossed-worlds---a-hp-x-dxd-fic_21543904506831605/chapter-1---reunion_57831665485010231](https://www.webnovel.com/book/high-human-in-crossed-worlds---a-hp-x-dxd-fic_21543904506831605/chapter-1---reunion_57831665485010231)

btw, webnovel doesn't use bold, italic or underscore. basically, the chapters can be copied to notepad without a problem.

**Comment by dteviot** [comment]
@Kiradien @SpiralBaka 
Sorry, I've been busy with RL issues.
I hope to look into this in the next 3 to 7 days.

**Comment by Kiradien** [comment]
> @Kiradien @SpiralBaka Sorry, I've been busy with RL issues. I hope to look into this in the next 3 to 7 days.

No worries. RL takes clear priority.

If, when you do get around to it, you decide to go the JSON route as shared by SpiralBaka, I do have some modified code I can share to give you a boost. It works for the novels I read, but requires a major permission change (cookies) and is liable to fail - seriously doesn't feel anywhere near ready to check in. If you can get the page to render as before, it's definitely a preferable solution.

**Comment by dteviot** [comment]
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with first 8 chapters of
* https://www.webnovel.com/book/cultivation-chat-group_8299599706003805
* https://www.webnovel.com/book/high-human-in-crossed-worlds---a-hp-x-dxd-fic_21543904506831605

Notes, 
1. @SpiralBaka Thanks for telling me the wanted content was embedded in the page, just as a JSON blob.  I was going to try retrieving it via REST calls, which would have been painful.
2. Unfortunately, I think WebNovel DOES use bold.  the Cultivation Chat Group pages show  &lt;em&gt; elements.
3. @Kiradien fixExcaping() is really hacky.  Cleaner solution would be nice if you have any ideas.  I suspect you're going to suggest using InnerHtml.  Which might be a problem getting past Mozilla's audit.

Time taken: 231 minutes.  I'm going to charge you double my normal rates for this one.

**Comment by Kiradien** [comment]
@dteviot It isn't perfect, and doesn't solve 100% of the problems (\<p\> and \</p\> will likely still need manual replacement, \r\n will be included but should be handled naturally when included in html), however using the internal javascript JSON.parse will handle a LOT of the natural escaping of JSON.

    fixExcaping(s) {
        s = s.replace(/\\ /g, " ")
            .replace(/<p>/g, "")
            .replace(/<\/p>/g, "");

        return JSON.parse(`{ "content": ${s} }`).content;
    }

**Comment by Flwk** [comment]
@dteviot Thank you very much ! :)

**Comment by Battlesp1ke** [comment]
@dteviot I went to use the new Test version on https://www.webnovel.com/book/goddess-of-ice-reborn-as-naruto's-twin-sister_18923491906741805 it only got the first two chapters then stopped

**Comment by dteviot** [comment]
@Battlesp1ke @Flwk @SpiralBaka 
Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

This fixes issues with chapter 2 in  https://www.webnovel.com/book/goddess-of-ice-reborn-as-naruto's-twin-sister_18923491906741805

Tested with first 16 chapters of 3 stories referred to previously.

@Kiradien 
Unfortunately the code you suggested doesn't work.

For my notes, 200 minutes work.  (Error message returned by JSON.parse is NOT helpful to figure out where problem is in a string with 32k characters, because actual problem can be a long way from the reported position.)

**Comment by Flwk** [comment]
@dteviot 

I see that there is an error when i did the update : 

> Manifest version 2 is deprecated, and support will be removed in 2023. See https://developer.chrome.com/blog/mv2-transition/ for more details.

I know that the plugin continue to work, but are your planning to do something about it ? 

Thank you very much !

**Comment by dteviot** [comment]
@Flwk
I'm waiting for Firefox to support Manifest version 3.
Will update then.

**Comment by dteviot** [comment]
@Flwk
Feel free to raise an issue to remind me.

**Comment by dteviot** [comment]
@Battlesp1ke @Flwk @SpiralBaka @Flwk
Updated version (0.0.0.148) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.

**Comment by AkiraReader** [comment]
Tried the Updated version (0.0.0.148)  and in some novels while generating an epub I got an error like this:

Warning, unable to convert chapter '80: Chapter 0080' from 'https://www.webnovel.com/book/the-sims-system_22496982205621005/chapter-0080_61243826664171854' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. 
Conversion error message was: (This page contains the following errors:error on line 1 at column 1096: Specification mandates value for attribute right
Below is a rendering of the page up to the first error.)

**Comment by dteviot** [comment]
@AkiraReader,
Tricky.  That chapter has text like 
> &lt;Taki-kun and Miss Okudera should be already gone on a date at this time right? I'm so happy for him! But what is going on with this faint pain in my heart?&gt;

Which WebToEpub is interpreting as a HTML tag.  Which it isn't, and that's giving the error you see.

So, I can fix this case by treating it as a string.  But there are other cases where there actually are HTML tags embedded in the text.  e.g.  https://www.webnovel.com/book/cultivation-chat-group_8299599706003805/a-recipe_22377153626685532 has an &lt;em&gt; tag

And I can't see anything obvious to tell which is which.
Least worst case is probably tell WebToEpub to treat as text. (So won't give error, and provide script to fix up afterwards, when problems occur.)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

EpubEditor script to fix up the embedded "&lt;em&gt;" tags:
```javascript
            let modified = false;
            for(let p of [...dom.querySelectorAll("p")]) {
                let c = p.textContent;
                if (c.includes("<em>")) {
                    console.log(c);
                    p.innerHTML = c;
                    modified = true;
                }
            }
            return modified;
```

**Comment by AkiraReader** [comment]
It seems to work great, no more errors in any of the novels I tried it.

**Comment by Veaxale** [comment]
Im an amateur, is it really work?, im usually using webtoepub to fecth content from webnovel.com.
By using android in kiwibrowser.
Open the novel site> enable dekstop site>reload if the address still start with m.> click table of content> click weptoepub> unclick the very first chapter> copy all the listing chapter>replace all the chapter addres www. With m. > pack epub. Done.
But now the chapter included a giberish character in the top and bottom page -.-, is it because the update 🤔

**Comment by dteviot** [comment]
@Veaxale 
Can you send me the epub?  
e.g. email to dteviot@gmail.com
So I can see what's happening.

**Comment by Veaxale** [comment]
Well with same twik in default mode, its work again. 

{"DefaultParserConfigs":[["www.webnovel.com",{"contentCss":"Div.styles_content__3tuD4 _font_4928466444306607","titleCss":"h1","removeCss":"","testUrl":"https://m.webnovel.com/book/avatar-the-last-airbender-cold-paths_18359936606504505/chapter-1_49284664443066074"}],["m.webnovel.com",{"contentCss":"div.styles_content__3tuD4","titleCss":"h1","removeCss":"","testUrl":"https://m.webnovel.com/book/avatar-the-last-airbender-cold-paths_18359936606504505/chapter-1_49284664443066074"}]],"ReadingList"

Its great if there an option to replace www. With m. without opening external app.
I think this can be a reference for tricky site, to change desktop address to mobile and many more.
Well im amateur though 👍

**Comment by seba11998** [comment]
Im still getting the same error
```
Warning, unable to convert chapter '18: One hundred years' from 'https://www.webnovel.com/book/new-god-in-marvel_21731452906433805/one-hundred-years_59330697923456658' to valid XHTML. Your epub viewer may fail when viewing that chapter. You may need to fix the chapter manually with Calibre. 
Conversion error message was: (This page contains the following errors:error on line 1 at column 4381: Specification mandates value for attribute you
Below is a rendering of the page up to the first error.)
```
Source:
```
<Draw is in progress> 
After what seemed even longer than the first one. 
```
Extension's output:
```
<p><congratulation you've="" won="" the="" ability="" devourer"="" <="" p=""></congratulation></p>
<p>And for the last spin, the draw took even longer before finally</p>
```

**Comment by dteviot** [comment]
@seba11998 
Version in stores has not been updated yet.
You need to use the test versions mentioned earlier.
> Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers

**Comment by pavan3999** [comment]
hi there, i tried the test version but creator thoughts is not showing while select/unselect Remove Author Notes option and for annotations &lt; &gt; showing for < > symbols

**Comment by dteviot** [comment]
@pavan3999 
Please provide URL(s) of chapters showing problems.
Note, showing the & lt; & gt; may be due to previously mentioned inability to distinguish embedded HTML tags.

**Comment by budikesuma** [comment]
@SpiralBaka 
Hello bro...

   Yeah, you're both right and wrong, wrong because webnovel hasn't changed their site, since years ago I haven't failed to crawl their site.  

   Yes (in your SS image) you are right if they use the method of concatenating/merging between paragraphs, because I've seen that method too (I used the manual scripting method).  


For @Veaxale 
Hello bro...

You're using a RegEx commonly used by low-level novel site aggregators, if you're satisfied with that result. 

   It won't make any difference if you change `www.` to `m.`, because both results are the same.  

   What is clear is that your method has failed to scrape the important Translator's footnotes.  Try to see my epub in the SS image below(clickable footnotes style). 
Bottom image is from your RegEx method(only show number without footnote).

   I give a link for you to try, that there are footnotes in Chapter 1, Chapter 10, & so on. 
Test novel link:


  Tryout if you can scrape it like it appears on my epub. 

.
![Screenshot_20220520-151728_MiXplorer](https://user-images.githubusercontent.com/50254552/169494750-ef951556-34f4-45eb-ad21-9433c603f2a4.jpg)
.
![Screenshot_20220520-151907_MiXplorer](https://user-images.githubusercontent.com/50254552/169494771-7f575166-719b-46a7-b630-6c111ada95a0.jpg)
.
![Screenshot_20220520-153108_MiXplorer](https://user-images.githubusercontent.com/50254552/169494782-b3776199-fcb9-408a-89bf-fe1483ac0cfb.jpg)
.

**Comment by Veaxale** [comment]
@budikesuma
That true, the footnote not shown.

Since the 1st time i use webtoepub extension in android(im never using computer either though), it keep failed to fetch epub in webnovel using standard option.
I tweek the default option to m. etc.. Than idk, its work

r u using android? which browser that support webtoepub? The firefox not support anymore.

**Comment by dteviot** [comment]
@budikesuma
The Webnovel site definitely changed the layout of the non-mobile version of their website.  Which is what broke WebToEpub.
Note, the site provides a mobile and non-mobile version.  (the "m." URLs are the mobile version of the site.)
It's possible that the mobile version of the site wasn't changed.

Also, thanks for the info on the footnote.
It does get captured by WebToEpub for the non-mobile site.  
Unfortunately, the site is doing some non-standard HTML tags (and then probably some Javascript) to create the footnotes.
So, the text in the epub shows the HTML tags.

e.g. WebToEpub does this for a footnote.
```HTML
<p>Uncle Zhou, I remember there's a <anno data-annotation-id='bf4e5119-0b1a-4824-b756-387eb3d8a9c2'>wanton</anno> stall in the east of the city.</p>
```

```HTML
<annotations style='display: none;'><ol class='tinymce-annotation-container'><li data-annotation-id='bf4e5119-0b1a-4824-b756-387eb3d8a9c2'>Chinese dumplings</li></ol></annotations>
```

Can you provide a link to a chapter with author notes?

**Comment by dteviot** [comment]
I think I got Author Notes working for Webnovel site.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with chapter 1 of https://www.webnovel.com/book/cultivation-chat-group_8299599706003805

For my notes: 32 minutes

**Comment by budikesuma** [comment]
> 

Here are the links:

`https://www.webnovel.com/book/my-wife-is-a-general-who-killed-tens-of-thousands-on-the-battlefield_21344870605997705/57493349283716105`

`https://www.webnovel.com/book/my-wife-is-a-general-who-killed-tens-of-thousands-on-the-battlefield_21344870605997705/57568149360399612`

**Comment by dteviot** [comment]
@budikesuma 
Thanks, I'd already looked at them.
Those are foot notes, not author comments.

**Comment by budikesuma** [comment]
> @budikesuma Thanks, I'd already looked at them. Those are foot notes, not author comments.

This novel contains author's thoughts. 

Chapter link:
https://www.webnovel.com/book/the-nine-cauldrons_10270042106004105/convergence-of-every-party_28077343222702125

**Comment by dteviot** [comment]
@budikesuma 

Sorry for delay in responding.
Latest version of WebToEpub picks up the creators's thoughts section of https://www.webnovel.com/book/the-nine-cauldrons_10270042106004105/convergence-of-every-party_28077343222702125

**Comment by mcandre** [comment]
The problem seems to have reappeared. "No chapters found" error for webnovel.com entries.

**Comment by dteviot** [comment]
@mcandre 
Try the following steps:
1. Open a main page like https://www.webnovel.com/book/my-wife-is-a-general-who-killed-tens-of-thousands-on-the-battlefield_21344870605997705, 
2. Click on the "Table of Contents" tab to get the list of chapters.
3. Open WebToEpub.
