### ISSUE TITLE
Bypass Webnovel.com locked chapters 

### ISSUE THREAD

**Issue by MohamadTaher** [dteviot/WebToEpub#742]
Most of the novels now days are on Webnovel.com and they are locked after a certain point. 
Is it possible to download the chapters unlocked inside the file?

**Comment by budikesuma** [comment]
> Most of the novels now days are on Webnovel.com and they are locked after a certain point. Is it possible to download the chapters unlocked inside the file?

If you meant was how to unlock locked chapters, then you must had vip/coin/ss/etc. Scraper can't help you to do that.
Just close it...

**Comment by Kiradien** [comment]
As of a few weeks ago, unlocked chapters on Webnovel now return encrypted data as a result, and their javascript is obfuscated to all hell. They're abusing translation overlays to display text instead of standard rendering and basically doing everything they can possibly do to screw over the visually impaired. Regular chapters that were never locked do not have this issue.

Unlocking them doesn't really solve anything for scrapers anymore - The only reliable way to get the page data would be a screenshot and OCR after their code runs through, but it's just too much of a headache when I looked into it for myself. I do wonder how much this will hurt their bottom line, it's definitely stopped me from ever spending cash there again until they get half decent TTS in their official app.

It is possible to scrub the key and data used in the decryption itself, however it wasn't entirely clear which encryption algorithm was used beyond the substring and btoa/atob before being pumped in with the book id. Thing is, even if it's reverse engineered, they set the algorithm up to allow for easy cycling.

Honestly, your best bet is just using their app, just wish they'd fix its TTS.
