### ISSUE TITLE
Auto populate Filename as {title} - {author}

### ISSUE THREAD

**Issue by lastwomanstanding** [dteviot/WebToEpub#745]
**Is your feature request related to a problem? Please describe.**
Since I am mostly downloading from https://www.wattpad.com, I noticed that in the title section, it always populates as {title} - {profile name} - {website name}. Should it be {title} only?

> Ex. Maybe this time.. - lala ツ - Wattpad
> Link: https://www.wattpad.com/story/139729965-maybe-this-time

**Describe the solution you'd like**
Would it be possible to change the filename as {title} - {author} to avoid confusion if there is a book with similar title?

**Describe alternatives you've considered**
Instead of the Advanced Option "Use full title as file name", could you consider changing it as "Use {title} - {author} as file name" instead?

**Additional context**
![title and filename](https://user-images.githubusercontent.com/105410957/170205203-ab4b2f41-efe2-492a-89d3-3806a785e27a.png)
![advanced option](https://user-images.githubusercontent.com/105410957/170205900-c8b65cb5-23d8-42b4-ab00-71088f028ae6.png)

**Comment by dteviot** [comment]
@lastwomanstanding 
>Since I am mostly downloading from https://www.wattpad.com, I noticed that in the title section, it always populates as {title} - {profile name} - {website name}. Should it be {title} only?

Thanks for bringing this to my attention.
Looks like site had changed since I last checked.
I've fixed, so Title should now be correctly populated.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

> Would it be possible to change the filename as {title} - {author} to avoid confusion if there is a book with similar title?

That's not a bad idea. However, I want to keep it simple.  How often is there going to be a conflict?
I've got literally hundreds of epubs, and no conflicts.

**Comment by lastwomanstanding** [comment]
I appreciate your hardwork, always. Title is now properly populated.

> That's not a bad idea. However, I want to keep it simple. How often is there going to be a conflict?
> I've got literally hundreds of epubs, and no conflicts.

I've encountered this only once but it is okay since it is fixed whenever I add the epub in Calibre. The other issue I've raised regarding the chapter title is fixed as well. Thank you so much.

**Comment by dteviot** [comment]
@lastwomanstanding 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
