### ISSUE TITLE
Wordpress Category

### ISSUE THREAD

**Issue by lastwomanstanding** [dteviot/WebToEpub#767]
I don't know if this is a bug or not but when I encounter a story under a category, only the latest entry (chapter) is read. If it is not categorized, the whole story is read properly.

Example links:
https://onlinenovelbook.com/category/my-babys-daddy-novel/ (categorized as per url)
![image](https://user-images.githubusercontent.com/105410957/177485820-37c3aed9-6a5b-4193-9edb-fa3646bfd109.png)

https://onlinenovelbook.com/ive-got-a-super-rich-dad-chapter-list-complete/ (not categorized)
![image](https://user-images.githubusercontent.com/105410957/177485954-7cd7c27e-0326-434a-9721-ea04eb2f4c41.png)

If it is not a bug, can you add this site? Thank you so much for your hardwork as always

**Comment by dteviot** [comment]
@lastwomanstanding 
It's not a bug.  It's a case of different stories on the site have different ToC layouts.  And that one I didn't do.
I may fix it next weekend, I've been busy trying to clear the backlog.

**Comment by dteviot** [comment]
@lastwomanstanding 
Turns out I was wrong.  WebToEpub did NOT have a parser for this site and was defaulting to the Wordpress parser.  Which worked fine for all stories with the more conventional Table of Contents page.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with chapters 1 and 787 of 
* https://onlinenovelbook.com/category/my-babys-daddy/

For my notes: 41 minutes work

**Comment by dteviot** [comment]
@lastwomanstanding 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
