### ISSUE TITLE
Please add site https://maho.jp/

### ISSUE THREAD

**Issue by Ceynou** [dteviot/WebToEpub#787]
### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://maho.jp/works/16743963567755939717

### What settings did you use?  What didn't work?
* https://maho.jp/works/16743963567755939717#16743963567755983828
* div.jsx-2543593858
* div.jsx-499916335.chapters
* 

seems like it's only one page, the extracted content is the one on the main page no matter which "page" you're on, like the 4th page for example
https://maho.jp/works/16743963567755939717#16743963567755983829

**Comment by dteviot** [comment]
@Ceynou 
It's going to be a couple of weeks at least before I can get onto this.  
RL issues.

**Comment by Ceynou** [comment]
Thank you for even considering it!

**Comment by dteviot** [comment]
@Ceynou
This is a difficult site.  

I **hypothesize** it's making graphql queries to the server to get content for each page.  (i.e. It's another site where the text isn't in the HTML.  Instead javascript in the HTML makes calls to the server to get the content, then puts it into the web page.)
Due to the fact it's in Japanese, it adds another layer of difficulty.

I estimate it would probably take hours to days to figure out, so I'm going to have to say 
> Sorry, I'm not willing to do this, I don't have the time.

For my notes: 40 minutes work
