### ISSUE TITLE
[NovelHall] Bug prevents Epub Packing

### ISSUE THREAD

**Issue by DicerX** [dteviot/WebToEpub#790]
Description: When trying to pack the epub, the loading bar quickly zooms to Chapter 58, ending the process and promoting the SaveAs pop-up. The same issue occurs in Firefox, Chrome, and Chromium Edge.

Url Affected: https://www.novelhall.com/he-who-fights-with-monsters-16287/

**Comment by dteviot** [comment]
@DicerX 
The chapter which has a URL of https://www.novelhall.com/he-who-fights-with-monsters-16287/3937542.html
seems to be blank.  (Try opening that page in the browser directly.)

This causes WebToEpub to stop, because it can't find any content.
You can either remove the chapter from list of chapters to fetch.
Or under "Advanced Options", check the box for "Skip chapters that return HTTP 404 error"

**Comment by dteviot** [comment]
Closing, due to lack of response.
