### ISSUE TITLE
Please add site https://www.asianovel.net/

### ISSUE THREAD

**Issue by JasCU100** [dteviot/WebToEpub#806]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://www.asianovel.net/novels/1790

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

Yes, I tried it and I got the chapters but it has weird spacing. 

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
#container > div.wrapper > main > div:nth-child(5) > article
* CSS selector for element holding Title of Chapter
#container > div.wrapper > main > div:nth-child(5) > h2
* CSS selector for element(s) to remove

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@JasCU100 

Looks like the site has changed since the parser for it was written.
I've updated the parser.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with 
* https://www.asianovel.net/novels/1790, chapters 1 and 85

For my notes: 39 minutes work

**Comment by JasCU100** [comment]
Hello thank you for the update but it seems like the words in the chapters still have no spacing when I checked.

**Comment by dteviot** [comment]
@JasCU100 
>  chapters still have no spacing when I checked

If you mean there is no space between paragraphs/sentences, e.g.
![image](https://user-images.githubusercontent.com/5157081/188726080-5b1f0f28-9084-438d-a165-23a703186f0f.png)

this is how the text on the site is formatted.  And sorry, but you're stuck with that.

If you mean something else, please provide more detail.

**Comment by JasCU100** [comment]
> 

It seems like I was mistaken. It was the epub reader that was at fault because when I imported it to calibre the spacing was ok. Thank you!

**Comment by dteviot** [comment]
@JasCU100 
Reopening so I know to contact you when Chrome and Firefox stores are updated.

**Comment by dteviot** [comment]
@JasCU100 
Updated version (0.0.0.150) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
