### ISSUE TITLE
Please add site https://lightnovelread.com

### ISSUE THREAD

**Issue by marodev1** [dteviot/WebToEpub#813]
Hello guys,

Can u please add this website ? lightnovelread.com

Thanks for your hard work

**Comment by dteviot** [comment]
@marodev1 
Seems to be similar layout to https://goblinsguide.com/ (which is a problem)

Note, stories on this site have two ToC page types.
* https://lightnovelread.com/light-novels/transcending-the-nine-heavens-fr/
* https://lightnovelread.com/novel/transcending-the-nine-heavens-fr/ttnh-chapitre-2613-epee-du-ciel-violent-l-orient-respecte-le-soleil-fort/

You need to launch WebToEpub using the first type of URL.  I can't get the chapters from the second.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with:
* https://lightnovelread.com/light-novels/mere-dapprentissage-mother-of-learning-en-francais/ chapters 1, 108
* https://lightnovelread.com/light-novels/only-i-level-up/ chapters chapters 1, 377
* https://goblinsguide.com/category/fff-class-trashero/

Note, the crappy chapter titles in the Table of Contents are because that's what the site returns.

For my notes: 183 minutes work

**Comment by marodev1** [comment]
@dteviot It works perfectly :)

**Comment by dteviot** [comment]
@marodev1 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
