### ISSUE TITLE
Wattpad error 404 doesn't download 

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#832]
![Screenshot_20221015_042308](https://user-images.githubusercontent.com/115823113/195937080-ec97dc17-9399-4fcb-8a9f-f356aff8cde0.jpg)
**Describe the bug**
I want to convert Wattpad story to epub but as soon as I click the Pack it suddenly stop then it says error to fetch 

**Expected behavior**
I hope it will fix 

**Smartphone (please complete the following information):**
 - Device: Nova 5t
 - OS: emui 11
 - Browser kiwi Browser
 - Version

**Comment by dteviot** [comment]
@AngelBurn 
Under "Advanced Options" there's "Skip chapters that return HTTP 404 error".  
Normal behaviour with WebToEpub is stop when it can't fetch a chapter due to a 404.  (So you can decide how to fix it.  It usually means the URL for the chapter is wrong.)

If you check "Skip chapters that return HTTP 404 error", WebToEpub will continue to fetch the other chapters, and put a placeholder in the epub for the chapters it could not fetch.

**Comment by AngelBurn** [comment]
Thank you so much!
