### ISSUE TITLE
novelonomicon.com crashes webtoepub

### ISSUE THREAD

**Issue by Jonson26** [dteviot/WebToEpub#845]
**Describe the bug**
Whenever I try to use webtoepub on novelonomicon.com it simply refuses to work.

**To Reproduce**
1. Go to 'novelonomicon.com'
2. Click on any novel
3. Run WebToEpub

**Expected behavior**
WebToEpub functions as usual

**Error message**
sibling is undefined nextTocPageUrl@moz-extension://7f0183e0-ee83-40f4-8890-7047996bf1c2/js/parsers/NovelonomiconParser.js:27:9
walkTocPages@moz-extension://7f0183e0-ee83-40f4-8890-7047996bf1c2/js/Parser.js:671:33
getChapterUrls@moz-extension://7f0183e0-ee83-40f4-8890-7047996bf1c2/js/parsers/NovelonomiconParser.js:11:28
onLoadFirstPage@moz-extension://7f0183e0-ee83-40f4-8890-7047996bf1c2/js/Parser.js:378:14
processInitialHtml@moz-extension://7f0183e0-ee83-40f4-8890-7047996bf1c2/js/main.js:46:24
populateControlsWithDom@moz-extension://7f0183e0-ee83-40f4-8890-7047996bf1c2/js/main.js:222:27
onMessageListener@moz-extension://7f0183e0-ee83-40f4-8890-7047996bf1c2/js/main.js:16:36

**Desktop (please complete the following information):**
 - OS: Kubuntu 22.04.1 LTS x86_64
 - Browser Firefox
 - Version 105.0.3 (64-bit)

**Comment by dteviot** [comment]
@Jonson26 

Apologies, site has changed since the parser for the site was written.  Parser updated.

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with (1st chapters from):
* https://novelonomicon.com/category/novels/tensei-reijou-ha-shomin-no-aji-ni-ueteiru/
* https://novelonomicon.com/category/novels/avoid-the-death-route/

For my notes: 75 minutes work

**Comment by dteviot** [comment]
@Jonson26 

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
