### ISSUE TITLE
 add site https://sj.uukanshu.com/

### ISSUE THREAD

**Issue by Dlordload** [dteviot/WebToEpub#847]
Please note, I'm basically the only developer working on WebToEpub, and I'm not paid for doing this.  (WebToEpub is completely free, and generates no money.) By asking to add a site, you're asking me to give you some of my limited free time. So, I think it's not unreasonable for me to ask you to do as much as you can to help me.

### Provide URL for web page that contains Table of Contents (list of chapters) of a typical story on the site
https://sj.uukanshu.com/book.aspx?id=182256

### Did you try using the Default Parser for the site?  If not, why not?
Instructions for using the default parser can be found at https://dteviot.github.io/Projects/webToEpub_DefaultParser.html

### What settings did you use?  What didn't work?
* URL of first chapter
* CSS selector for element holding content to put into EPUB
* CSS selector for element holding Title of Chapter
* CSS selector for element(s) to remove
This
![Screenshot_20221030-232010](https://user-images.githubusercontent.com/87926179/198886665-0719220a-c027-45df-aacc-36f39e57a167.jpg)

### If the Default Parser did not work, if you have developer skills, did you try writing a new parser?
Instructions https://dteviot.github.io/Projects/webToEpub_FAQ.html#write-parser

**Comment by dteviot** [comment]
@Dlordload 

Strange, That sort of thing usually happens when site is not encoded using Unicode.  But site seems to be using Unicode. (UTF-8 to be specific)

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Tested with https://sj.uukanshu.com/book.aspx?id=182256, chapters 1 to 4

For my records: 34 minutes work

**Comment by Dlordload** [comment]
@dteviot okay it works now thank you very much!

**Comment by dteviot** [comment]
@Dlordload 

I didn't do anything, but it's working anyway.  (I hope.)

Updated version (0.0.0.151) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
If you can't wait, Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
