### ISSUE TITLE
Crappy 1 star rating with avast because of uninstall rate and other proprietary data they collect

### ISSUE THREAD

**Issue by belldandu** [dteviot/WebToEpub#85]
Not exactly sure what all avast is collecting to determine that webtoepub is potentially unwanted but when i was on my step sisters laptop this happened.
![whale then](https://cloud.githubusercontent.com/assets/5639384/20871533/c84bfe40-ba64-11e6-826f-bb42b1a6ef7d.png)

**Comment by belldandu** [comment]
Leaving this open so that people know we know about it.

**Comment by typhoon71** [comment]
I'll just say avast has many innocent victims.
I expecially find annoying how he messes with my audio player... ok, it's not mainstream, but it's like decades it exist... XD

**Comment by toshiya44** [comment]
Letting third party applications interfere with browser is a really bad idea. It will open up more security holes than it will solve. Not to mention the data collection as mentioned by themselves in your screenshot.

**Comment by dteviot** [comment]
What I'd like to know is where they are getting the Uninstall rate information from.
_I_ can get the uninstall rate information for the Chrome version of the plugin (It's about 66%  i.e. For every 3 people who install the plug-in, 2 of them uninstall.)  But I have no idea where to get it for Firefox.

**Comment by dteviot** [comment]
I found the stats for the Firefox version.
There's been 1,718 installs.  There are 365 copies still installed (so uninstall rate of 79%)   
On average 276 people use it per day.

**Comment by typhoon71** [comment]
Now: HOW do they count the install/uninstall?
Because if one unistalls and then reinstalls instead of updating the rates would be altered, and it would easily seem there's a lot of uninstall.

For example, when I was testing this addon in the early stages I removed and reinstalled every time, since I want to start over every time (both with ffox and chrome).

Also: do they count installs (and uninstall) from git? XD

Anyway, AV sometimes are plain stupid: this is a rather niche addon, obviously a lot of ppl will uninstall it, that rating is nonsensical. I still have stuff installed just in case, but disabled: does that count as good SW? ;)

**Comment by dteviot** [comment]
@typhoon71 
>Also: do they count installs (and uninstall) from git? XD

I would be very surprised if they do.

**Comment by toshiya44** [comment]
I think these un/install stats don't mean much. If you check some of the popular extensions, you'll see that uninstall rate is about 80%-95%

[80% - Ublock Origin. 95% - ABP]

**Comment by Evolution0** [comment]
@typhoon71 Did a scan in Avast, it no longer displays as a bad add-on.

**Comment by typhoon71** [comment]
@belldandu: and now your sister can feel safer than before! XD

**Comment by belldandu** [comment]
xD. Will close for now. If it happens again will just reopen. @toshiya44 @typhoon71 @Evolution0 @dteviot
