### ISSUE TITLE
panda-novel.com generates error when trying to download books

### ISSUE THREAD

**Issue by VorpalQ** [dteviot/WebToEpub#880]
**Describe the bug**
When trying to use the addon on panda-novel.com the following error occurs:

Fetch of URL 'https://www.panda-novel.com/api/book/chapters/1096/1' failed with network error 403. onResponseError@moz-extension://562a7ddd-608a-4c94-94e8-b620a317116f/js/HttpClient.js:32:25
checkResponseAndGetData@moz-extension://562a7ddd-608a-4c94-94e8-b620a317116f/js/HttpClient.js:166:45
wrapFetchImpl/<@moz-extension://562a7ddd-608a-4c94-94e8-b620a317116f/js/HttpClient.js:160:31

This occurs with any novel on the site.

**To Reproduce**
1. Go to panda-novel.com
2. Click on any novel
3. Click web2epub button in browser

**Expected behavior**
Screen for selecting chapters for web2epub to collect.

**Desktop (please complete the following information):**
 - OS: Windows 11
 - Browser Firefox
 - Version [107.0.1

**Comment by dteviot** [comment]
@VorpalQ 
The problem is site is trying to check if you're a person.
So, what you need to do is in the browser, open a tab and paste in the URL from the WebToEpub error message.
In the above case, it would be "https://www.panda-novel.com/api/book/chapters/1096/1"
Then respond to the CAPTCHA.  (e.g. Tick the "I'm a person" box, then select the required images.
You should then get a page of funny looking text.
At this point, WebToEpub will work.

**Comment by dteviot** [comment]
Closing, due to no response.
