### ISSUE TITLE
fannovel.com sometimes the chapter downloaded is raw [in cn]

### ISSUE THREAD

**Issue by Finks82** [dteviot/WebToEpub#896]
**Describe the bug**
[A clear and concise description of what the bug is.]

Sometimes the DL chapter is in raw form and if re-DL its on ENG
one of the example novel it happen https://www.fannovel.com/novel/699905728.html

**To Reproduce**

**Expected behavior**

**Screenshots**

**Desktop (please complete the following information):**
 - OS: [e.g. iOS] win 10
 - Browser [e.g. chrome, safari] firefox
108.0.1
Firefox Release
December 16, 2022

**Smartphone (please complete the following information):**

**Additional context**

**Comment by dteviot** [comment]
@Finks82 
Yes, it looks like the site randomly decides to send a chapter in Chinese, instead of English.  I already said that in https://github.com/dteviot/WebToEpub/issues/886
I assume it's some sort of anti-copy process.

My suggested workaround:
1. After downloading the epub, check to see which chapters are in Chinese.
2. Download another epub with the problem chapters.
3. Use MergeWebToEpub to replace the chapters.

**Comment by Finks82** [comment]
Found kind of bypass, just need to set DL delay chapter by 10second - tested and it work 99% all in ENG

**Comment by dteviot** [comment]
@Finks82 
I'll call this fixed then.
