### ISSUE TITLE
ChrysanthemumGarden requires user supplied "password" for some chapters

### ISSUE THREAD

**Issue by vanessabluellie** [dteviot/WebToEpub#907]
Hello! I'm really sorry for the bother again, but I'm having a big problem with this site source [https://chrysanthemumgarden.com/]. Even when I use the password to open a chapter individually, **WebToEpub can't grab the chapters anymore**. When the EPUB is generated, it only shows the screen of "Content is Password-Locked". Please please is there anyway at all to grab the chapters on this source, even if it's manually one by one, I really really hope there is some way to bypass it. I'm really sorry for the inconvenience. Thank you!

**Comment by dteviot** [comment]
@vanessabluellie 
I'll look into it, 
* Stupid question.  Have you tried to manually enter password and visit a locked page, then run WebToEpub?  (In case once you supply the password, the browser will have the necessary cookie(s) to access the locked chapters.)

If that doesn't work, 
* to save time can you give me the steps you use to view a password locked chapter (ignoring WebToEpub)?
* How do the steps differ for the second password locked chapter?
* Note, I'm not willing to visit the site's discord to collect the current password.

Notes:
Looks like password is submitted via a form, with a couple of hidden fields.

**Comment by dteviot** [comment]
@vanessabluellie 

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.

Notes:
1. I've added a "Password" input under the existing "Filename", that will only appear for ChrysanthemumGarden.  You will need to type the password there.
2. Password is NOT saved (because it's a password) so you'll need to enter it each time.
3. Incidentally, please don't post passwords to GitHub, it's public.

Tested with:
*  https://chrysanthemumgarden.com/novel-tl/ygbg/, chapters 70, 71

For my notes: 87 minutes work.  (That I'd rather have spent playing "Space Engineers".  Hmmm.  I have a problem.)

**Comment by vanessabluellie** [comment]
@dteviot 

Omg, thank you thank you so so so much, it worked really well!!! I'm really really sorry for taking up your precious time as well. But I had thought that adding the "password" option wasn't at all possible due to this being against some terms (or conditions?) of the Chrome webstore so if doing this could implicate you at all then please do not hestitate to remove it from the extension. But again, I still cannot thank you enough!!! :D

And I've also edited my previous comment (removing the password), thank you for censoring it!

**Comment by dteviot** [comment]
@vanessabluellie 
> I had thought that adding the "password" option wasn't at all possible due to this being against some terms (or conditions?) of the Chrome webstore

There are two separate things going on.
1. The site "scrambles" text, to discourage downloading.  This is copyright protection, and bypassing that is against Google's Terms and Conditions.  (You will note the epub still contains the scrambled text, and you'll need a separate tool to unscramble it.
2. The site requires you to provide a "password" to show you're entitled to view content.  It's perfectly OK for WebToEpub to ask you for the password and then pass it on to the site.  WebToEpub handling the password itself would not be OK.  (At least that's my understanding.  If I'm wrong, you can expect the changes to be reverted.)

**Comment by vanessabluellie** [comment]
Ah, so that's how it works, thank you for explaining to me! And thank you for also changing the title ahah, makes much more sense now. :D

**Comment by dteviot** [comment]
@vanessabluellie 
Updated version (0.0.0.152) has been submitted to Firefox and Chrome stores.
Firefox version is available now.
Chrome might be available in 1 to 3 weeks.
