### ISSUE TITLE
Please add site novelebook.com

### ISSUE THREAD

**Issue by AngelBurn** [dteviot/WebToEpub#917]

**Comment by dteviot** [comment]
@AngelBurn.
Sorry, not possible, at least some of the content on each page is encrypted.

**Comment by dteviot** [comment]
For my notes: 
Time spent 45 minutes.
Note to self, check for encryption BEFORE starting work

**Comment by AngelBurn** [comment]
Thank u for your time im sorry i understand

**Comment by gamebeaker** [comment]
@dteviot as an idea: My understanding is that Websites use custom fonts to scramble text. 
In EPUB3 it should be possible to embed custom fonts. 
If WebToEpub knows which class is scrambled it applies the custom font for the website.
Only an idea i don't plan to implement it at the moment.

**Comment by dteviot** [comment]
Hmm.  It's possible it's using a scrambled font. I'll check again.  Custom fonts can be worked around.  I've a tool to descramble them.

**Comment by dteviot** [comment]
I did have a plan for dealing with these difficult sites.  Basically, instead of making a fetch call to get the HTML, instead open each page in a tab.  Which would allow the page to open normally (and do any decrypting it needed), then inject a content script into the page to extract the now decrypted/loaded content.  Just haven't been bothered enough to do the work.

**Comment by gamebeaker** [comment]
@dteviot i think that my approach (if it is only the font, i have seen it on one page but don't remember which) wouldn't violate Google's terms of service because it is the same as every browser it just takes a copy from the page and displays this copy with the original font and doesn't "decode" the scramble. The text in the epub file is still scrambled but displayed with the right font. If someone tries to copy the text from the epub in a text ducument he gets scramble.

**Comment by dteviot** [comment]
I've seen at least 2 sites that use the font technique.

**Comment by dteviot** [comment]
@gamebeaker
It's definitely encrypted text.
If you open a page in Chrome dev tools, you can see the text that was scrambled in the network tab is NOT scrambled on the elements tab.
If it was using the font technique, on the elements tab, the text would still appear scrambled.
