### ISSUE TITLE
Support for https://allnovelbook.com/

### ISSUE THREAD

**Issue by MohamadTaher** [dteviot/WebToEpub#940]
Hello, this site is not supported https://allnovelbook.com/ can you please add it? Thank you so much for your effort.

**Comment by dteviot** [comment]
@MohamadTaher 

Site seems to also be called https://readnoveldaily.com/

Test versions for Firefox and Chrome have been uploaded to https://drive.google.com/drive/folders/1B_X2WcsaI_eg9yA-5bHJb8VeTZGKExl8?usp=sharing. Pick the one suitable for you, follow the "How to install from Source (for people who are not developers)" instructions at https://github.com/dteviot/WebToEpub/tree/ExperimentalTabMode#user-content-how-to-install-from-source-for-people-who-are-not-developers and let me know how it goes.
Tested with:
* https://readnoveldaily.com/novel/im-really-not-the-demon-gods-lackey-2023-2337

For my notes: 48 minutes work

**Comment by MohamadTaher** [comment]
@dteviot 

It did work after downloading the 0.0.0.154 version, but it didn't work with 0.0.0.152 which is on the extension store. 

Any reason the extension store version isn't up to date?

**Comment by gamebeaker** [comment]
@MohamadTaher it depends which store you mean.
Firefox has version 0.0.0.153
https://addons.mozilla.org/de/firefox/addon/webtoepub-for-baka-tsuki/
Chrome has version 0.0.0.152
https://chrome.google.com/webstore/detail/webtoepub/akiljllkbielkidmammnifcnibaigelm
The reason is that chrome takes longer until a new version is aproved and published on the store.
The downloaded zip was 0.0.0.154 because version 0.0.0.153 is published(firefox store). Now that there are Changes to WebToEpub (added support for allnovelbook.com) it isn't version 0.0.0.153 anymore. That's why it is version 0.0.0.154. And new versions are only submitted to the store if there are "enough" changes done compared to the previous version. Because submitting a new  version to the store takes time and effort.

**Comment by MohamadTaher** [comment]
Got it thanks a lot for all the efforts.
