### ISSUE TITLE
Epub size should not be unnecessarily large ( more than 100 MB)

### ISSUE THREAD

**Issue by acestronautical** [dteviot/WebToEpub#942]
**Describe the bug**
The generated Epub is massive in size.

**To Reproduce**
1. Go to https://www.royalroad.com/fiction/8894/everybody-loves-large-chests
2. Use WebToEpub to convert to Epub
3. The Epub produced is ~350 MB

**Expected behavior**
Epub is a reasonable size (less than 100 MB)

**Desktop (please complete the following information):**
 - OS: MacOS
 - Browser: Firefox
 - Version: Newest
 
**Additional context**
Using calibre to convert the epub to mobi and then back to epub produces an epub which is a magnitude smaller (22 MB).
I'm not sure where all this filesize bloat is coming from, but given that Calibre is able to reduce the size so drastically, this feels like a bug.

**Comment by gamebeaker** [comment]
@acestronautical it isn't a bug. 
Why is the file size a problem?
Through converting the EPUB Calibre changed the original pictures to a lower resulution.
Example: In the Chapter "Eat And Grow 2" is a picture. In the Epub with 390MB the picture has 349KB after converting through calibre the same picture has 25,8KB.
You can even create a smaler epub through calibre if you convert epub to epub the new epub has 50MB. It looks like calibre is more agressive with the resolution lowering if you convert to mobi.
If you unzip your massive ebup you can see, that the images folder takes 390MB space and the Text folder only 11MB. The probleme is that the story has a lot of Pictures with "high" resolution. In the Converted EPUB (Mobi->Epub) the images folder takes only 11,5MB and the content still ~11MB.
It could be a new feature request that WebToEpub automatically tries to lower the resolution of pictures, so that the EPUB size is smaller.

**Comment by dteviot** [comment]
@acestronautical 
There is a "Skip Images" option under "Advanced Options".  This will remove all images (and their size) from the epub.

@gamebeaker 
>It could be a new feature request that WebToEpub automatically tries to lower the resolution of pictures, so that the EPUB size is smaller.

It's unlikely I would try to implement this in WebToEpub, trying to shrink images can be tricky.
