### ISSUE TITLE
Bloqueo por pedido de los dueños de las páginas 

### ISSUE THREAD

**Issue by Alastorwill** [dteviot/WebToEpub#954]
Quisiera saber si no ay una manera de usar webtoepub en una página bloqueada por webtoepub a pedido de los dueños se que no la pueden desbloquear por las reglas de play stores pero quisiera que hicieran una forma de desbloquear esas páginas por nosotros mismos después de todo después de instalar si nosotros asemos cambios a la aplicación es nuestra responsabilidad también quisiera agregar que sería bueno que hicieran que uno pudiera escoger de cuentas capítulos querían copilar no solo manual sino poder Aser que se separen en 50 o 100 o 500 con unos pocos clips

**Comment by kolbdog3333** [comment]
Here is an english translation on what that persion is trying to say. 
I would like to know if there isn't a way to use webtoepub on a page blocked by webtoepub at the request of the owners. I know they can't unblock it due to play store rules, but I would like them to make a way to unblock those pages by ourselves after all. to install if we make changes to the application it is our responsibility I would also like to add that it would be good if they made it possible for one to choose from accounts chapters they wanted to compile not only manually but to be able to separate them into 50 or 100 or 500 with a few clips

**Comment by dteviot** [comment]
@Alastorwill 
You can build your own version of WebToEpub with the site blocks removed.
Basically, remove the disabled() function from the parser for the site, rebuild WebToEpub and load the new build into your browser.    Refer https://github.com/dteviot/WebToEpub for details on how to build and load.

As regards separate into blocks, that can already be done.  just shift-click on the check boxes to select/unselect a range.

@kolbdog3333 Thanks for the translation.

Apologies for delay in responding, but I've had RL issues for last 4 weeks.
